"""Reviewed carry research universe; identities are not trading recommendations."""
EQUITIES = {'AAPL': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'ABBV': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'ABT': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'ACN': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'ADBE': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'AMGN': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'AMZN': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'AVGO': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'AXP': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'BAC': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'BLK': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'BMY': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'BRK-B': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'C': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'CAT': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'COST': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'CRM': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'CSCO': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'CVX': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'DE': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'DGRO': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'DHR': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'DIA': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'DVY': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'EEM': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'EFA': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'EWA': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'EWC': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'EWG': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'EWH': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'EWJ': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'EWT': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'EWU': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'EWY': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'EWZ': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'F': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'GE': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'GILD': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'GM': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'GOOGL': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'GS': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'HD': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'HDV': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'HON': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'IBM': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'INDA': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'IWM': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'IYR': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'JNJ': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'JPM': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'KO': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'LLY': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'LOW': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'MA': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'MCD': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'MCHI': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'MDT': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'MDY': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'META': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'MMM': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'MRK': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'MS': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'MSFT': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'MTUM': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'NKE': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'NOBL': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'NVDA': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'PEP': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'PFE': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'PG': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'QCOM': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'QQQ': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'QUAL': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'RSP': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'SBUX': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'SCHD': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'SCHH': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'SCHW': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'SPGI': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'SPHD': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'SPY': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'T': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'TGT': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'TMO': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'TSLA': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'TXN': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'UNH': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'USMV': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'V': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'VEA': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'VLUE': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'VNQ': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'VTI': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'VWO': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'VYM': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'VZ': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'WFC': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'WMT': {'expected_quote_currency': 'USD', 'expected_type': 'equity'},
 'XLB': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'XLC': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'XLE': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'XLF': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'XLI': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'XLK': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'XLP': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'XLRE': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'XLU': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'XLV': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'XLY': {'expected_quote_currency': 'USD', 'expected_type': 'etf'},
 'XOM': {'expected_quote_currency': 'USD', 'expected_type': 'equity'}}

FX = {'AUD': {'legacy_alias': 'AUD', 'rate_kind': 'interbank_three_month_monthly', 'series': 'IR3TIB01AUM156N'},
 'BRL': {'legacy_alias': 'BRL', 'rate_kind': 'central_bank_monthly', 'series': 'IRSTCB01BRM156N'},
 'CAD': {'legacy_alias': 'CAD', 'rate_kind': 'interbank_three_month_monthly', 'series': 'IR3TIB01CAM156N'},
 'CHF': {'legacy_alias': 'CHF', 'rate_kind': 'interbank_three_month_monthly', 'series': 'IR3TIB01CHM156N'},
 'DKK': {'legacy_alias': 'DKK', 'rate_kind': 'interbank_three_month_monthly', 'series': 'IR3TIB01DKM156N'},
 'EUR': {'legacy_alias': 'EUR', 'rate_kind': 'interbank_three_month_monthly', 'series': 'IR3TIB01EZM156N'},
 'GBP': {'legacy_alias': 'GBP', 'rate_kind': 'interbank_three_month_monthly', 'series': 'IR3TIB01GBM156N'},
 'IDR': {'legacy_alias': 'IDN', 'rate_kind': 'interbank_three_month_monthly', 'series': 'IR3TIB01IDM156N'},
 'INR': {'legacy_alias': 'INR', 'rate_kind': 'interbank_three_month_monthly', 'series': 'IR3TIB01INM156N'},
 'JPY': {'legacy_alias': 'JPY', 'rate_kind': 'interbank_three_month_monthly', 'series': 'IR3TIB01JPM156N'},
 'KRW': {'legacy_alias': 'KOR', 'rate_kind': 'interbank_three_month_monthly', 'series': 'IR3TIB01KRM156N'},
 'MXN': {'legacy_alias': 'MXN', 'rate_kind': 'interbank_three_month_monthly', 'series': 'IR3TIB01MXM156N'},
 'NOK': {'legacy_alias': 'NOK', 'rate_kind': 'interbank_three_month_monthly', 'series': 'IR3TIB01NOM156N'},
 'NZD': {'legacy_alias': 'NZD', 'rate_kind': 'interbank_three_month_monthly', 'series': 'IR3TIB01NZM156N'},
 'SEK': {'legacy_alias': 'SEK', 'rate_kind': 'interbank_three_month_monthly', 'series': 'IR3TIB01SEM156N'},
 'TRY': {'legacy_alias': 'TUR', 'rate_kind': 'interbank_three_month_monthly', 'series': 'IR3TIB01TRM156N'},
 'USD': {'legacy_alias': 'USD', 'rate_kind': 'effective_overnight', 'series': 'DFF'},
 'ZAR': {'legacy_alias': 'ZAR', 'rate_kind': 'interbank_three_month_monthly', 'series': 'IR3TIB01ZAM156N'}}

FIXED_INCOME = {'EM_USD': {'kind': 'credit_index_yield', 'series': 'BAMLEMCBPIEY'},
 'HY_CCC': {'kind': 'credit_index_yield', 'series': 'BAMLH0A3HYCEY'},
 'HY_CRED': {'kind': 'credit_index_yield', 'series': 'BAMLH0A0HYM2EY'},
 'IG_AAA': {'kind': 'credit_index_yield', 'series': 'BAMLC0A1CAAAEY'},
 'IG_CRED': {'kind': 'credit_index_yield', 'series': 'BAMLC0A0CMEY'},
 'MUNI': {'kind': 'unresolved_definition', 'series': 'BAMLU0A0CMEY'},
 'TIPS_10Y': {'kind': 'real_yield', 'series': 'DFII10'},
 'UST_10Y': {'kind': 'nominal_treasury_yield', 'series': 'DGS10'},
 'UST_1M': {'kind': 'nominal_treasury_yield', 'series': 'DGS1MO'},
 'UST_1Y': {'kind': 'nominal_treasury_yield', 'series': 'DGS1'},
 'UST_20Y': {'kind': 'nominal_treasury_yield', 'series': 'DGS20'},
 'UST_2Y': {'kind': 'nominal_treasury_yield', 'series': 'DGS2'},
 'UST_30Y': {'kind': 'nominal_treasury_yield', 'series': 'DGS30'},
 'UST_3M': {'kind': 'nominal_treasury_yield', 'series': 'DGS3MO'},
 'UST_3Y': {'kind': 'nominal_treasury_yield', 'series': 'DGS3'},
 'UST_5Y': {'kind': 'nominal_treasury_yield', 'series': 'DGS5'},
 'UST_6M': {'kind': 'nominal_treasury_yield', 'series': 'DGS6MO'},
 'UST_7Y': {'kind': 'nominal_treasury_yield', 'series': 'DGS7'}}

FRED = {'BAMLC0A0CMEY': {'frequency': 'D', 'kind': 'credit_index_yield', 'unit': 'Percent'},
 'BAMLC0A1CAAAEY': {'frequency': 'D', 'kind': 'credit_index_yield', 'unit': 'Percent'},
 'BAMLEMCBPIEY': {'frequency': 'D', 'kind': 'credit_index_yield', 'unit': 'Percent'},
 'BAMLH0A0HYM2EY': {'frequency': 'D', 'kind': 'credit_index_yield', 'unit': 'Percent'},
 'BAMLH0A3HYCEY': {'frequency': 'D', 'kind': 'credit_index_yield', 'unit': 'Percent'},
 'BAMLU0A0CMEY': {'frequency': 'D', 'kind': 'unresolved_definition', 'unit': 'Percent'},
 'DFF': {'frequency': 'D', 'kind': 'effective_overnight', 'unit': 'Percent'},
 'DFII10': {'frequency': 'D', 'kind': 'real_yield', 'unit': 'Percent'},
 'DGS1': {'frequency': 'D', 'kind': 'nominal_treasury_yield', 'unit': 'Percent'},
 'DGS10': {'frequency': 'D', 'kind': 'nominal_treasury_yield', 'unit': 'Percent'},
 'DGS1MO': {'frequency': 'D', 'kind': 'nominal_treasury_yield', 'unit': 'Percent'},
 'DGS2': {'frequency': 'D', 'kind': 'nominal_treasury_yield', 'unit': 'Percent'},
 'DGS20': {'frequency': 'D', 'kind': 'nominal_treasury_yield', 'unit': 'Percent'},
 'DGS3': {'frequency': 'D', 'kind': 'nominal_treasury_yield', 'unit': 'Percent'},
 'DGS30': {'frequency': 'D', 'kind': 'nominal_treasury_yield', 'unit': 'Percent'},
 'DGS3MO': {'frequency': 'D', 'kind': 'nominal_treasury_yield', 'unit': 'Percent'},
 'DGS5': {'frequency': 'D', 'kind': 'nominal_treasury_yield', 'unit': 'Percent'},
 'DGS6MO': {'frequency': 'D', 'kind': 'nominal_treasury_yield', 'unit': 'Percent'},
 'DGS7': {'frequency': 'D', 'kind': 'nominal_treasury_yield', 'unit': 'Percent'},
 'IR3TIB01AUM156N': {'frequency': 'M', 'kind': 'interbank_three_month_monthly', 'unit': 'Percent'},
 'IR3TIB01CAM156N': {'frequency': 'M', 'kind': 'interbank_three_month_monthly', 'unit': 'Percent'},
 'IR3TIB01CHM156N': {'frequency': 'M', 'kind': 'interbank_three_month_monthly', 'unit': 'Percent'},
 'IR3TIB01DKM156N': {'frequency': 'M', 'kind': 'interbank_three_month_monthly', 'unit': 'Percent'},
 'IR3TIB01EZM156N': {'frequency': 'M', 'kind': 'interbank_three_month_monthly', 'unit': 'Percent'},
 'IR3TIB01GBM156N': {'frequency': 'M', 'kind': 'interbank_three_month_monthly', 'unit': 'Percent'},
 'IR3TIB01IDM156N': {'frequency': 'M', 'kind': 'interbank_three_month_monthly', 'unit': 'Percent'},
 'IR3TIB01INM156N': {'frequency': 'M', 'kind': 'interbank_three_month_monthly', 'unit': 'Percent'},
 'IR3TIB01JPM156N': {'frequency': 'M', 'kind': 'interbank_three_month_monthly', 'unit': 'Percent'},
 'IR3TIB01KRM156N': {'frequency': 'M', 'kind': 'interbank_three_month_monthly', 'unit': 'Percent'},
 'IR3TIB01MXM156N': {'frequency': 'M', 'kind': 'interbank_three_month_monthly', 'unit': 'Percent'},
 'IR3TIB01NOM156N': {'frequency': 'M', 'kind': 'interbank_three_month_monthly', 'unit': 'Percent'},
 'IR3TIB01NZM156N': {'frequency': 'M', 'kind': 'interbank_three_month_monthly', 'unit': 'Percent'},
 'IR3TIB01SEM156N': {'frequency': 'M', 'kind': 'interbank_three_month_monthly', 'unit': 'Percent'},
 'IR3TIB01TRM156N': {'frequency': 'M', 'kind': 'interbank_three_month_monthly', 'unit': 'Percent'},
 'IR3TIB01ZAM156N': {'frequency': 'M', 'kind': 'interbank_three_month_monthly', 'unit': 'Percent'},
 'IRSTCB01BRM156N': {'frequency': 'M', 'kind': 'central_bank_monthly', 'unit': 'Percent'}}

COMMODITIES = ('GLD', 'SLV', 'USO', 'BNO', 'UNG', 'DBA', 'DBC', 'DBB', 'CPER', 'PPLT', 'PALL', 'CORN', 'WEAT', 'VXX')

ECB_EURIBOR_ID = 'FM.M.U2.EUR.RT.MM.EURIBOR3MD_.HSTA'
ECB_EURIBOR_URL = 'https://data-api.ecb.europa.eu/service/data/FM/M.U2.EUR.RT.MM.EURIBOR3MD_.HSTA?format=csvdata'
FMP_PATHS = ('profile', 'historical-price-eod/light', 'historical-price-eod/non-split-adjusted', 'dividends', 'splits', 'ratios-ttm', 'key-metrics-ttm')
