import json, boto3
lam=boto3.client("lambda",region_name="us-east-1"); s3=boto3.client("s3",region_name="us-east-1")
lam.invoke(FunctionName="justhodl-retail-sentiment", InvocationType="RequestResponse")
d=json.loads(s3.get_object(Bucket="justhodl-dashboard-live",Key="data/retail-sentiment.json")["Body"].read())
r=d.get("ranked",{})
print("#2 crowded_exhaustion:", len(r.get("crowded_exhaustion",[])), "| capitulation:", len(r.get("capitulation",[])))
t30=d.get("top_30_by_mentions",[])
print("  crowding_score coverage:", sum(1 for e in t30 if e.get("crowding_score") is not None),"/",len(t30))
ex=r.get("crowded_exhaustion",[])
if ex: print("  sample exhaustion:", ex[0].get("ticker"), "bull",ex[0].get("stwt_bull_pct"),"crowd",ex[0].get("crowding_score"))
print("#3 squeeze_radar:", len(r.get("squeeze_radar",[])))
print("  short_pct coverage:", sum(1 for e in t30 if e.get("short_pct") is not None),"/",len(t30), "| squeeze_score:", sum(1 for e in t30 if e.get("squeeze_score") is not None))
sq=r.get("squeeze_radar",[])
if sq: print("  sample squeeze:", sq[0].get("ticker"),"heat",sq[0].get("heat"),"short",sq[0].get("short_pct"),"score",sq[0].get("squeeze_score"))
