import urllib.request, json, time
j=json.loads(urllib.request.urlopen(urllib.request.Request("https://justhodl-data-proxy.raafouis.workers.dev/data/attention-confluence.json?t=%d"%int(time.time()),headers={"User-Agent":"Mozilla/5.0"}),timeout=25).read())
print("top:",list(j.keys()))
print("stages:",list(j.get("stages",{}).keys()))
print("panels:",list(j.get("panels",{}).keys()))
t=j["stages"]["stealth"][0] if j["stages"]["stealth"] else (j["stages"]["igniting"][0] if j["stages"]["igniting"] else {})
print("ticker record keys:",list(t.keys()))
print("subscores:",t.get("subscores"))
print("sample options panel[0]:", (j["panels"]["unusual_options"] or [{}])[0])
print("sample insider panel[0]:", (j["panels"]["insider_clusters"] or [{}])[0])
print("sample smartmoney[0]:", (j["panels"]["smart_money"] or [{}])[0])
print("sample darkpool[0]:", (j["panels"]["dark_pool_accumulation"] or [{}])[0])
print("sample congress[0]:", (j["panels"]["congress_buys"] or [{}])[0])
print("sample theme[0]:", (j["panels"]["theme_attention"] or [{}])[0])
print("DONE 2586")
