const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const ui=require('../jh-aaii-research.js'),fixture=()=>JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/aaii-native.json'),'utf8'));
function fetcher(objects){return async url=>{const text=objects[url.slice(1)];return {ok:typeof text==='string',status:typeof text==='string'?200:404,arrayBuffer:async()=>new TextEncoder().encode(text).buffer};};}
test('Python-produced retained bytes and output bind in JavaScript',async()=>{const f=fixture();assert.equal(await ui.verifyPacket(f.packet,fetcher(f.artifacts)),f.packet);});
test('tampered value, wrong source run and changed output are refused',async()=>{
 const f=fixture(),changed=structuredClone(f.packet);changed.observation.bullish_pct=99;await assert.rejects(ui.verifyPacket(changed,fetcher(f.artifacts)),/Current packet differs/);
 const run=JSON.parse(f.artifacts[f.packet.replay.manifest_key]);f.artifacts[run.output.key]+=' ';await assert.rejects(ui.verifyPacket(f.packet,fetcher(f.artifacts)),/Output bytes differ/);
});
test('legacy packets and self-qualified votes are not native research',()=>{assert.equal(ui.typed({latest:{bullish:.28}}),false);const p=fixture().packet;p.calls_eligible=true;assert.equal(ui.typed(p),false);});
test('percentage categories and percentage-point spread remain distinct',()=>{const h=ui.render(fixture().packet,Date.parse('2026-09-20T14:00:00Z'));assert.match(h,/>28.8 <small>%/);assert.match(h,/>-24.5 <small>pp/);assert.match(h,/not allocations, transactions/);assert.doesNotMatch(h,/undefined|NaN/);});
test('current zero is displayed and exact accessible measure label is short',()=>{const p=fixture().packet;p.observation.bullish_pct=0;const h=ui.render(p,Date.parse(p.generated_at));assert.match(h,/>0 <small>%/);assert.match(h,/<label for="aaii-metric">Measure<\/label><select id="aaii-metric">/);});
test('recent generation cannot turn an overdue source into current research',()=>{const p=fixture().packet;p.generated_at='2026-09-24T20:00:00Z';assert.equal(ui.current(p,Date.parse(p.generated_at)),false);assert.match(ui.render(p,Date.parse(p.generated_at)),/Current survey use is withheld/);});
test('a missing survey week stays a gap and visible missing table row',()=>{const p=fixture().packet;p.history=p.history.filter(r=>r.week_ending!=='2026-08-12');const h=ui.history(p,'bull_bear_spread_pp');assert.equal((h.match(/<polyline /g)||[]).length,2);assert.match(h,/2026-08-12<\/td><td>Unavailable/);assert.match(h,/Missing week/);assert.match(h,/fixed scale/);});
test('original-source display escapes text and does not expose protected archive URLs',()=>{const p=fixture().packet;p.source_evidence.main.acquired_at='<img onerror=x>';const h=ui.render(p,Date.parse(p.generated_at));assert.match(h,/&lt;img/);assert.doesNotMatch(h,/<img|href="[^\"]*audit-private/);assert.match(h,/not independent source confirmation/);});
test('AAII page declares its native renderer and offers portfolio scenarios',()=>{const h=fs.readFileSync(path.join(__dirname,'../aaii.html'),'utf8');assert.match(h,/jh-aaii-research.js\?v=20260920-native1/);assert.match(h,/position-sizer.html/);assert.doesNotMatch(h,/jh-page-ai.js/);});
test('AAII current packet and request status bypass the edge cache; originals stay private',async()=>{
 const {pathToFileURL}=require('node:url');const worker=(await import(pathToFileURL(path.join(__dirname,'../cloudflare/workers/justhodl-data-proxy/src/index.js')).href)).default;
 const calls=[],stored=[];globalThis.caches={default:{match:async()=>undefined,put:async(...args)=>stored.push(args)}};globalThis.fetch=async url=>{calls.push(String(url));return new Response('{}',{status:200});};
 for(const key of ['data/aaii-sentiment.json','data/aaii-research/requests/'+'a'.repeat(64)+'.json']){const waits=[];const response=await worker.fetch(new Request('https://justhodl.ai/'+key),{},{waitUntil:p=>waits.push(p)});await Promise.all(waits);assert.equal(response.status,200);assert.equal(response.headers.get('Cache-Control'),'no-store');}
 assert.equal(stored.length,0);const before=calls.length;const response=await worker.fetch(new Request('https://justhodl.ai/audit-private/20260909-originals/aaii-sentiment/'+'a'.repeat(64)+'.bin'),{},{waitUntil(){}});assert([401,403].includes(response.status));assert.equal(calls.length,before);
});
