const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),test=require('node:test');
const source=fs.readFileSync(path.join(__dirname,'../jh-ai-command.js'),'utf8');
async function render(doc,ai={},code=source){const nodes={},calls=[];const main={firstChild:null,insertBefore(n){nodes[n.id]=n;}};const env={window:{},document:{getElementById:id=>nodes[id]||(id==='main'?main:null),body:main,createElement:()=>({style:{},innerHTML:''})},fetch:async url=>{calls.push(url);return{ok:true,json:async()=>url.includes('ai-student')?doc:ai};}};vm.runInNewContext(code,env);await new Promise(r=>setImmediate(r));return{html:nodes['jh-ai-command'].innerHTML,calls};}
function packet(){return{decision_status:'ADVISORY_ONLY',market_exam_holdout:{score:.9,prior_score:.5,beats_prior:true},coding_exam:{passed:'9/10',score:.9},calls:{graded:25,made:11,graded_unit:'reported_window',qualification:{contract:'market-read-reported-outcomes.v1'}},next_lesson:'Qualify source marks',can_do:['Invented capability'],cannot_do_yet:['Invented limitation']};}
test('actual overlay never promotes weights because a reported exam comparison wins',async()=>{const {html}=await render(packet());assert.match(html,/YES \(reported comparison\)/);assert.doesNotMatch(html,/promote path open|do not promote weights/);assert.match(html,/do not establish forecasting skill/);});
test('reported windows and calls have separate denominators',async()=>{const {html}=await render(packet());assert.match(html,/Reported outcome windows/);assert.match(html,/>25<\/span>/);assert.match(html,/Calls recorded/);assert.doesNotMatch(html,/25 \/ 11|Calls graded/);});
test('legacy narratives and counts stay withheld until the new projection exists',async()=>{let d=packet();delete d.calls.qualification;d.next_lesson='Market skill exists; promote';const {html}=await render(d);assert.match(html,/validation unavailable/);assert.doesNotMatch(html,/Market skill exists/);});
test('all received text is escaped before insertion into the actual overlay',async()=>{const bad='<img src=x onerror=attack()>',d=packet();d.voice=bad;d.decision_status=bad;d.pipeline=bad;d.coding_exam.passed=bad;d.next_lesson=bad;d.can_do=[bad];d.cannot_do_yet=[bad];const {html}=await render(d);assert.ok(!html.includes('<img'));assert.equal((html.match(/&lt;img/g)||[]).length,7);});
test('zero is retained while booleans and numeric text stay unavailable',async()=>{let d=packet();d.calls.graded=0;d.calls.made=0;d.market_exam_holdout.score=0;let out=await render(d);assert.match(out.html,/>0<\/span>/);assert.match(out.html,/0\.0%/);d.calls.graded=true;d.calls.made='25';d.market_exam_holdout.score=true;d.coding_exam.score=Infinity;out=await render(d);assert.match(out.html,/unavailable/);assert.ok(!out.html.includes('100.0%'));assert.ok(!out.html.includes('Infinity'));});
test('overlay preserves only its two existing read requests',async()=>{const out=await render(packet());assert.deepEqual(out.calls,['/data/ai-student-desk.json','/data/ai.json']);});

test('retained actual overlay reproduces promotion and HTML insertion defects',async()=>{const old=fs.readFileSync(path.join(__dirname,'fixtures/ai-command-pre-outcomes-20261002.js'),'utf8');assert.equal(require('node:crypto').createHash('sha256').update(old).digest('hex'),'8999914bb5ce1a3e9e87a5a6a9ce6bf725a56d3dbb7354ba99a4523755467819');const d=packet();d.voice='<img src=x onerror=attack()>';const out=await render(d,{},old);assert.match(out.html,/promote path open/);assert.match(out.html,/25 \/ 11/);assert.match(out.html,/<img src=x/);});
