const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),test=require('node:test');
const html=fs.readFileSync(path.join(__dirname,'../ai.html'),'utf8');
const start=html.indexOf('  function renderPerf('),end=html.indexOf('  function renderVerdict(',start);assert.ok(start>0&&end>start);
const source=html.slice(start,end);
function render(perf){const nodes={};const env={$:id=>nodes[id]||(nodes[id]={innerHTML:''}),fmt:(v,n)=>Number(v).toFixed(n),esc:v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),ago:()=>'<invented time>',stTag:()=>'<invented state>'};vm.runInNewContext(source+';renderPerf(input,null)',{...env,input:perf});return nodes;}
const base=()=>({n_calls:1,qualification:{contract:'market-read-reported-outcomes.v1'},by_window:{'21':{n:1,hits:0,hit_rate:0}},rows:[{ticker:'QAONLY',direction:'UP',windows:{'21':{return_pct:0,correct:false,reported_grade_valid:true}},withheld_windows:{},status:'partial',thesis:'invented'}]});
test('actual outcome renderer withholds legacy unvalidated totals',()=>{let p=base();delete p.qualification;const n=render(p);assert.match(n['perf-summary'].innerHTML,/validation unavailable/);assert.doesNotMatch(n['perf-summary'].innerHTML,/%/);});
test('actual outcome renderer keeps reported zero and calls it calendar-day evidence',()=>{const n=render(base());assert.match(n['perf-summary'].innerHTML,/0%/);assert.match(n['perf-summary'].innerHTML,/21 calendar-day reported accuracy/);assert.match(n['perf-summary'].innerHTML,/latest-80 scope/);assert.match(n['perf-table'].innerHTML,/0\.00%/);});
test('malformed totals cannot render as accuracy',()=>{for(const bad of [{n:true,hits:1,hit_rate:1},{n:0,hits:0,hit_rate:0},{n:1,hits:2,hit_rate:1},{n:2,hits:1,hit_rate:1},{n:1,hits:1,hit_rate:NaN}]){let p=base();p.by_window['21']=bad;assert.doesNotMatch(render(p)['perf-summary'].innerHTML,/%/);}});
test('withheld reason is escaped and cannot create markup',()=>{let p=base();p.rows[0].windows={};p.rows[0].withheld_windows={'21':{withheld_reasons:['<img src=x onerror=attack()>','"bad"']}};const table=render(p)['perf-table'].innerHTML;assert.match(table,/withheld/);assert.match(table,/&lt;img/);assert.doesNotMatch(table,/<img/);});
test('invalid reported cell cannot become a win',()=>{for(const bad of [{return_pct:true,correct:true,reported_grade_valid:true},{return_pct:1,correct:'false',reported_grade_valid:true},{return_pct:1,correct:true},{return_pct:Infinity,correct:true,reported_grade_valid:true}]){let p=base();p.rows[0].windows['21']=bad;const table=render(p)['perf-table'].innerHTML;assert.match(table,/withheld/);assert.doesNotMatch(table,/mono ok/);}});
test('unknown direction is preserved instead of defaulting to DOWN',()=>{let p=base();p.rows[0].direction='UNKNOWN';const table=render(p)['perf-table'].innerHTML;assert.match(table,/UNKNOWN/);assert.doesNotMatch(table,/>DOWN</);});
test('release gate never treats a nonempty call list as an out-of-sample test',()=>{assert.match(html,/reported ledger outcomes do not establish point-in-time, cost-adjusted out-of-sample performance/);assert.doesNotMatch(html,/no matured out-of-sample call history/);assert.doesNotMatch(html,/5 \/ 21 \/ 63 trading days/);});
test('small positive baseline stays visible and booleans cannot become a price of one',()=>{let p=base();p.rows[0].baseline_price=0.0000001;assert.match(render(p)['perf-table'].innerHTML,/>0\.0000001<\/td>/);for(const value of [true,false,0,'100',NaN,Infinity]){p.rows[0].baseline_price=value;assert.match(render(p)['perf-table'].innerHTML,/<td class="mono">—<\/td>/);}});
