const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const api=require('../jh-alpha-research.js'),stamp='2026-09-19T09:30:00Z',now=Date.parse(stamp);
function packet(){return {contract:api.CONTRACT,generated_at:stamp,method:'fixture',call:null,calls_eligible:false,sizing_eligible:false,execution_eligible:false,
 research_ideas:[{subject:'Crypto',direction:'RISK-ON / LONG',reported_conviction:0,source_status:'current_packet',source_generated_at:stamp,decision_id:'alpha-fixture',source:'data/conviction.json',engines:[],stats:{distributions:[],scorecards:[]},qualification_gaps:['source_model_not_validated']}],source_feeds:{},regime:{sources:[]},pd_settlement_fails:{}};}
test('unsupported sizes and a reported zero remain distinct',()=>{const html=api.render(packet(),now).ideas;assert.match(html,/conviction: 0 /);assert.match(html,/Allocation \/ stop \/ target: unavailable/);assert.match(html,/No prior payoff is invented/);assert.match(html,/not a probability/);assert.equal(api.num(null),'Unavailable');assert.equal(api.num(false),'Unavailable');});
test('current source or snapshot expiry withholds displayed directional score',()=>{const p=packet();p.research_ideas[0].source_generated_at='2026-09-17T09:30:00Z';assert.ok(!api.render(p,now).ideas.includes('conviction: 0 '));assert.match(api.render(p,now,true).ideas,/conviction: 0 /);assert.match(api.render(packet(),now+5*3600000).hero,/snapshot stale/);});
test('HTML injection and arbitrary evidence schemes cannot reach markup',()=>{const p=packet();p.research_ideas[0].subject='<img onerror=x>';p.research_ideas[0].source='javascript:x';const html=api.render(p,now).ideas;assert.ok(!html.includes('<img'));assert.ok(!html.includes('href="javascript:'));assert.equal(api.path('data/../secret'),null);p.sizing_eligible=true;assert.throws(()=>api.render(p),/boundary/);});
test('explicit scenarios calculate direct long and short cash consequences after entered costs',()=>{let r=api.scenario('10000','-5','10','long');assert.equal(r.gross_usd,'-500.00');assert.equal(r.entered_cost_usd,'10.00');assert.equal(r.after_entered_cost_usd,'-510.00');r=api.scenario('10000','-5','10','short');assert.equal(r.after_entered_cost_usd,'490.00');assert.match(r.scope,/short losses are not bounded/);assert.match(r.scope,/Not an expected return/);});
test('scenario decimals, zero shock and signed rounding do not rely on floating point',()=>{assert.equal(api.scenario('1','0.5','0','long').gross_usd,'0.01');assert.equal(api.scenario('1','-0.5','0','long').gross_usd,'-0.01');assert.equal(api.scenario('100','0','0','long').after_entered_cost_usd,'0.00');assert.equal(api.scenario('123.45','1.2345','12.3456','long').after_entered_cost_usd,'1.37');});
test('invalid assumptions never become defaults or a hidden trade',()=>{for(const args of [['','0','0','long'],['1','-101','0','long'],['1','2','-1','long'],['0','0','0','long'],['100','NaN','0','long'],['100','5','0','inverse'],['100','5','0',''],['1e9','0','0','long']])assert.throws(()=>api.scenario(...args));});
test('brief formatting escapes HTML and supports only harmless text structure',()=>{const html=api.briefMarkup('# Research\n**WAIT**\n<script>bad()</script>\n[x](javascript:alert(1))\n`decision-id`');assert.match(html,/<h3>Research/);assert.match(html,/<strong>WAIT/);assert.ok(!html.includes('<script>'));assert.ok(!html.includes('<a '));assert.match(html,/<code>decision-id/);});
test('retained snapshot loader checks kind, hash, contract and output bytes',async()=>{const body=new TextEncoder().encode(JSON.stringify(packet())),sha=await api.sha(body),manifest={contract:'alpha-replay.v1',kind:'compass',generated_at:stamp,output_sha256:sha,output:{key:api.PREFIX+'outputs/'+sha+'.json',sha256:sha,bytes:body.length}};const raw=new TextEncoder().encode(JSON.stringify(manifest)),id=await api.sha(raw),files={['/'+api.PREFIX+'runs/'+id+'.json']:raw,['/'+manifest.output.key]:body};const fetcher=async key=>new Response(files[key],{status:files[key]?200:404});assert.equal((await api.loadSnapshot(id,fetcher)).contract,api.CONTRACT);await assert.rejects(api.loadSnapshot(id,fetcher,'brief'),/identity/);files['/'+manifest.output.key]=new TextEncoder().encode('{}');await assert.rejects(api.loadSnapshot(id,fetcher),/output differs/);await assert.rejects(api.loadSnapshot('../current',fetcher),/Invalid/);await assert.rejects(api.loadSnapshot('a'.repeat(64),async()=>new Response(new Uint8Array(256*1024+1))),/size bound/);});
test('page uses immutable research and explicit assumptions without page AI or unrelated mutable fails strip',()=>{const html=fs.readFileSync(require.resolve('../alpha-compass.html'),'utf8');assert.match(html,/jh-alpha-research.js/);assert.ok(!html.includes('jh-page-ai'));assert.ok(!html.includes('jh-pd-context'));assert.match(html,/id="notional"[^>]*required/);assert.ok(!html.includes('value="10000"'));const js=fs.readFileSync(require.resolve('../jh-alpha-page.js'),'utf8');assert.match(js,/setInterval\(refresh,60000\)/);assert.match(js,/source_replay\?\.manifest_key!==packet.replay.manifest_key/);assert.match(js,/Current pointer differs/);});
