const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib'),crypto=require('node:crypto');
const v=require('../jh-asia-calendar.js'),raw=zlib.gunzipSync(fs.readFileSync(path.join(__dirname,'fixtures/asia-calendar-browser.json.gz'))),native=()=>JSON.parse(raw),now=Date.parse('2026-09-28T11:00:00Z'),sid='XTEXVA01KRM667N';
class Element{constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.textContent='';this.value='';}appendChild(n){this.children.push(n);return n;}replaceChildren(){this.children=[];this.textContent='';}text(){return this.textContent+this.children.map(n=>n.text()).join(' ');}set innerHTML(_){throw Error('Untrusted HTML forbidden');}}
function document(){const html=fs.readFileSync(path.join(__dirname,'../macro-leads.html'),'utf8'),nodes=new Map([...html.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],new Element('div')]));return{createElement:tag=>new Element(tag),getElementById:id=>nodes.get(id)||null};}
function recalculate(s){const values=new Map(s.observations.map((r,i)=>{r.position=i;return[r.month,r.value];}));s.returned_rows=s.observations.length;s.level=values.get(s.latest_month);s.status=s.level===null?'latest_missing':'measured';for(const key of ['mom','three_month','yoy'])Object.assign(s[key],v.comparison(s.level,values.get(s[key].previous_month)??null));}

test('native fixture carries both complete 500-month populations with different units',()=>{
 const p=native(),before=JSON.stringify(p),out=v.view(p,now);assert.equal(p._synthetic_fixture,true);assert.ok(raw.length>190000);assert.equal(out.native,true);assert.equal(out.authority,false);assert.equal(out.positions,1000);assert.equal(out.rows.length,2);assert.equal(out.rows[0].unit,'US dollars, exchange rate converted');assert.equal(out.rows[1].unit,'Millions of Dollars');assert.equal(out.rows[0].s.yoy.previous_month,'2025-08');assert.equal(JSON.stringify(p),before);
});
test('every comparison, original numeric row, clock, definition and permission is independently checked',()=>{
 const changes=[p=>p.measurement_review.series[sid].mom.percent++,p=>p.measurement_review.series[sid].three_month.previous_month='2026-06',p=>p.measurement_review.series[sid].yoy.percent++,p=>p.measurement_review.series[sid].observations[0].value++,p=>p.measurement_review.series[sid].observations[1].month='1985-01',p=>p.measurement_review.series[sid].observations[0].original.date='1985-01-02',p=>p.measurement_review.series[sid].observations[0].original.value='1_000',p=>p.measurement_review.series[sid].observations[0].original.value=true,p=>p.measurement_review.series[sid].observations[0].original.value='1e-999',p=>p.measurement_review.series[sid].observations[0].original.value='Infinity',p=>p.measurement_review.series[sid].metadata.units='Millions of Dollars',p=>p.measurement_review.series[sid].metadata.seasonal_adjustment_short='SA',p=>p.measurement_review.series[sid].annualized_three_month_percent=20,p=>p.measurement_review.series[sid].observation_age_days++,p=>p.calls_eligible=true,p=>p.measurement_review.series[sid].sizing_eligible=true,p=>p.publication_context.multiple_head_atomic=true,p=>p.publication_context.manifest.bytes=0,p=>p.publication_context.manifest.key='data/account.json',p=>delete p.compiler_sha256['managed_secret.py'],p=>delete p.measurement_review.series.VALEXPTWM052N,p=>p.generated_at='2026-09-29T00:00:00Z',p=>p.generated_at='2026-02-30T00:00:00Z'];
 for(const change of changes){const p=native();change(p);assert.throws(()=>v.view(p,now));}
});
test('calendar holes never substitute an adjacent observation and missing latest never borrows a prior value',()=>{
 let p=native(),s=p.measurement_review.series[sid];s.observations=s.observations.filter(r=>r.month!=='2025-08');recalculate(s);let out=v.view(p,now);assert.equal(out.positions,999);assert.equal(out.rows[0].s.yoy.status,'prior_month_missing');assert.equal(out.rows[0].s.yoy.percent,null);
 p=native();s=p.measurement_review.series[sid];Object.assign(s.observations.at(-1),{value:null,status:'missing'});s.observations.at(-1).original.value='.';recalculate(s);out=v.view(p,now);assert.equal(out.rows[0].s.level,null);assert.equal(out.rows[0].s.yoy.status,'latest_missing');
});
test('zero levels are retained, zero denominators and overflow are explicit unavailable states',()=>{
 let p=native(),s=p.measurement_review.series[sid],r=s.observations.find(r=>r.month==='2025-08');r.value=0;r.original.value='0';recalculate(s);assert.equal(v.view(p,now).rows[0].s.yoy.status,'zero_denominator');
 p=native();s=p.measurement_review.series[sid];r=s.observations.at(-1);r.value=0;r.original.value='0';recalculate(s);assert.equal(v.view(p,now).rows[0].s.yoy.percent,-100);
 assert.deepEqual(v.comparison(1e15,1e-300),{status:'outside_numeric_range',percent:null});assert.equal(v.number('-0'),-0);assert.equal(v.number('1.20e2'),120);
});
test('unavailable sources remain separate, retain every ambiguous row, and grant no measurements',()=>{
 const p=native(),s=p.measurement_review.series[sid];s.status='ambiguous_or_invalid_observations';s.observations[0].original.value='<img src=x onerror=alert(1)>';s.observations[0].status='invalid_observation';const out=v.view(p,now);assert.equal(out.rows[0].usable,false);assert.equal(out.rows[1].usable,true);assert.equal(out.positions,1000);
 const doc=document();v.render(doc,p,now);for(let i=0;i<4;i++)doc.getElementById('asia-prev').onclick();assert.match(doc.getElementById('asia-months').text(),/<img src=x onerror=alert\(1\)>/);assert.match(doc.getElementById('asia-months').text(),/Unqualified/);assert.match(doc.getElementById('asia-definition').text(),/ambiguous/);
});
test('complete pagination and whole-packet disclosure preserve source values without HTML execution',()=>{
 const p=native(),doc=document();v.render(doc,p,now);assert.equal(doc.getElementById('asia-choice').children.length,2);assert.match(doc.getElementById('asia-row-count').textContent,/401–500 of 500/);assert.equal(doc.getElementById('asia-next').disabled,true);
 for(let i=0;i<4;i++)doc.getElementById('asia-prev').onclick();assert.match(doc.getElementById('asia-row-count').textContent,/1–100 of 500/);assert.equal(doc.getElementById('asia-prev').disabled,true);doc.getElementById('asia-next').onclick();assert.match(doc.getElementById('asia-row-count').textContent,/101–200/);
 const select=doc.getElementById('asia-choice');select.value='VALEXPTWM052N';select.onchange();assert.match(doc.getElementById('asia-definition').textContent,/Millions of Dollars/);assert.match(doc.getElementById('asia-row-count').textContent,/401–500/);const details=doc.getElementById('asia-details');details.open=true;details.ontoggle();assert.deepEqual(JSON.parse(doc.getElementById('asia-original').textContent),p);
});
test('failed, legacy and invalid refreshes clear previous measurements and obsolete callbacks',()=>{
 const doc=document();v.render(doc,native(),now);const next=doc.getElementById('asia-next').onclick,select=doc.getElementById('asia-choice').onchange,toggle=doc.getElementById('asia-details').ontoggle;
 v.clear(doc,'Failed source');doc.getElementById('asia-details').open=true;next();select();toggle();assert.equal(doc.getElementById('asia-months').children.length,0);assert.equal(doc.getElementById('asia-original').textContent,'Unavailable');assert.equal(doc.getElementById('asia-choice').onchange,null);
 v.render(doc,{generated_at:'2026-09-27T10:20:00Z',korea_exports:{yoy_pct:999}},now);assert.match(doc.getElementById('asia-calendar-status').textContent,/Legacy publication/);assert.equal(doc.getElementById('asia-choice').children.length,0);
 v.render(doc,native(),now);const p=native();p.calls_eligible=true;assert.throws(()=>v.render(doc,p,now));assert.equal(doc.getElementById('asia-series').children.length,0);assert.equal(doc.getElementById('asia-original').textContent,'Unavailable');
});
test('the existing page keeps one Asia read, whole predecessor, and all other source contexts',()=>{
 const before=fs.readFileSync(path.join(__dirname,'fixtures/pre-asia-calendar-macro-leads.html.txt'));assert.equal(before.length,18964);assert.equal(crypto.createHash('sha256').update(before).digest('hex'),'3b3ec237bb3019e26e7ac7c912c59cb21490daba3642d942d51ab96beba81172');
 const page=fs.readFileSync(path.join(__dirname,'../macro-leads.html'),'utf8');assert.equal((page.match(/load\('asia'\)/g)||[]).length,1);assert.match(page,/JHAsiaCalendar.render\(document,asiaRaw\)/);assert.match(page,/Legacy text extractions below are unqualified/);assert.match(page,/id="asia-calendar"/);for(const key of ['china','geo','calendar','macro'])assert.ok(page.includes("load('"+key+"')"));assert.ok(page.indexOf('jh-business-cycle-review.js')<page.indexOf('jh-asia-calendar.js'));assert.ok(!page.includes('a.taiwan_orders.latest_usd_bn||'));
});
