const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict');
const file=path.join(__dirname,'../intelligence/index.html'),html=fs.readFileSync(file,'utf8');
const a=html.indexOf('function renderBondTrace(d) {'),b=html.indexOf('// ─── TIC FLOWS',a),source=html.slice(a,b);
function render(packet,old={}){const nodes=Object.fromEntries(['bondtrace-kpis','bondtrace-etfs','bondtrace-interp'].map(id=>[id,{innerHTML:old[id]||''}]));const context=vm.createContext({document:{getElementById:id=>nodes[id]}});vm.runInContext(source,context);context.renderBondTrace(packet);return Object.fromEntries(Object.entries(nodes).map(([id,node])=>[id,node.innerHTML]));}
function packet(){return {regime:'CALM',hyg:{price:100,perf_5d_pct:-1,perf_30d_pct:0},lqd:{price:200,perf_5d_pct:1,perf_30d_pct:0},hyg_lqd_ratio:{value:.5,change_5d_pct:-2},trace:{observation_dates:{treasury:'2026-09-29',corporate:'2026-09-30'}},generated_at:'2026-10-01T21:00:00Z'};}
test('object ratio uses its actual value and change rather than stringifying a packet',()=>{const out=render(packet());assert.match(out['bondtrace-kpis'],/>0\.500</);assert.match(out['bondtrace-kpis'],/-2\.00%/);assert.doesNotMatch(JSON.stringify(out),/\[object Object\]/);});
test('absolute price ratio never declares an investment posture',()=>{for(const value of [.5,1,2]){const p=packet();p.hyg_lqd_ratio.value=value;const out=render(p);assert.doesNotMatch(out['bondtrace-kpis'],/risk-on|risk-off/);assert.match(out['bondtrace-interp'],/does not establish relative performance/);}});
test('missing and typed numeric fields stay unavailable without positive color',()=>{for(const value of [null,undefined,true,'0',NaN,Infinity]){const p=packet();p.hyg={price:value,perf_5d_pct:value,perf_30d_pct:value,perf_90d_pct:value};const out=render(p);assert.match(out['bondtrace-etfs'],/class="t-mute">Unavailable/);assert.doesNotMatch(out['bondtrace-etfs'],/NaN|Infinity/);}});
test('real zero returns retain zero and neutral styling',()=>{const p=packet();p.hyg.perf_5d_pct=0;assert.match(render(p)['bondtrace-etfs'],/class="t-mute">0\.00%/);});
test('per-source observation dates remain distinct from generation',()=>{const text=render(packet())['bondtrace-interp'];for(const date of ['2026-09-29','2026-09-30','2026-10-01T21:00:00.000Z'])assert.ok(text.includes(date));assert.match(text,/Generation time is not an observation date/);});
test('invalid and markup dates and regime cannot inject elements',()=>{const p=packet();p.regime='<img src=x onerror=alert(1)>';p.trace.observation_dates.treasury='2026-09-31';p.trace.observation_dates.corporate='<svg/onload=alert(1)>';p.generated_at='<b>now</b>';const out=render(p);assert.doesNotMatch(JSON.stringify(out),/<img|<svg|<b>now/);assert.match(out['bondtrace-kpis'],/&lt;img/);assert.match(out['bondtrace-interp'],/Treasury observation: Unavailable · Corporate breadth observation: Unavailable/);});
test('absent packet clears prior successful bond display',()=>{const first=render(packet());const empty=render(null,first);assert.doesNotMatch(empty['bondtrace-kpis'],/>0\.500</);assert.match(empty['bondtrace-kpis'],/Unavailable/);assert.match(empty['bondtrace-interp'],/Research status: unqualified/);});
test('legacy eighty-nine-observation horizon is disclosed rather than renamed ninety days',()=>{const out=render(packet());assert.match(out['bondtrace-etfs'],/89 observations earlier/);assert.match(out['bondtrace-etfs'],/not total returns/);});
test('boot renders explicit unavailable state and does not keep a loading stub forever',()=>{assert.ok(html.includes('  renderBondTrace(bt);'));assert.ok(!html.includes('if (bt) renderBondTrace(bt);'));});
