const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const R=path.resolve(__dirname,'..'),ac={exports:{}};Function('exports','module',process.binding('natives')['internal/deps/acorn/acorn/dist/acorn'])(ac.exports,ac);
function functions(raw){const nodes=ac.exports.parse(raw,{ecmaVersion:'latest'}).body.find(n=>n.expression?.callee?.type==='FunctionExpression').expression.callee.body.body;return Object.fromEntries(nodes.filter(n=>n.type==='FunctionDeclaration').map(n=>[n.id.name,raw.slice(n.start,n.end)]));}
const current=functions(fs.readFileSync(path.join(R,'jh-chart-engine.js'),'utf8')),prior=functions(fs.readFileSync(path.join(R,'tests/fixtures/chart-oecd-additional/jh-chart-engine.js.before.txt'),'utf8'));
const plain=v=>JSON.parse(JSON.stringify(v));
function packet(id='NASDAQ:ABC'){return {id,freq:'D',provider:'invented',source:'invented complete test packet',ohlc:Array.from({length:20},(_,i)=>['2026-01-'+String(i+1).padStart(2,'0'),10+i,12+i,9+i,11+i,i===0?null:i===1?0:100]),market_history_quality:{provider_identity_verified:false},bar_sources:Array.from({length:20},(_,i)=>({ordinal:i,scope:'invented fixture'}))};}
function boot(received,old=false){const selected=old?prior:current,c={window:{},PROXY:'https://fixture.invalid',LIVE:'https://fixture.invalid',active:'NASDAQ:ABC',tf:'1d',lastSource:'previous',barEvidence:new WeakMap(),observationAxes:new WeakMap(),barCache:{},calls:[],spec:id=>[id],resolveSym:s=>({ticker:s.split(':').pop(),yahoo:s.split(':').pop(),raw:s}),observationId:()=>false,document:{getElementById:()=>null}};
 c.fetchJson=async url=>{c.calls.push(url);assert.match(url,/\/series\?id=/,'No fallback request is authorized');if(received instanceof Error)throw received;return typeof received==='function'?await received():received;};
 vm.createContext(c);const names=['klines','identifyBars','reportedVolume','volumeTotal','volumeFields','resampleToTf','barsFitTf','medianGap','expectedGap','uniq','toBars','looksCloseOnly','fillCandleBodies','sanitizeBars','utcMidnight'];vm.runInContext(names.filter(n=>selected[n]).map(n=>selected[n]).join('\n'),c);return c;}

test('predecessor accepts the wrong complete instrument; repaired route refuses it without a bare-symbol fallback',async()=>{const raw=packet('NYSE:OTHER'),old=boot(raw,true),now=boot(raw);assert.equal((await old.klines('NASDAQ:ABC','1d')).length,20);assert.equal((await now.klines('NASDAQ:ABC','1d')).length,0);assert.equal(now.calls.length,1);});
test('predecessor expands flat OHLC; repaired route preserves every reported value and unknown volume',async()=>{const raw=packet();raw.ohlc.forEach(r=>r.splice(1,4,r[4],r[4],r[4],r[4]));const before=structuredClone(raw),old=boot(raw,true),now=boot(raw);const oldBars=await old.klines(raw.id,'1d'),bars=await now.klines(raw.id,'1d');assert.ok(oldBars.some(b=>b.open!==b.close||b.high!==b.close||b.low!==b.close));assert.deepEqual(Array.from(bars,b=>[new Date(b.time*1000).toISOString().slice(0,10),b.open,b.high,b.low,b.close,b.volume]),raw.ohlc);assert.deepEqual(raw,before);});
test('complete parsed packet and source ordinals stay attached, without granting source or decision authority',async()=>{const raw=packet();raw.ohlc.reverse();const before=structuredClone(raw),c=boot(raw),bars=await c.klines(raw.id,'1d'),e=c.barEvidence.get(bars).market_history;assert.equal(e.whole_packet,raw);assert.deepEqual(raw,before);assert.equal(e.requested_id,raw.id);assert.equal(e.reported_id,raw.id);assert.deepEqual(Array.from(e.source_row_ordinals),Array.from({length:20},(_,i)=>i));assert.equal(bars[0].close,11);for(const key of ['provider_identity_verified','full_history_verified','raw_upstream_replay_verified','point_in_time_verified','calls_eligible','sizing_eligible'])assert.equal(e[key],false,key);assert.match(c.lastSource,/unverified/);});
test('scalar observations, returned alternatives, missing identity and unreported cadence cannot become OHLC',async()=>{const variants=[r=>{delete r.id;},r=>{r.id='NYSE:ABC';},r=>{delete r.freq;},r=>{r.freq='M';},r=>{r.via='alternative';},r=>{r.routing_evidence={};},r=>{r.obs=r.ohlc.map(x=>[x[0],x[4]]);delete r.ohlc;},r=>{r.bars=r.ohlc;delete r.ohlc;}];for(const change of variants){const raw=packet();change(raw);const c=boot(raw);assert.equal((await c.klines('NASDAQ:ABC','1d')).length,0);assert.equal(c.calls.length,1);assert.equal(c.lastSource,'previous');}});
test('invalid OHLC numbers and calendar dates are rejected rather than repaired or silently dropped',async()=>{const mutations=[r=>r[0]='2026-02-30',r=>r[0]='2026-1-01',r=>r[1]='10',r=>r[1]=null,r=>r[2]=false,r=>r[3]=NaN,r=>r[4]=Infinity,r=>r[2]=1,r=>r[3]=100,r=>r.push(1)];for(const mutate of mutations){const raw=packet();mutate(raw.ohlc[0]);const c=boot(raw);assert.equal((await c.klines(raw.id,'1d')).length,0);assert.equal(c.calls.length,1);}const raw=packet();raw.ohlc[1][0]=raw.ohlc[0][0];assert.equal((await boot(raw).klines(raw.id,'1d')).length,0);});
test('reported zeros survive, five-column rows retain absent volume and bad volume does not invalidate prices',async()=>{for(const volume of [undefined,null,'0',false,-1,Infinity]){const raw=packet();raw.ohlc[0]=['2026-01-01',0,0,0,0];if(volume!==undefined)raw.ohlc[0].push(volume);const c=boot(raw),bars=await c.klines(raw.id,'1d');assert.equal(bars.length,20);assert.equal(bars[0].close,0);assert.equal(bars[0].volume,null);assert.equal(bars[1].volume,0);}});
test('daily source observations cannot masquerade as intraday data and refused HTTP is not retried',async()=>{for(const interval of ['1m','15m','1h','4h']){const c=boot(packet());assert.equal((await c.klines('NASDAQ:ABC',interval)).length,0);assert.equal(c.calls.length,0);}const c=boot(new Error('HTTP 403'));assert.equal((await c.klines('NASDAQ:ABC','1d')).length,0);assert.equal(c.calls.length,1);});
test('weekly display aggregation retains original rows, first open, high, low and last close',async()=>{const raw=packet(),c=boot(raw),bars=await c.klines(raw.id,'1w');assert.ok(bars.length>=2&&bars.length<raw.ohlc.length);const first=bars[0];assert.equal(first.open,10);assert.equal(first.high,15);assert.equal(first.low,9);assert.equal(first.close,14);assert.equal(first.volume,null);assert.equal(c.barEvidence.get(bars).market_history.whole_packet,raw);});
test('a cached bare ticker cannot override another venue; superseded completions cannot replace its source label',async()=>{const raw=packet(),c=boot(raw);c.barCache['ABC|1d']={at:Date.now(),src:'wrong venue',d:Array(20).fill({time:1,close:999})};c.active='NYSE:XYZ';const bars=await c.klines(raw.id,'1d');assert.equal(c.calls.length,1);assert.equal(bars[0].close,11);assert.equal(c.lastSource,'previous');assert.equal(c.barEvidence.get(bars).symbol,raw.id);});
test('changing an exchange-qualified selection clears the previous instrument before the request completes',async()=>{const c=boot(packet()),priorBars=[{close:999}],clears=[];let resolve;c.lastBars=priorBars;c.barEvidence.set(priorBars,{symbol:'NYSE:OLD',bars:priorBars});Object.assign(c,{loadGen:0,lastGoodTf:'1d',preserveView:true,layout:1,clearObservationFrame:msg=>{clears.push(msg);c.lastBars=[];},syncLivePill:()=>{},toast:()=>{},renderTf:()=>{},klines:()=>new Promise(r=>{resolve=r;})});vm.runInContext(current.load,c);const pending=c.load();assert.equal(clears.length,1);assert.equal(c.lastBars.length,0);resolve([]);await pending;assert.equal(c.lastBars.length,0);assert.equal(c.lastSource,'unavailable');});
