// Complete unchanged canonical paint executes with synthetic rendering/I/O stubs.
// The native Chromium companion exercises the actual library and selected graph.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const ROOT=path.join(__dirname,'..'),parser={exports:{}};Function('exports','module',process.binding('natives')['internal/deps/acorn/acorn/dist/acorn'])(parser.exports,parser);
const source=fs.readFileSync(path.join(ROOT,'jh-chart-engine.js'),'utf8'),body=parser.exports.parse(source,{ecmaVersion:'latest'}).body.find(n=>n.expression?.callee?.type==='FunctionExpression').expression.callee.body.body;
const fn=Object.fromEntries(body.filter(n=>n.type==='FunctionDeclaration').map(n=>[n.id.name,source.slice(n.start,n.end)]));
function setup(){
 const d=Array.from({length:80},(_,i)=>({time:1767225600+i*300,open:100,high:103,low:98,close:101+i/100,volume:i===1?null:i===2?0:100+i})),before=JSON.stringify(d),wait=[],calls={paint:0,prepare:0,complete:0,quote:0};
 const chart={timeScale:()=>({getVisibleLogicalRange:()=>null,fitContent(){},setVisibleLogicalRange(){}}),applyOptions(){},priceScale:()=>({applyOptions(){}}),addHistogramSeries:()=>({setData(){}})};
 const c={window:{lastBars:d,jhActive:'BTC-USD',tf:'5m',INDS:[],OSC:[]},active:'BTC-USD',tf:'5m',paintSeq:0,loadGen:1,barEvidence:new WeakMap(),observationId:()=>false,mode:'dod',lastBars:d,series:[],INDS:[],OSC:[],compare:[],tape:{prints:[]},COLORS:[],UP:'up',DN:'down',lastSource:'invented:unit-unknown',volOn:false,watermark:false,chart,preserveView:false,lastSpxDaily:[],BARS:{dod:1},isFinite,localStorage:{getItem:()=>null},document:{getElementById:()=>null},wipe(){c.series=[];},pal:()=>({}),chartLook:()=>({}),rightScaleMode:()=>0,requestAnimationFrame(){},loadBench:()=>new Promise(resolve=>wait.push(resolve)),fmtVol:String};
 for(const n of['paintOsc','drawSVG','paintPat','renderDetail','checkAlerts','countdown','renderLegend','syncLivePill','renderTech','renderOver','renderSeason','renderFin','paintMini','writeState','clearObservationFrame','paintObservations'])c[n]=()=>{};
 c.quoteUI=()=>calls.quote++;vm.createContext(c);vm.runInContext(['reportedVolume','computeChange','paint','sliceIdentifiedBars','repaintOwnedBars'].map(n=>fn[n]).join('\n'),c);
 const actual=c.paint;c.paint=(...a)=>{calls.paint++;return actual(...a);};
 const evidence={symbol:c.active,interval:c.tf,source:'invented:unit-unknown',bars:d,published_at:'invented original'};c.barEvidence.set(d,evidence);
 return {c,d,before,calls,evidence,prepare:()=>calls.prepare++,complete:()=>calls.complete++,flush:()=>wait.splice(0).forEach(resolve=>resolve([]))};
}
for(const [name,change]of[['unknown array',s=>s.c.barEvidence.delete(s.d)],['private timeframe changed',s=>s.c.tf='30m'],['private symbol changed',s=>s.c.active='AAPL'],['different private array',s=>s.c.lastBars=s.d.slice()],['wrong source interval',s=>s.evidence.interval='1d']])test(name+' prevents every timer repaint side effect despite stale public globals',()=>{
 const s=setup();change(s);assert.equal(s.c.repaintOwnedBars(s.d,s.prepare,s.complete),null);assert.deepEqual(s.calls,{paint:0,prepare:0,complete:0,quote:0});assert.equal(JSON.stringify(s.d),s.before);
});
test('matching frame executes complete canonical paint and captured completion without quantity mutation',async()=>{const s=setup();let captured;const p=s.c.repaintOwnedBars(s.d,s.prepare,(...args)=>{s.complete();captured=args;});assert.equal(s.calls.paint,1);s.flush();await p;assert.equal(s.calls.complete,1);assert.equal(s.calls.quote,1);assert.equal(captured[0],s.c.chart);assert.equal(captured[1],s.d);assert.deepEqual(captured.slice(2),['BTC-USD','5m']);assert.equal(JSON.stringify(s.d),s.before);});
for(const [name,change]of[['timeframe',s=>s.c.tf='30m'],['symbol',s=>s.c.active='AAPL'],['generation',s=>s.c.loadGen++],['chart',s=>s.c.chart={}],['array',s=>s.c.lastBars=s.d.slice()],['evidence',s=>s.c.barEvidence.set(s.d,{...s.evidence})]])test(name+' interruption suppresses completion after actual async paint',async()=>{const s=setup(),p=s.c.repaintOwnedBars(s.d,s.prepare,s.complete);change(s);s.flush();await p;assert.equal(s.calls.complete,0);assert.equal(JSON.stringify(s.d),s.before);});
test('prepare cannot change selection and then paint a stale frame',()=>{const s=setup();assert.equal(s.c.repaintOwnedBars(s.d,()=>{s.prepare();s.c.tf='30m';},s.complete),null);assert.equal(s.calls.paint,0);});
test('same-array later actual paint suppresses old framing completion',async()=>{const s=setup(),p=s.c.repaintOwnedBars(s.d,s.prepare,s.complete),newer=s.c.paint(s.d);s.flush();await Promise.all([p,newer]);assert.equal(s.calls.complete,0);assert.equal(s.calls.quote,1);});
test('synchronous reentrant actual paint cannot donate its sequence to stale work',async()=>{const s=setup();let once=false,newer;s.c.wipe=()=>{if(!once){once=true;newer=s.c.paint(s.d);}};await s.c.repaintOwnedBars(s.d,s.prepare,s.complete);assert.equal(s.calls.paint,2);assert.equal(s.calls.complete,0);assert.equal(s.calls.quote,0);s.flush();await newer;assert.equal(s.calls.quote,1);});
test('replay slices copy existing identity and share original null/zero rows; unknown parents stay unknown',()=>{const s=setup(),full=s.c.sliceIdentifiedBars(s.d),prefix=s.c.sliceIdentifiedBars(full,40);assert.equal(prefix[1],s.d[1]);assert.equal(prefix[1].volume,null);assert.equal(prefix[2].volume,0);for(const d of[full,prefix]){const e=s.c.barEvidence.get(d);assert.equal(e.bars,d);assert.equal(e.symbol,s.evidence.symbol);assert.equal(e.interval,s.evidence.interval);assert.equal(e.source,s.evidence.source);assert.equal(e.published_at,s.evidence.published_at);}assert.equal(s.c.barEvidence.get(s.c.sliceIdentifiedBars(s.d.slice(),5)),undefined);assert.equal(JSON.stringify(s.d),s.before);});
test('a rejected paint is handled and cannot run completion',async()=>{const s=setup();s.c.paint=()=>Promise.reject(Error('invented paint rejection'));await s.c.repaintOwnedBars(s.d,s.prepare,s.complete);assert.equal(s.calls.complete,0);});
