const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const R=path.resolve(__dirname,'..'),read=p=>require('./helpers/chart-provider-browser-preservation.cjs').normalize(fs.readFileSync(path.join(R,p),'utf8'),p),transition=JSON.parse(read('tests/fixtures/chart-provider-access/transition.json'));
function helpers(source=read('jh-watchlist-quotes.js')){const context={window:{},AbortController,setTimeout,clearTimeout};vm.runInNewContext(source,context);context.window.jhWatchlistResolve=s=>({engine:'equity',ticker:s,yahoo:s});return context.window.JHWatchlistQuotes;}
test('bundled resolver is exactly the complete reviewed repository contract',()=>{const api=helpers(),expected=JSON.parse(read('data/tv-symbol-resolver.json'));assert.deepEqual(JSON.parse(JSON.stringify(api.rules())),expected);const r=api.rules();r.exact.SPX.id='INVENTED';assert.equal(api.rules().exact.SPX.id,expected.exact.SPX.id);});
test('whole predecessor reproduces quote lockout when the runtime resolver is denied',()=>{const api=helpers(read(transition.changes['jh-watchlist-quotes.js'].before_path));assert.match(api.resolve('QASYNTH',null).reason,/resolver unavailable/);const current=helpers();assert.equal(current.resolve('QASYNTH',current.rules()).ticker,'QASYNTH');for(const id of ['QAONLY','NASDAQ:QAONLY','FX:EURUSD','FRED:DGS10','ECONOMICS:USLEI','TVC:GOLD'])assert.ok(current.resolve(id,current.rules()).reason,id);});
test('actual renderer initialization uses local reviewed rules without a runtime fetch',async()=>{const source=read('jh-chart-tvwatch.js'),line=source.split('\n').find(x=>x.startsWith('  function loadResolver(){'));assert.ok(line);const api=helpers(),c={window:{JHWatchlistQuotes:api},Promise,resolver:null,calls:0,fetch(){throw Error('No resolver network request permitted');},refreshQuotes(){c.calls++;}};vm.createContext(c);vm.runInContext(line,c);await c.loadResolver();assert.equal(c.calls,1);assert.equal(c.resolver.schema,'tv-resolver-1.0');});
test('all unrelated source bytes and previous preservation assertions remain intact',()=>{
 const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
 for(const [file,e] of Object.entries(transition.changes)){let raw=read(file);assert.equal(hash(raw),e.after_sha256);for(const x of [...e.edits].reverse()){assert.equal(raw.slice(x.start,x.end),x.after);raw=raw.slice(0,x.start)+x.before+raw.slice(x.end);}assert.equal(raw,read(e.before_path));assert.equal(hash(raw),e.before_sha256);}
 const before=JSON.parse(read('tests/fixtures/chart-provider-access/watchlist-transition.before.json')),after=JSON.parse(read('tests/fixtures/watchlist-correctness/source-transition.json'));
 for(const [file,row] of Object.entries(before)){const next=structuredClone(after[file]);if(['chart.html','jh-chart-tvwatch.js'].includes(file)){assert.deepEqual(next.edits.slice(0,row.edits.length),row.edits);next.edits=next.edits.slice(0,row.edits.length);next.after_sha256=row.after_sha256;}assert.deepEqual(next,row);}
});
