const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),test=require('node:test');
const parser={exports:{}};Function('exports','module',process.binding('natives')['internal/deps/acorn/acorn/dist/acorn'])(parser.exports,parser);
function boot(file){const raw=fs.readFileSync(file,'utf8'),body=parser.exports.parse(raw,{ecmaVersion:'latest'}).body.find(n=>n.expression?.callee?.type==='FunctionExpression').expression.callee.body.body,named=Object.fromEntries(body.filter(n=>n.type==='FunctionDeclaration').map(n=>[n.id.name,raw.slice(n.start,n.end)]));
 const els={quote:{},detail:{}},c={active:'INVENTED',tf:'1d',mode:'candles',window:{},lastAdr:null,lastOrLv:null,lastVsSpx:null,lastVP:{poc:null},tape:{delta:0,prints:[]},observationId:()=>false,periodVwap:()=>[],twap:()=>[],atr:()=>[],escHtml:String,fmt:String,document:{getElementById:id=>els[id]||null}};
 vm.createContext(c);vm.runInContext(['reportedVolume','fmtVol','rvolAt','closeLocationVolume','fmtSignedVol','quoteUI'].map(n=>named[n]).join('\n'),c);return{c,els};}
const frame=last=>Array.from({length:61},(_,i)=>({time:Date.UTC(2026,0,i+1)/1000,open:100,high:102,low:99,close:101,volume:i===60?last:100}));
for(const [volume,label] of [[0,'0.00x'],[Number.MIN_VALUE,'Unavailable'],[.0001,'&lt;0.01x'],[.1,'&lt;0.01x'],[.99,'&lt;0.01x'],[1,'0.01x'],[100,'1.00x'],[8000,'80.00x'],[null,'Unavailable']])test('quote and detail volume '+volume,()=>{const {c,els}=boot(path.join(__dirname,'../jh-chart-engine.js')),d=frame(volume),before=structuredClone(d);c.quoteUI(d);assert.deepEqual(d,before);assert.ok(els.quote.innerHTML.includes('RVOL '+label));assert.ok(els.detail.innerHTML.includes('RVOL 20</span><span>'+label));});
test('whole predecessor reproduces tiny-positive zero display',()=>{const {c,els}=boot(path.join(__dirname,'fixtures/chart-ratio-precision/engine-before.js.txt'));c.quoteUI(frame(.1));assert.ok(els.quote.innerHTML.includes('RVOL 0.00x'));assert.ok(els.detail.innerHTML.includes('RVOL 20</span><span>0.00x'));});

test('all arithmetic and unrelated source bytes survive the three exact display replacements',()=>require('./helpers/chart-ratio-precision-preservation.cjs').normalizeSource(fs.readFileSync(path.join(__dirname,'../jh-chart-engine.js'),'utf8')));
test('prior preservation remains whole with exactly two new dependency hooks',()=>{const root=path.join(__dirname,'..'),D=path.join(__dirname,'fixtures/chart-ratio-precision'),t=JSON.parse(fs.readFileSync(path.join(D,'helper-transition.json'),'utf8')),old=fs.readFileSync(path.join(D,'warehouse-helper-before.cjs.txt'),'utf8'),hash=x=>require('node:crypto').createHash('sha256').update(x).digest('hex');assert.equal(hash(old),t.before_sha256);let expected=old;for(const e of t.replacements){assert.equal(expected.split(e.before).length,2);expected=expected.replace(e.before,e.after);}const actual=fs.readFileSync(path.join(root,t.path),'utf8');assert.equal(actual,expected);assert.equal(hash(actual),t.after_sha256);});
