const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../chart.html'),'utf8'),candidate=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(x=>x[1]).find(x=>x.includes('window.__jhFetchGuard'));
function wrap(source,fetch){const root={fetch};vm.runInNewContext(source,{window:root,document:{addEventListener(){}},Date,Promise,Object,String});return root.fetch.bind(root);}
test('no-store retries perform new requests after a denial',async()=>{let calls=0;const fetch=wrap(candidate,async()=>new Response('invented',{status:++calls===1?403:200}));assert.equal((await fetch('/data/invented.json',{cache:'no-store'})).status,403);assert.equal((await fetch('/data/invented.json',{cache:'no-store'})).status,200);assert.equal(calls,2);});
test('different explicit contexts are never coalesced',async()=>{let calls=0;const releases=[],fetch=wrap(candidate,(_,options)=>{calls++;return new Promise(resolve=>releases.push(()=>resolve(new Response(options.headers['X-Invented-Context']))));});const a=fetch('/data/invented.json',{headers:{'X-Invented-Context':'A'}}),b=fetch('/data/invented.json',{headers:{'X-Invented-Context':'B'}});releases.forEach(f=>f());assert.equal(calls,2);assert.deepEqual(await Promise.all([a,b].map(async p=>(await p).text())),['A','B']);});
test('an aborted caller cannot join an unrelated in-flight request',async()=>{let release,calls=0;const controller=new AbortController();controller.abort();const fetch=wrap(candidate,(_,options)=>{calls++;if(options?.signal?.aborted)return Promise.reject(new DOMException('invented','AbortError'));return new Promise(resolve=>{release=()=>resolve(new Response('invented'));});});const active=fetch('/data/invented.json');await assert.rejects(fetch('/data/invented.json',{signal:controller.signal}),{name:'AbortError'});release();assert.equal((await active).status,200);assert.equal(calls,2);});
test('Request objects preserve their own context and options',async()=>{let received;const input=new Request('https://invented.invalid/data.json',{headers:{'X-Invented-Context':'A'}}),fetch=wrap(candidate,async(x,o)=>{received=[x,o];return new Response('invented');});await fetch(input);assert.equal(received[0],input);assert.equal(received[1],undefined);});
test('plain URL requests still coalesce and retain independent readable bodies',async()=>{let calls=0,release;const fetch=wrap(candidate,()=>{calls++;return new Promise(resolve=>{release=()=>resolve(new Response('invented'));});});const a=fetch('/data/invented.json'),b=fetch('/data/invented.json');release();assert.equal(calls,1);assert.deepEqual(await Promise.all([a,b].map(async p=>(await p).text())),['invented','invented']);});
test('the existing bare-request 403 and 404 storm suppression remains',async()=>{for(const status of [403,404]){let calls=0;const fetch=wrap(candidate,async()=>{calls++;return new Response('invented',{status});});assert.equal((await fetch('/data/invented.json')).status,status);assert.equal((await fetch('/data/invented.json')).status,status);assert.equal(calls,1);}});
test('explicit null or empty options still go straight to the native transport',async()=>{let calls=0;const fetch=wrap(candidate,async()=>{calls++;return new Response('invented',{status:403});});await fetch('/data/invented.json',null);await fetch('/data/invented.json',{});assert.equal(calls,2);});
