const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib'),crypto=require('node:crypto');
const v=require('../jh-china-calendar.js'),raw=zlib.gunzipSync(fs.readFileSync(path.join(__dirname,'fixtures/china-calendar-browser.json.gz'))),native=()=>JSON.parse(raw),now=Date.parse('2026-09-28T15:00:00Z'),sid='MANMM101CNM189S';
class Element{constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.textContent='';this.value='';}appendChild(n){this.children.push(n);return n;}replaceChildren(){this.children=[];this.textContent='';}text(){return this.textContent+this.children.map(n=>n.text()).join(' ');}set innerHTML(_){throw Error('Untrusted HTML forbidden');}}
function document(){const html=fs.readFileSync(path.join(__dirname,'../macro-leads.html'),'utf8'),nodes=new Map([...html.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],new Element('div')]));return{createElement:tag=>new Element(tag),getElementById:id=>nodes.get(id)||null};}

test('all eleven distinct series and 5320 original positions remain inspectable',()=>{
 const p=native(),before=JSON.stringify(p),out=v.view(p,now);assert.equal(p._synthetic_fixture,true);assert.ok(raw.length>1400000);assert.equal(out.native,true);assert.equal(out.authority,false);assert.equal(out.positions,5320);assert.equal(out.rows.length,11);assert.equal(out.rows[0].s.freshness,'stale');assert.equal(out.rows[0].s.current_measurement_eligible,false);assert.equal(out.rows[2].concept,'M2');assert.equal(out.rows[3].concept,'M3');assert.equal(out.rows[1].frequency,'Q');assert.equal(out.rows[9].concept,'gold_export_price_index');assert.equal(out.rows[10].usable,false);assert.equal(out.rows[10].rows.length,500);assert.equal(JSON.stringify(p),before);
});
test('definition, calendar, raw source, age, permissions and formula tampering are rejected',()=>{
 const mutations=[p=>p.measurement_review.series[sid].yoy.value++,p=>p.measurement_review.series[sid].money_growth_acceleration.value_pp++,p=>p.measurement_review.series[sid].three_month.comparison_date='2018-08-01',p=>p.measurement_review.series[sid].observations[0].value++,p=>p.measurement_review.series[sid].observation_response.observations[0].value='1_000',p=>p.measurement_review.series[sid].metadata_response.seriess[0].units='Index',p=>p.measurement_review.series[sid].current_measurement_eligible=true,p=>p.measurement_review.series[sid].observation_age_days--,p=>p.measurement_review.series[sid].freshness='within_age_policy',p=>p.measurement_review.series[sid].latest_period_end='2018-12-01',p=>p.measurement_review.series[sid].age_policy_days=9999,p=>p.calls_eligible=true,p=>p.regime='EASING',p=>p.credit_impulse.value_pp=5,p=>p.dr_copper.copper_gold_ratio=3,p=>delete p.measurement_review.series.MABMM301CNM189S,p=>p.publication_context.multiple_head_atomic=true,p=>p.publication_context.manifest.key='data/private-account.json',p=>delete p.compiler_sha256['china_store.py'],p=>p.generated_at='2026-09-29T00:00:00Z'];
 for(const change of mutations){const p=native();change(p);assert.throws(()=>v.view(p,now));}
});
test('daily FX and quarterly comparisons expose actual dates without row-count substitution',()=>{
 const out=v.view(native(),now),fx=out.rows.find(s=>s.id==='DEXCHUS'),q=out.rows.find(s=>s.id==='MANMM101CNQ189S');assert.equal(fx.s.three_month.comparison_date,'2026-06-25');assert.equal(q.s.yoy.comparison_date,'2017-10-01');assert.equal(q.s.three_month.comparison_date,'2018-07-01');assert.equal(v.shift('2024-02-29',-12),'2023-02-28');assert.deepEqual(v.comparison(0,10),{status:'measured',value:-100});assert.deepEqual(v.comparison(1,0),{status:'zero_denominator',value:null});assert.deepEqual(v.comparison(1,0,true),{status:'measured',value:1});assert.equal(v.number('-0'),-0);assert.equal(v.number('-1',true),-1);
 for(const n of [true,'1_000','1e999','1e-999','-1','NaN'])assert.throws(()=>v.number(n));
});
test('missing calendar denominator stays unavailable and all source positions survive',()=>{
 const p=native(),s=p.measurement_review.series.PCOPPUSDM,prior=s.yoy.comparison_date;const r=s.observations.find(r=>r.date===prior);r.value=null;r.status='missing';r.original.value='.';s.observation_response.observations[r.position].value='.';s.yoy.status='prior_period_missing';s.yoy.value=null;
 assert.equal(v.view(p,now).rows.find(r=>r.id==='PCOPPUSDM').s.yoy.value,null);assert.equal(v.view(p,now).positions,5320);
});
test('unqualified raw text is displayed safely and never promoted into a measurement',()=>{
 const p=native(),s=p.measurement_review.series.IR3TIB01CNM156S;s.observations[0].original.value='<img src=x onerror=alert(1)>';s.observation_response.observations[0].value=s.observations[0].original.value;
 const doc=document();v.render(doc,p,now);const select=doc.getElementById('china-choice');select.value='IR3TIB01CNM156S';select.onchange();for(let i=0;i<4;i++)doc.getElementById('china-prev').onclick();assert.match(doc.getElementById('china-months').text(),/<img src=x onerror=alert\(1\)>/);assert.match(doc.getElementById('china-months').text(),/Unqualified/);assert.match(doc.getElementById('china-definition').text(),/definition_not_reviewed/);
});
test('complete pagination, separate units and full raw packet remain available',()=>{
 const doc=document(),p=native();v.render(doc,p,now);assert.equal(doc.getElementById('china-choice').children.length,11);assert.match(doc.getElementById('china-row-count').textContent,/401–500 of 500/);for(let i=0;i<4;i++)doc.getElementById('china-prev').onclick();assert.match(doc.getElementById('china-row-count').textContent,/1–100 of 500/);assert.equal(doc.getElementById('china-prev').disabled,true);
 const select=doc.getElementById('china-choice');select.value='DEXCHUS';select.onchange();assert.match(doc.getElementById('china-row-count').textContent,/901–1000 of 1000/);assert.equal(doc.getElementById('china-next').disabled,true);assert.match(doc.getElementById('china-definition').textContent,/Chinese Yuan Renminbi to One U.S. Dollar/);doc.getElementById('china-prev').onclick();assert.match(doc.getElementById('china-row-count').textContent,/801–900/);
 const details=doc.getElementById('china-details');details.open=true;details.ontoggle();assert.deepEqual(JSON.parse(doc.getElementById('china-original').textContent),p);
});
test('failed, old and invalid replacements clear prior tables and obsolete callbacks',()=>{
 const doc=document();v.render(doc,native(),now);const next=doc.getElementById('china-next').onclick,select=doc.getElementById('china-choice').onchange,toggle=doc.getElementById('china-details').ontoggle;
 v.clear(doc,'Source unavailable');doc.getElementById('china-details').open=true;next();select();toggle();assert.equal(doc.getElementById('china-months').children.length,0);assert.equal(doc.getElementById('china-original').textContent,'Unavailable');assert.equal(doc.getElementById('china-choice').onchange,null);
 v.render(doc,{generated_at:'2026-09-25T14:30:00Z',regime:'EASING'},now);assert.match(doc.getElementById('china-calendar-status').textContent,/Legacy publication/);assert.equal(doc.getElementById('china-choice').children.length,0);
 v.render(doc,native(),now);const p=native();p.calls_eligible=true;assert.throws(()=>v.render(doc,p,now));assert.equal(doc.getElementById('china-series').children.length,0);
});
test('existing page retains its whole predecessor and loads China independently of Asia',()=>{
 const raw=fs.readFileSync(path.join(__dirname,'fixtures/pre-china-calendar-macro-leads.html.txt'));assert.equal(raw.length,20587);assert.equal(crypto.createHash('sha256').update(raw).digest('hex'),'a7ce4e86a4b9baa53a0c4568d353ddc0770b809631e3cdd252abf0e86a1accc1');
 const html=fs.readFileSync(path.join(__dirname,'../macro-leads.html'),'utf8');assert.equal((html.match(/load\('china'\)/g)||[]).length,1);assert.ok(html.indexOf("load('china')")<html.indexOf("load('asia')"));assert.match(html,/JHChinaCalendar.render\(document,chinaRaw\)/);assert.ok(html.indexOf('jh-business-cycle-review.js')<html.indexOf('jh-china-calendar.js'));assert.match(html,/unqualified financing extraction/);assert.ok(!html.includes("(cl.yoy_delta_trn||0)>0?'good'"));for(const name of ['macro','asia','china','geo','calendar'])assert.ok(html.includes("load('"+name+"')"));
});
