const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.join(__dirname,'..'),source=fs.readFileSync(path.join(root,'correlation.html'),'utf8'),before=fs.readFileSync(path.join(__dirname,'fixtures/correlation-heatmap-before.html.txt'),'utf8');
function inline(html){return [...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.includes('function renderHeatmap'));}
function warm(){return {schema_version:'1.0',generated_at:'2026-10-01T00:00:00Z',status:'warming_up',message:'Insufficient aligned data: 0 dates (need ≥312)',n_dates_aligned:0,instruments:['SP500','DGS10'],labels:{SP500:'S&P 500',DGS10:'10Y Yield'}};}
function valid(){return {...warm(),status:'ok',signal:'NORMAL',interpretation:'Backend interpretation retained',latest_matrix:[[1,0],[null,1]],delta_matrix:[[0,-0.25],[0.25,null]],n_instruments:2,n_dates_aligned:400,window_days:60};}
async function harness(first=warm(),html=source){const elements={},buttons=['hm-latest','hm-prior','hm-delta'];let payload=first;const get=id=>elements[id]??={innerHTML:'',textContent:'',style:{},attrs:{},classes:new Set(),classList:{add(c){get(id).classes.add(c)},remove(c){get(id).classes.delete(c)}},setAttribute(k,v){this.attrs[k]=v},addEventListener(_event,fn){this.click=fn;}};buttons.forEach(get);
const context=vm.createContext({console:{error(){}},Date,document:{getElementById:get,querySelectorAll:()=>buttons.map(get)},fetch:async()=>({ok:true,json:async()=>payload}),setInterval(){}});
vm.runInContext(inline(html).replace('\nloadData();','\nthis.initial = loadData();'),context);await context.initial;
return {elements,context,select(mode){get('hm-'+mode).click();},async refresh(next){payload=next;await context.loadData();}};}
test('reproduces the complete predecessor stale PRIOR message on latest',async()=>{const h=await harness(warm(),before);h.select('prior');h.select('delta');h.select('latest');assert.match(h.elements['heatmap-table'].innerHTML,/Prior matrix not available/);});
test('initial warming packet and repeated switches always match selected empty view',async()=>{const h=await harness();assert.match(h.elements['heatmap-table'].innerHTML,/Latest matrix is unavailable/);for(const mode of ['prior','delta','latest','delta','prior','latest']){h.select(mode);const html=h.elements['heatmap-table'].innerHTML;assert.match(html,new RegExp(mode==='prior'?'Prior matrix is not published':mode==='delta'?'Delta matrix is unavailable':'Latest matrix is unavailable'));assert.match(html,/0 dates \(need ≥312\)/);assert.doesNotMatch(html,/Try LATEST or DELTA/);for(const other of ['prior','delta','latest'])assert.equal(h.elements['hm-'+other].attrs['aria-pressed'],String(other===mode));}});
test('valid matrices, zero and missing cells survive repeated switching without data mutation',async()=>{const d=valid(),saved=JSON.stringify(d),h=await harness(d);for(const mode of ['latest','prior','delta','latest','prior','delta']){h.select(mode);const html=h.elements['heatmap-table'].innerHTML;if(mode==='prior'){assert.match(html,/not published/);assert.doesNotMatch(html,/heatmap-cell/);}else{assert.equal((html.match(/class="heatmap-cell"/g)||[]).length,4);assert.match(html,/>0\.00</);assert.match(html,/>—</);assert.match(html,mode==='delta'?/>-0\.25</:/>1\.00</);assert.doesNotMatch(html,/unavailable|not published/);}}assert.equal(JSON.stringify(d),saved);});
test('absent, null, empty, malformed and partial matrices have truthful mode-specific states',async()=>{for(const value of [undefined,null,[],{},'matrix',[[1]],[[1,0],null]]){const d=valid();d.latest_matrix=d.delta_matrix=value;const h=await harness(d);for(const mode of ['latest','delta']){h.select(mode);assert.match(h.elements['heatmap-table'].innerHTML,new RegExp(mode==='latest'?'Latest matrix is unavailable':'Delta matrix is unavailable'));assert.doesNotMatch(h.elements['heatmap-table'].innerHTML,/heatmap-cell/);}}});
test('refresh replaces old heatmap on warming and recovers in the selected mode',async()=>{const h=await harness(valid());h.select('delta');await h.refresh(warm());assert.match(h.elements['heatmap-table'].innerHTML,/Delta matrix is unavailable/);assert.doesNotMatch(h.elements['heatmap-table'].innerHTML,/heatmap-cell/);const d=valid();d.generated_at='2026-10-01T01:00:00Z';await h.refresh(d);assert.match(h.elements['heatmap-table'].innerHTML,/>-0\.25</);assert.equal(h.elements['hm-delta'].attrs['aria-pressed'],'true');assert.equal(h.elements['footer-ts'].textContent,d.generated_at);assert.equal(h.elements['composite-desc'].textContent,d.interpretation);h.select('prior');await h.refresh(d);assert.match(h.elements['heatmap-table'].innerHTML,/Prior matrix is not published/);});
test('only finite numeric cells render as numbers; warm text and labels are escaped',async()=>{const d=valid();d.latest_matrix=[[false,'0'],[Infinity,0]];d.instruments=['<img src=x>','DGS10'];d.labels={'<img src=x>':'<svg onload=alert(1)>'};const h=await harness(d);assert.equal((h.elements['heatmap-table'].innerHTML.match(/>—</g)||[]).length,3);assert.match(h.elements['heatmap-table'].innerHTML,/>0\.00</);assert.doesNotMatch(h.elements['heatmap-table'].innerHTML,/<img|<svg/);await h.refresh({...warm(),message:'<img src=x onerror=alert(1)>'});assert.match(h.elements['heatmap-table'].innerHTML,/&lt;img/);assert.doesNotMatch(h.elements['heatmap-table'].innerHTML,/<img/);});
test('all other renderer functions, feed URL, narrative markup and navigation remain byte-identical',()=>{assert.equal(crypto.createHash('sha256').update(before).digest('hex'),'4f4e02065df102b2582c7a6966b5756f62b3246b431997c343ff3f4a32fb17a3');const normalize=s=>inline(s).replace(/function renderHeatmap\(d, mode\) \{[\s\S]*?\nfunction renderHistoryChart/,'function renderHistoryChart').replace(/    renderHeatmap\(d, (?:HM_MODE|'latest')\);\n(?:\n)?/g,'');assert.equal(normalize(source),normalize(before));const prefix=s=>s.slice(0,s.indexOf('  <!-- Heatmap -->')).replace(/<style>[\s\S]*?<\/style>/,'');assert.equal(prefix(source),prefix(before));const links=s=>[...s.matchAll(/\b(?:href|src)="([^"]*)"/g)].map(m=>m[1]);assert.deepEqual(links(source),links(before));assert.match(source,/aria-live="polite"/);});
