const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),{source,fixture}=require('./crypto-sentiment-support.cjs');
function runtime(){const nodes={main:{innerHTML:''},ts:{textContent:''},'fg-full-chart':{innerHTML:''}},errors=[],scope={D:{},window:{},document:{getElementById:id=>nodes[id]},console:{error:e=>errors.push(String(e))}};vm.createContext(scope);vm.runInContext(source().code,scope);return {scope,nodes,errors};}
test('legacy unretained values and forged authority cannot become current sentiment',()=>{const {scope:s}=runtime();for(const p of [{current:50},null,true,[],{...fixture(),calls_eligible:true},{...fixture(),independent_investment_votes:false}])assert.equal(s.cryptoSentimentCurrent(p),null);});
test('zero survives while missing and booleans never become a neutral number',()=>{const {scope:s}=runtime();assert.equal(s.cryptoSentimentCurrent(fixture()),0);for(const v of [null,true,false,'0','',NaN,Infinity,-1,101]){const p=fixture();p.current=v;p.recent_reported_observations.history[0].value=v;assert.equal(s.cryptoSentimentCurrent(p),null);}});
test('complete UTC-date averages use all required dates and ignore supplied averages',()=>{const {scope:s}=runtime(),p=fixture();p.avg_7d=99;p.avg_30d=99;assert.equal(s.cryptoSentimentAverage(p,7),3);assert.equal(s.cryptoSentimentAverage(p,30),14.5);for(const n of [1,6,29]){const q=fixture(n);assert.equal(s.cryptoSentimentAverage(q,30),null);}p.recent_reported_observations.history[4].timestamp+=86400;assert.equal(s.cryptoSentimentAverage(p,7),null);});
test('copies disagreeing on a day withhold current or the affected average',()=>{const {scope:s}=runtime(),p=fixture();p.full_reported_observations.history[0].value=99;assert.equal(s.cryptoSentimentCurrent(p),null);assert.equal(s.cryptoSentimentAverage(p,7),null);assert.equal(s.cryptoSentimentAverage(p,30),null);});
test('source order retained, duplicate clocks resolve only identical values',()=>{const {scope:s}=runtime(),p=fixture(),rows=s.cryptoSentimentRows(p,'full');assert.equal(rows[0].source_row,'/data/0');assert.equal(rows.at(-1).source_row,'/data/30');const series=s.cryptoSentimentSeries([rows[0],{...rows[0],source_row:'/data/31'}]);assert.equal(series.length,1);assert.equal(series[0].source_rows.length,2);assert.equal(s.cryptoSentimentSeries([rows[0],{...rows[0],value:7}])[0].value,null);});
test('all thousand rows survive the table and synthetic legacy history is ignored',()=>{const {scope:s}=runtime(),p=fixture(1000);p.full_history=[{value:99,date:'2016-01-01',synthetic:true}];const html=s.renderCryptoSentimentHistory(p);assert.equal((html.match(/<tr><td>/g)||[]).length,2000);assert.match(html,/\/data\/999/);assert.doesNotMatch(html,/>2016-01-01</);assert.match(html,/Alternative\.me/);});
test('untrusted labels and reasons are escaped in every retained row',()=>{const {scope:s}=runtime(),p=fixture();p.full_reported_observations.history[0].label='<img src=x onerror=alert(1)>';p.full_reported_observations.history[0].reason='<script>bad</script>';const html=s.renderCryptoSentimentHistory(p);assert.doesNotMatch(html,/<img|<script>/);assert.match(html,/&lt;img/);});
test('actual UTC spacing and gaps replace ordinal points and invented prehistory',()=>{const {scope:s,nodes}=runtime(),p=fixture(3),rows=p.full_reported_observations.history;rows[2].timestamp-=86400;rows[2].observation_at=new Date(rows[2].timestamp*1000).toISOString();rows[2].date=rows[2].observation_at.slice(0,10);s.D={fear_greed:p};s.renderFullHistoryChart();const html=nodes['fg-full-chart'].innerHTML;assert.match(html,/cx='518\.333'/);assert.equal((html.match(/<circle/g)||[]).length,3);assert.match(html,/M45\.000,216\.200 M518\.333,218\.100 L755\.000,220\.000/);assert.doesNotMatch(html,/2016|next Lambda run/);});
test('full renderer preserves unrelated sections with valid, hostile and absent sentiment',()=>{for(const p of [fixture(),{},true,null]){const {scope:s,nodes,errors}=runtime();s.D={fear_greed:p,global_market:{btc_dominance:61}};s.render();assert.deepEqual(errors,[]);assert.match(nodes.main.innerHTML,/Sentiment Components/);assert.match(nodes.main.innerHTML,/>61<\/span>/);assert.match(nodes.main.innerHTML,/Stablecoin flow \(transaction evidence unavailable\)/);}});
test('unavailable population differs from a verified empty source array',()=>{const {scope:s}=runtime(),p=fixture();p.full_reported_observations={status:'unavailable'};assert.match(s.renderCryptoSentimentHistory(p),/Full-history endpoint: Unavailable retained source rows/);p.full_reported_observations={status:'descriptive',returned_rows:0,history:[]};assert.match(s.renderCryptoSentimentHistory(p),/Full-history endpoint: 0 retained source rows/);p.full_reported_observations.history=null;assert.match(s.renderCryptoSentimentHistory(p),/Full-history endpoint: Unavailable retained source rows/);});
