const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),api=require('../jh-dealer-research.js');
const stamp='2026-09-19T11:00:00Z',now=Date.parse(stamp);
function quality(){return {status:'fresh',observation_date:'2026-09-09',acquired_at:stamp,next_expected_publication_date:'2026-09-24T20:15:00Z',max_acquisition_age_hours:192};}
function series(id='PDSI2NSP'){return {definition:{series_id:id,definition_status:'reviewed',family:'specific_issue_position',native_unit:'usd_mn',valuation_basis:'original_issuance_par',catalog:{description:'Specific issue net position'},note:'On-the-run identity rolls'},history:[['2026-09-02',-10,0,'observed','SBN2024'],['2026-09-09',0,1,'observed','SBN2024']],reported_value:0,as_of:'2026-09-09',original_row_index:1,catalog_row_index:2,quality:quality(),comparisons:{},statistics:{status:'insufficient_comparable_prior_reports',method:'Current excluded',prior_n:1,z:null,percentile:null}};}
function packet(){return {contract:api.CONTRACT,generated_at:stamp,source_generated_at:stamp,call:null,calls_eligible:false,sizing_eligible:false,execution_eligible:false,native_series:Object.fromEntries(Array.from({length:70},(_,i)=>{const id=i?'fixture'+i:'PDSI2NSP';return [id,series(id)];})),groups:{},quality:{total_series:70,counts:{fresh:70,incomplete:0,definition_unverified:0}},sources:{observations:{evidence:{key:'data/evidence/fr2004/original.bin.gz'}},catalog:{evidence:{key:'data/evidence/fr2004/catalog.bin.gz'}},breaks:{evidence:{key:'data/evidence/fr2004/breaks.bin.gz'}},SBN2024:{evidence:{key:'data/evidence/fr2004/instructions.bin.gz'}}},section_pages:{SBN2024:{specific_issue_position:33}},revisions:{known_changed_values:0},replay:{manifest_key:api.PREFIX+'runs/'+'a'.repeat(64)+'.json'}};}

test('signed values, zero, source row and reviewed value basis survive rendering',()=>{const p=packet();api.boundary(p);const html=api.detail(p,'series:PDSI2NSP',now,false);assert.match(html,/<strong>0 USD millions/);assert.match(html,/Original observation row 1, catalog row 2/);assert.match(html,/PDF page 33/);assert.match(html,/original issuance par/);assert.match(api.history(p,'series:PDSI2NSP').html,/-10/);});
test('unresolved source units remain numeric originals without normalized comparisons',()=>{const p=packet(),r=p.native_series.PDSI2NSP;r.definition.definition_status='unresolved';r.definition.native_unit='publisher_units_unverified';r.quality.status='definition_unverified';const html=api.detail(p,'series:PDSI2NSP',now,false);assert.match(html,/unit normalization unverified/);assert.match(html,/Definition unresolved/);assert.match(html,/Current comparisons withheld/);assert.doesNotMatch(html,/Signed z/);});
test('dealer and fails context use their own source acquisition expiry',()=>{const q=quality();assert.equal(api.current(q,now),true);assert.equal(api.current(q,now+9*86400000),false);q.max_acquisition_age_hours=36;assert.equal(api.current(q,now+37*3600000),false);assert.equal(api.current(q,now+37*3600000,true),true);q.status='incomplete';assert.equal(api.current(q,now,true),false);});
test('original identity, exact sum and unauthorized decisions are rejected',()=>{const p=packet();p.native_series.PDSI2NSP.definition.series_id='OTHER';assert.throws(()=>api.boundary(p),/identity/);const q=packet();q.groups.x={usd_mn:11,components:{one:{usd_mn:10}}};assert.throws(()=>api.boundary(q),/reconcile/);const r=packet();r.sizing_eligible=true;assert.throws(()=>api.boundary(r),/contract/);});
test('chart uses real dates and breaks at gaps, suppression and source periods',()=>{const rows=[{date:'2024-01-03',value:-2,period:'a'},{date:'2024-01-10',value:0,period:'a'},{date:'2024-01-24',value:4,period:'a'},{date:'2024-01-31',value:3,period:'b'}];const html=api.chart(rows,0),path=html.match(/<path d="([^"]*)"/)[1];assert.equal((path.match(/M/g)||[]).length,3);assert.match(html,/zero line is a sign reference/);rows[1].value=null;assert.equal((api.chart(rows).match(/<path d="([^"]*)"/)[1].match(/L/g)||[]).length,0);});
test('history retains oldest reports and suppressed values on later pages',()=>{const p=packet(),r=p.native_series.PDSI2NSP;r.history=Array.from({length:105},(_,i)=>[new Date(Date.UTC(2024,0,3)+i*7*86400000).toISOString().slice(0,10),i?0:null,i,i?'observed':'suppressed','SBN2024']);const h=api.history(p,'series:PDSI2NSP',10);assert.equal(h.page,2);assert.equal(h.count,105);assert.match(h.html,/2024-01-03/);assert.match(h.html,/suppressed/);assert.match(h.html,/—/);});
test('source descriptions are escaped and only confined evidence paths become links',()=>{const p=packet();p.native_series.PDSI2NSP.definition.catalog.description='<script>bad()</script>';const html=api.detail(p,'series:PDSI2NSP',now,false);assert.ok(!html.includes('<script>'));assert.match(html,/&lt;script&gt;/);assert.equal(api.path('data/../../private'),null);assert.equal(api.path('https://untrusted'),null);});
test('retained run requires matching bytes, current contract and generation clock',async()=>{const p=packet();delete p.replay;const output=new TextEncoder().encode(JSON.stringify(p)),sha=await api.sha(output),m={contract:'dealer-original-replay.v1',generated_at:stamp,output_sha256:sha,output:{key:api.PREFIX+'outputs/'+sha+'.json',sha256:sha,bytes:output.length}},raw=new TextEncoder().encode(JSON.stringify(m)),id=await api.sha(raw),files={['/'+api.PREFIX+'runs/'+id+'.json']:raw,['/'+m.output.key]:output};const fetcher=async key=>new Response(files[key],{status:files[key]?200:404});assert.equal((await api.loadSnapshot(id,fetcher)).contract,api.CONTRACT);files['/'+m.output.key]=new TextEncoder().encode('{}');await assert.rejects(api.loadSnapshot(id,fetcher),/differs/);await assert.rejects(api.loadSnapshot('a'.repeat(64),async()=>new Response(new Uint8Array(256*1024+1))),/size bound/);});
test('page uses a single immutable snapshot and pins the selected measurement',()=>{const html=fs.readFileSync(require.resolve('../primary-dealers.html'),'utf8'),js=fs.readFileSync(require.resolve('../jh-dealer-page.js'),'utf8');assert.match(html,/jh-dealer-research.js/);assert.ok(!html.includes('jh-page-ai'));assert.ok(!html.includes('data/history/nyfed-pd-corp.json'));assert.match(js,/Current pointer differs/);assert.match(js,/encodeURIComponent\(selected\)/);assert.match(js,/setInterval\(render,60000\)/);});

test('older native observations keep their numbers with unverified historical scope',()=>{const p=packet(),r=p.native_series.PDSI2NSP;r.reviewed_catalog_period='SBN2024';r.history_scope_note='Earlier scopes have not been verified.';r.history[0][4]='SBN2022';const h=api.history(p,'series:PDSI2NSP').html;assert.match(h,/-10/);assert.match(h,/historical scope unverified/);assert.match(api.detail(p,'series:PDSI2NSP',now,false),/do not verify the historical mapping/);});
