const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),api=require('../jh-etf-research.js');
const now=Date.parse('2026-09-19T19:30:00Z');
function packet(){return {contract:api.CONTRACT,generated_at:'2026-09-19T19:15:00Z',call:null,calls_eligible:false,sizing_eligible:false,execution_eligible:false,additional_independent_calls_votes:0,n_etfs:128,quality:{native_histories:81,native_observations:429188,aligned_five_observation_estimates:81,all_funds_covered:false},aggregation_period:{end_date:'2026-09-17'},by_etf:{IVV:{history:{},source:{acquired_at:'2026-09-19T19:00:00Z'}}}};}
test('ETF evidence remains descriptive and source-check labels expire',()=>{const p=packet();assert.equal(api.summary(p,now,false).state,'partial coverage');assert.equal(api.status(p,now+49*3600000,false),'source check expired');assert.equal(api.status(p,now+49*3600000,true),'historical snapshot');p.additional_independent_calls_votes=1;assert.throws(()=>api.boundary(p));p.additional_independent_calls_votes=0;p.calls_eligible=true;assert.throws(()=>api.boundary(p));});
test('missing issuer history never plots or labels a fabricated zero flow',()=>{const p=packet();p.by_etf.QQQ={source_status:'unreviewed',vendor_context:{}};assert.match(api.detail(p,'QQQ'),/Missing estimates remain unavailable/);assert.throws(()=>api.detail(p,'NOT_IN_UNIVERSE'));});
test('complete history pagination keeps invalid source observations and zero versus unavailable',()=>{const doc={contract:'etf-native-history.v1',rows:Array.from({length:25},(_,i)=>({date:'2026-09-'+String(i+1).padStart(2,'0'),nav_decimal:i===0?'0':'100',shares_decimal:'1000',nav_valued_share_change_decimal:i===0?null:'0',flow_status:i===0?'<unreviewed>':'descriptive_estimate',source_row:i}))};assert.equal(api.history(doc).count,25);assert.equal(api.history(doc).pages,2);assert.match(api.history(doc).html,/<td>0<\/td>/);assert.match(api.history(doc,1).html,/&lt;unreviewed&gt;/);assert.match(api.history(doc,1).html,/<td>—<\/td>/);assert.throws(()=>api.history({contract:'unknown',rows:[]}));});
test('excluded flow observations break chart while valid native NAV remains visible',()=>{const doc={rows:[['2026-09-15','10','descriptive_estimate'],['2026-09-16',null,'possible_split_or_unreviewed_action'],['2026-09-17','20','descriptive_estimate']].map(([date,flow,status])=>({date,nav_decimal:'100',shares_decimal:'1000',nav_valued_share_change_decimal:flow,flow_status:status}))};const chart=api.chart(doc,'flow',0,350);assert.equal((chart.match(/<path /g)||[]).length,2);assert.match(chart,/viewBox="0 0 350 240"/);assert.ok(!chart.includes('NaN'));assert.equal((api.chart(doc,'nav').match(/<path /g)||[]).length,1);});
test('portfolio scenario uses entry and exit premiums and does not infer returns from fund flow',()=>{const x={exposure:100000,navPct:5,entryBp:200,exitBp:0,income:1000,costs:100,days:30},s=api.scenario(x);assert.ok(Math.abs(s.net_pnl-3841.176470588)<1e-7);assert.equal(s.forecast,false);assert.equal(s.automatic_position_size,null);assert.equal(s.issuance_to_return_coefficient,null);assert.equal(api.scenario({...x,days:365}).net_pnl,s.net_pnl);assert.equal(api.scenario({...x,navPct:0,entryBp:0,exitBp:0,income:0,costs:0}).net_pnl,0);for(const change of [{costs:undefined},{navPct:-100},{entryBp:5001},{exposure:0},{days:1.5},{income:NaN}])assert.throws(()=>api.scenario({...x,...change}));});
test('selected ETF artifact requires exact bytes and retained namespace',async()=>{const raw=Buffer.from('{"rows":[]}'),sha=crypto.createHash('sha256').update(raw).digest('hex'),ref={key:api.PREFIX+'histories/'+sha+'.json',sha256:sha,bytes:raw.length};assert.deepEqual(await api.verified(async()=>new Response(raw),ref),{rows:[]});await assert.rejects(()=>api.verified(async()=>new Response('{}'),ref));await assert.rejects(()=>api.verified(async()=>new Response(raw),{...ref,key:'data/private/'+sha+'.json'}));await assert.rejects(()=>api.verified(async()=>new Response(raw),{...ref,bytes:20*1024*1024}));});
