const test=require('node:test'),assert=require('node:assert/strict');
const api=require('../jh-extremes-research.js');
const key='data/market-extremes.json',pause=()=>new Promise(resolve=>setImmediate(resolve));
function source(chunks,options={}){let n=0,cancelled=0,read=0;return {ok:options.ok??true,status:options.status??200,
 body:{getReader(){return {read(){read++;return options.stall?new Promise(()=>{}):Promise.resolve(n<chunks.length?{value:chunks[n++],done:false}:{done:true});},cancel(){cancelled++;return Promise.resolve();},releaseLock(){} };},cancel(){cancelled++;return Promise.resolve();}},get cancelled(){return cancelled;},get reads(){return read;}};}
test('bounded response preserves split UTF-8 bytes, zero and null',async()=>{const bytes=new TextEncoder().encode('{"label":"測試","zero":0,"missing":null}'),response=source(Array.from(bytes,b=>new Uint8Array([b])));const result=await api.load(key,async()=>response);assert.deepEqual(new Uint8Array(result.raw),bytes);assert.deepEqual(result.doc,{label:'測試',zero:0,missing:null});assert.equal(response.cancelled,1);});
test('deadline covers a fetch promise that ignores cancellation',async()=>{let signal;await assert.rejects(api.load(key,async(url,o)=>{signal=o.signal;return new Promise(()=>{});},null,{timeoutMs:5}),/timed out/);assert.equal(signal.aborted,true);});
test('deadline covers a body that ignores cancellation',async()=>{const response=source([],{stall:true});await assert.rejects(api.load(key,async()=>response,null,{timeoutMs:5}),/timed out/);assert.equal(response.cancelled,1);});
test('too large response stops before subsequent chunks',async()=>{const response=source(Array.from({length:5},()=>new Uint8Array(2*1024*1024)));await assert.rejects(api.load(key,async()=>response),/response bound/);assert.equal(response.reads,3);assert.equal(response.cancelled,1);});
test('invalid UTF-8, incomplete JSON and missing streaming bodies fail',async()=>{for(const bytes of [new Uint8Array([0xc0,0x80]),new TextEncoder().encode('{"cut":')]){const response=source([bytes]);await assert.rejects(api.load(key,async()=>response));assert.equal(response.cancelled,1);}await assert.rejects(api.load(key,async()=>({ok:true,arrayBuffer:async()=>new ArrayBuffer(0)})),/Readable complete/);});
test('non-success bodies are cancelled without reading',async()=>{const response=source([],{ok:false,status:503});await assert.rejects(api.load(key,async()=>response),/HTTP 503/);assert.equal(response.reads,0);assert.equal(response.cancelled,1);});
test('parent cancellation stops pending bodies and avoids requests if already aborted',async()=>{let calls=0;const prior=new AbortController();prior.abort();await assert.rejects(api.load(key,async()=>{calls++;},prior.signal),{name:'AbortError'});assert.equal(calls,0);const controller=new AbortController(),response=source([],{stall:true});const job=api.load(key,async()=>response,controller.signal);await pause();controller.abort();await assert.rejects(job,{name:'AbortError'});assert.equal(response.cancelled,1);});
test('late responses are cancelled after deadline instead of read',async()=>{let release;const response=source([new TextEncoder().encode('{}')]);const job=api.load(key,()=>new Promise(resolve=>release=resolve),null,{timeoutMs:5});await assert.rejects(job,/timed out/);release(response);await pause();assert.equal(response.reads,0);assert.equal(response.cancelled,1);});
test('late body completion cannot resume consumption',async()=>{let release,reads=0,cancelled=0;const response={ok:true,body:{getReader(){return {read(){reads++;return new Promise(resolve=>release=resolve);},cancel(){cancelled++;return Promise.resolve();},releaseLock(){}};}}};const job=api.load(key,async()=>response,null,{timeoutMs:5});await assert.rejects(job,/timed out/);release({value:new TextEncoder().encode('{}'),done:false});await pause();assert.equal(reads,1);assert.equal(cancelled,1);});

test('deadline remains a timeout when the fetcher rejects with AbortError on cancellation',async()=>{await assert.rejects(api.load(key,(url,options)=>new Promise((resolve,reject)=>{options.signal.addEventListener('abort',()=>{const e=Error('aborted');e.name='AbortError';reject(e);});}),null,{timeoutMs:5}),error=>error.name!=='AbortError'&&/timed out/.test(error.message));});
