const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const api=require('../jh-fails-research.js'),stamp='2026-09-19T11:00:00Z',now=Date.parse(stamp);
function row(){return {scope_id:'treasury_incl_tips',label:'Treasury including TIPS',unit:'usd_bn',as_of:'2026-09-09',complete:true,ftd_usd_mn:0,ftr_usd_mn:101,gross_usd_mn:101,exact_usd_bn:{ftd:'0',ftr:'0.101',gross:'0.101'},quality:{status:'fresh',acquired_at:stamp,next_expected_publication_date:'2026-09-24T20:15:00Z'},history:[{date:'2026-09-02',seriesbreak:'SBN2024',ftd_usd_mn:20,ftr_usd_mn:100,gross_usd_mn:120,complete:true,components:{}},{date:'2026-09-09',seriesbreak:'SBN2024',ftd_usd_mn:0,ftr_usd_mn:101,gross_usd_mn:101,complete:true,components:{'PDFTD-USTET':{row_index:0,value_usd_mn:0,status:'observed'}}}],statistics:{status:'insufficient_comparable_prior_reports',baseline:{sample_n:1},z:null,pctile:null},previous_reported_change:null};}
function packet(){return {contract:api.CONTRACT,call:null,calls_eligible:false,sizing_eligible:false,execution_eligible:false,generated_at:stamp,source_generated_at:stamp,treasury:row(),headline:row(),totals:{...row(),scope_id:'all_asset'},classes:Array.from({length:6},(_,i)=>({...row(),scope_id:'class'+i})),sources:{observations:{evidence:{key:'data/evidence/fr2004/source.bin.gz'}},catalog:{evidence:{key:'data/evidence/fr2004/catalog.bin.gz'}},breaks:{evidence:{key:'data/evidence/fr2004/breaks.bin.gz'}}},series_coverage:{one:{observations:2}},reporting_periods:{},measurement_note:'Cumulative two-sided reported amounts.',revisions:{known_changed_values:0},replay:{manifest_key:api.PREFIX+'runs/'+'a'.repeat(64)+'.json'}};}
test('exact zero, separate scopes and reported source rows survive rendering',()=>{const p=packet(),html=api.detail(p,p.treasury,now,false);assert.match(html,/0 \+ 0.101 = 0.101 USD bn/);assert.match(html,/PDFTD-USTET/);assert.match(html,/<td>0<\/td><td>0<\/td>/);assert.equal(api.scopes(p).length,8);assert.match(api.overview(p,now,false).hero,/WAIT means abstain/);});
test('source acquisition and release expiry never renew from page generation',()=>{const r=row();assert.equal(api.current(r,now),true);assert.equal(api.current(r,now+37*3600000),false);assert.equal(api.current(r,now+37*3600000,true),true);r.quality.status='incomplete';assert.equal(api.current(r,now,true),false);});
test('non-reconciling gross and authority changes are rejected',()=>{const p=packet();p.treasury.gross_usd_mn=102;assert.throws(()=>api.boundary(p),/reconcile/);const q=packet();q.calls_eligible=true;assert.throws(()=>api.boundary(q),/contract/);});
test('suppressed data stays unavailable and zero SD is not an invented z',()=>{const p=packet();p.treasury.statistics={status:'constant_prior_sample',baseline:{sample_n:52},z:null,pctile:50,mean:1,standard_deviation_usd_mn_decimal:'0'};assert.match(api.detail(p,p.treasury,now),/z —/);assert.match(api.detail(p,p.treasury,now),/z is undefined/);assert.match(api.detail(p,p.treasury,now+37*3600000),/source is incomplete or expired/);});
test('charts break at source periods, gaps and suppressed observations',()=>{const r=row();r.history.push({...r.history[1],date:'2026-09-23',ftd_usd_mn:null,ftr_usd_mn:null});r.history.push({...r.history[1],date:'2026-09-30'});const html=api.chart(r.history,0);assert.equal([...html.matchAll(/<path d="([^"]*)"/g)].reduce((n,m)=>n+(m[1].match(/M/g)||[]).length,0),4);const changed=row();changed.history[1].seriesbreak='SBN_NEXT';assert.equal([...api.chart(changed.history).matchAll(/<path d="([^"]*)"/g)].reduce((n,m)=>n+(m[1].match(/M/g)||[]).length,0),4);assert.match(html,/2026-09-30/);assert.match(html,/source-period breaks/);});
test('history pagination preserves older rows without arbitrary monthly sampling',()=>{const r=row();r.history=Array.from({length:105},(_,i)=>({...r.history[0],date:new Date(Date.UTC(2024,0,3)+i*7*86400000).toISOString().slice(0,10)}));const view=api.history(r,10);assert.equal(view.page,2);assert.equal(view.count,105);assert.match(view.html,/2024-01-03/);});
test('untrusted source names are escaped and paths are constrained',()=>{const p=packet();p.treasury.label='<img src=x onerror=alert(1)>';assert.ok(!api.overview(p,now).scopes.includes('<img'));assert.equal(api.path('data/../private'),null);assert.equal(api.path('https://elsewhere'),null);});
test('immutable run, output bytes, clock and size must verify',async()=>{const p=packet();delete p.replay;const output=new TextEncoder().encode(JSON.stringify(p)),sha=await api.sha(output),manifest={contract:'fr2004-fails-replay.v1',generated_at:stamp,output_sha256:sha,output:{key:api.PREFIX+'outputs/'+sha+'.json',sha256:sha,bytes:output.length}},raw=new TextEncoder().encode(JSON.stringify(manifest)),id=await api.sha(raw),files={['/'+api.PREFIX+'runs/'+id+'.json']:raw,['/'+manifest.output.key]:output};const fetcher=async key=>new Response(files[key],{status:files[key]?200:404});assert.equal((await api.loadSnapshot(id,fetcher)).contract,api.CONTRACT);files['/'+manifest.output.key]=new TextEncoder().encode('{}');await assert.rejects(api.loadSnapshot(id,fetcher),/differs/);await assert.rejects(api.loadSnapshot('a'.repeat(64),async()=>new Response(new Uint8Array(256*1024+1))),/size bound/);});
test('page uses one immutable snapshot, no PageAI and a current-data expiry refresh',()=>{const html=fs.readFileSync(require.resolve('../fails.html'),'utf8'),js=fs.readFileSync(require.resolve('../jh-fails-page.js'),'utf8');assert.match(html,/jh-fails-research.js/);assert.ok(!html.includes('jh-page-ai'));assert.ok(!html.includes('jh-pd-fails-strip'));assert.match(js,/loadSnapshot/);assert.match(js,/Current pointer differs/);assert.match(js,/setInterval\(render,60000\)/);});
