const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),api=require('../jh-flow-research.js');
const at=Date.parse('2026-09-19T20:00:00Z');
function packet(){return {contract:api.CONTRACT,generated_at:'2026-09-19T19:00:00Z',source_generated_at:'2026-09-19T18:00:00Z',source_reference_date:'2026-09-18',call:null,calls_eligible:false,sizing_eligible:false,execution_eligible:false,additional_independent_votes:0,groups:{},funds:{},quality:{status:'partial',configured_funds:128,source_histories:81,aligned_funds:81,issuer_classified_funds:49}};}
test('research permissions reject trading authority; latest publication expires while pinned evidence remains historical',()=>{const p=packet();assert.equal(api.summary(p,at).state,'partial fund coverage');assert.equal(api.status(p,at+49*3600000),'source check expired');assert.equal(api.status(p,at+49*3600000,true),'historical snapshot');for(const field of ['calls_eligible','sizing_eligible','execution_eligible'])assert.throws(()=>api.boundary({...p,[field]:true}));assert.throws(()=>api.boundary({...p,additional_independent_votes:1}));assert.throws(()=>api.boundary({...p,call:'LONG'}));assert.equal(api.status({...p,source_generated_at:'2026-10-01'},at),'source check expired');});
function row(date,value,members=['IVV']){return {date,one_observation_decimal:value,five_observation_decimal:value,five_start_date:'2026-09-01',one_covered_members:members,five_covered_members:members};}
test('full history preserves exact zero, missing rows and membership with bounded pagination',()=>{const doc={contract:'flow-desk-history.v1',rows:Array.from({length:25},(_,i)=>row('2026-09-'+String(i+1).padStart(2,'0'),i===0?null:'0'))};assert.equal(api.history(doc).count,25);assert.equal(api.history(doc).pages,2);assert.match(api.history(doc).html,/<td>0<\/td>/);assert.match(api.history(doc,1).html,/<td>—<\/td>/);assert.throws(()=>api.history({contract:'unknown',rows:[]}));assert.equal(api.million(null),'—');assert.equal(api.million(0),'0');});
test('chart breaks on both missing observations and changed covered funds, without NaN or compressed dates',()=>{const doc={rows:[row('2026-09-14','100'),row('2026-09-15','200',['IVV','AGG']),row('2026-09-16',null),row('2026-09-18','0',['IVV','AGG'])]};const chart=api.chart(doc,'five',0,350);assert.equal((chart.match(/<path /g)||[]).length,3);assert.match(chart,/viewBox="0 0 350 260"/);assert.match(chart,/2026-09-18/);assert.ok(!chart.includes('NaN'));assert.match(api.chart({rows:[row('2026-09-18',null)]}),/Missing values are not zero/);});
test('group details expose issuer classification and overlap without treating unknown coverage as zero',()=>{const p=packet();p.groups.test={label:'<group>',kind:'configured_basket',scope:'covered funds',configured_members:['IVV','QQQ'],net_flow_5d_usd:0,coverage_count:1,configured_count:2,period:{start_date:'2026-09-10',end_date:'2026-09-17'}};p.funds.IVV={history:{},source_snapshot:'/etf-research.html?run=abc',identity:{fund_name:'<fund>'},comparison:{net_flow_5d_usd:0},issuer_classification:{status:'reported_issuer_classification',asset_class:'Equity',sub_asset_class:'Large/Mid Cap'},observation_date:'2026-09-18'};p.overlapping_memberships={IVV:['one','two']};const html=api.detail(p,'test');assert.match(html,/&lt;group&gt;/);assert.match(html,/&lt;fund&gt;/);assert.match(html,/Equity \/ Large\/Mid Cap/);assert.match(html,/Unreviewed classification/);assert.match(html,/<td>—<\/td>/);assert.match(html,/count it repeatedly/);assert.throws(()=>api.detail(p,'missing'));});
test('multi-position scenario combines local price and currency multiplicatively with cash and costs once',()=>{const positions=[{label:' US ',exposure:100000,pricePct:5,fxPct:0,income:1000,costs:100},{label:'EU',exposure:50000,pricePct:-10,fxPct:5,income:500,costs:50}];const s=api.scenario(positions,30);assert.ok(Math.abs(s.positions[0].net_pnl-5900)<1e-8);assert.ok(Math.abs(s.positions[1].net_pnl+2300)<1e-8);assert.ok(Math.abs(s.net_pnl-3600)<1e-8);assert.ok(Math.abs(s.net_return-.024)<1e-10);assert.equal(s.positions[0].inputs.label,'US');assert.equal(s.forecast,false);assert.equal(s.probability,null);assert.equal(s.fund_flow_to_return_coefficient,null);assert.equal(s.automatic_allocation,null);assert.equal(api.scenario(positions,365).net_pnl,s.net_pnl);});
test('explicit zero and full price loss are valid; absent, non-finite and impossible scenarios are rejected',()=>{const x={label:'Zero',exposure:100,pricePct:0,fxPct:0,income:0,costs:0};assert.equal(api.scenario([x],1).net_pnl,0);assert.equal(api.scenario([{...x,pricePct:-100}],1).net_pnl,-100);for(const change of [{label:''},{exposure:0},{pricePct:-101},{income:undefined},{fxPct:NaN},{costs:Infinity},{costs:-1}])assert.throws(()=>api.scenario([{...x,...change}],30));for(const days of [0,1.5,3651])assert.throws(()=>api.scenario([x],days));assert.throws(()=>api.scenario([],30));assert.throws(()=>api.scenario(Array(13).fill(x),30));});
test('flow history rejects altered bytes and artifacts outside its immutable namespace',async()=>{const raw=Buffer.from('{"rows":[]}'),sha=crypto.createHash('sha256').update(raw).digest('hex'),ref={key:api.PREFIX+'histories/'+sha+'.json',sha256:sha,bytes:raw.length};assert.deepEqual(await api.verified(async()=>new Response(raw),ref),{rows:[]});await assert.rejects(()=>api.verified(async()=>new Response('{}'),ref));await assert.rejects(()=>api.verified(async()=>new Response(raw),{...ref,key:'data/private/'+sha+'.json'}));await assert.rejects(()=>api.verified(async()=>new Response(raw),{...ref,bytes:20*1024*1024}));});
