const {test}=require('node:test'),assert=require('node:assert/strict'),api=require('../jh-foreign-research.js');
const now=Date.parse('2026-09-19T18:00:00Z');
function packet(){return {contract:api.CONTRACT,call:null,calls_eligible:false,sizing_eligible:false,execution_eligible:false,groups:{},latest_month:'2026-07-01',flows_bn:{total:{latest:0},treas:{latest:-3.7},equity:{latest:1},tbills:{latest:2}},quality:{status:'fresh',original_archive_acquired_at:'2026-09-19T17:00:00Z',calendar_acquired_at:'2026-09-19T17:00:00Z',calendar_expires_at:'2026-10-17T04:00:00Z'}};}
function group(){return {code:'10251',name:'Belgium',series:{'lt_treas:pos':{rows:[{date:'2026-01-01',value_decimal:'0',row_index:2},{date:'2026-02-01',value_decimal:null,row_index:1},{date:'2026-03-01',value_decimal:'1200',row_index:0}],coverage:{observations:3}}},decompositions:{lt_treas:[{ending_month:'2026-03-01',holdings_change_usd_million_decimal:'25',transactions_usd_million_decimal:'10',valuation_change_usd_million_decimal:'7',other_change_residual_usd_million_decimal:'8',status:'complete'}]}};}
test('foreign current totals expire without erasing explicitly dated snapshots',()=>{const p=packet();assert.match(api.summary(p,now,false).cards,/<strong>0<\/strong>/);assert.match(api.summary(p,now+27*3600000,false).cards,/<strong>—<\/strong>/);assert.match(api.summary(p,now+27*3600000,true).cards,/-3.7/);p.quality.status='partial';assert.match(api.summary(p,now,false).cards,/<strong>—<\/strong>/);p.calls_eligible=true;assert.throws(()=>api.boundary(p));});
test('holdings are labeled stocks and missing source values remain missing',()=>{const g=group(),h=api.history(g,'lt_treas','pos','native');assert.equal(h.count,3);assert.match(h.html,/>0<\/td>/);assert.match(h.html,/>—<\/td>/);assert.match(h.html,/1,200/);const chart=api.chart(g,'lt_treas','pos','native',0,350);assert.match(chart,/viewBox="0 0 350 240"/);assert.match(chart,/holdings stock, not an amount to sum/);assert.equal((chart.match(/<path /g)||[]).length,2);assert.ok(!chart.includes('NaN'));});
test('omitted calendar months break a chart and source counts must match',()=>{const g=group();g.series['lt_treas:pos'].rows.splice(1,1);assert.throws(()=>api.history(g,'lt_treas','pos','native'));g.series['lt_treas:pos'].coverage.observations=2;assert.equal((api.chart(g,'lt_treas','pos','native').match(/<path /g)||[]).length,2);});
test('holdings decomposition exposes other changes rather than relabeling them as purchases',()=>{const g=group();const t=api.history(g,'lt_treas','pos','decomposition');assert.match(t.html,/Other residual/);assert.match(t.html,/>8<\/td>/);assert.match(api.chart(g,'lt_treas','pos','decomposition'),/Monthly change in holdings/);assert.throws(()=>api.history(g,'treas','pos','decomposition'));});
test('artifact path, bytes and SHA must all bind before rendering',async()=>{const raw=new TextEncoder().encode(JSON.stringify(group())),sha=require('node:crypto').createHash('sha256').update(raw).digest('hex'),ref={key:api.PREFIX+'histories/'+sha+'.json',bytes:raw.length,sha256:sha};assert.deepEqual(await api.verified(async()=>new Response(raw),ref),group());await assert.rejects(()=>api.verified(async()=>new Response('{}'),ref));await assert.rejects(()=>api.verified(async()=>new Response(raw),{...ref,key:'data/other/'+sha+'.json'}));await assert.rejects(()=>api.verified(async()=>new Response(raw),{...ref,bytes:8*1024*1024}));});
test('scenario consequences require entered returns and never manufacture flow impact',()=>{const result=api.scenario({exposure:1000000,priceMove:-8,income:10000,costs:2500,days:90});assert.equal(result.net_pnl,-72500);assert.equal(result.forecast,false);assert.equal(result.tic_flow_to_return_coefficient,null);assert.throws(()=>api.scenario({exposure:1,priceMove:0,income:0,days:1}));});
