const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),api=require('../jh-funding-research.js');
const stamp='2026-09-19T13:00:00Z',at=Date.parse(stamp);
function row(id='SOFR'){return {id,label:'Dated SOFR',unit:'Percent',value:0,value_decimal:'0',as_of:'2026-09-18',calls_eligible:false,sizing_eligible:false,execution_eligible:false,frequency:'D',layer:'us_core',history:null,quality:{status:'fresh',acquired_at:stamp,observation_date:'2026-09-18',max_acquisition_age_hours:26,max_observation_age_days:5},statistics:{prior_n:0,requested_prior:252,z:null,percentile:null,status:'insufficient_comparable_history'},changes:{}};}
function packet(){return {contract:api.CONTRACT,generated_at:stamp,call:null,calls_eligible:false,sizing_eligible:false,execution_eligible:false,portfolio_action:'WAIT',plumbing_health:null,measurements:{SOFR:row()},comparisons:{},errors:{},quality:{},missing_capabilities:{},replay:{manifest_key:api.PREFIX+'runs/'+'a'.repeat(64)+'.json'}};}
test('native zero and exact original amount render without crisis or sizing authority',()=>{const p=packet();api.boundary(p);assert.match(api.detail(p,'SOFR',at,false),/<strong>0 Percent/);p.sizing_eligible=true;assert.throws(()=>api.boundary(p),/contract/);});
test('source acquisition and observation expiry cannot be cured by a page timestamp',()=>{const r=row();assert.equal(api.current(r,at),true);assert.equal(api.current(r,at+27*3600000),false);assert.equal(api.current(r,at+27*3600000,true),true);r.quality.observation_date='2026-09-01';assert.equal(api.status(r,at),'stale_observation');r.quality.status='historical_final';assert.equal(api.current(r,at,true),false);});
test('expired comparison is withheld from current board but original remains inspectable',()=>{const p=packet();p.comparisons.x={...row('x'),unit:'basis_points',value:2,value_decimal:'2',limitation:'Mixed tenor; not OIS'};const html=api.summary(p,at+27*3600000,false).board;assert.match(html,/— basis_points/);assert.match(html,/expired source/);assert.match(api.detail(p,'x',at+27*3600000,false),/<strong>2 basis_points/);});
test('exact history table preserves nulls and all original references',()=>{const h={columns:['date','value_decimal','row_index','status'],rows:Array.from({length:105},(_,i)=>[new Date(Date.UTC(2026,0,1)+i*86400000).toISOString().slice(0,10),i?'0':null,i,i?'observed':'missing'])};const r=api.history(h,9);assert.equal(r.page,2);assert.equal(r.count,105);assert.match(r.html,/2026-01-01/);assert.match(r.html,/missing/);assert.match(r.html,/—/);});
test('chart uses true dates, keeps negative values, and breaks daily gaps and missing values',()=>{const h={id:'spread',unit:'basis_points',frequency:'D',columns:['date','value_decimal','row_index','status'],rows:[['2026-09-01','-2',0,'observed'],['2026-09-02','0',1,'observed'],['2026-09-18','3',2,'observed']]};let path=api.chart(h).match(/<path d="([^"]*)"/)[1];assert.equal((path.match(/M/g)||[]).length,2);assert.match(api.chart(h),/-2/);h.rows[1][1]=null;path=api.chart(h).match(/<path d="([^"]*)"/)[1];assert.equal((path.match(/L/g)||[]).length,0);});
test('scenario uses explicit conventions, signs and zero; no exposure or shock defaults',()=>{assert.equal(api.scenario(1000000,100,90,360).incremental_usd,2500);assert.equal(api.scenario(1000000,-100,365,365).incremental_usd,-10000);assert.equal(api.scenario(0,0,1,360).incremental_usd,0);for(const args of [[null,100,90,360],[1000,NaN,90,360],[1000,100,1.5,360],[1000,100,90,0],[-1,100,90,360]])assert.throws(()=>api.scenario(...args));assert.equal(api.scenario(100,2,3,360).position_size,null);});
test('rendered original labels are escaped and paths stay inside public data',()=>{const p=packet();p.measurements.SOFR.label='<script>attack()</script>';const html=api.detail(p,'SOFR',at,false);assert.match(html,/&lt;script&gt;/);assert.ok(!html.includes('<script>'));assert.equal(api.path('data/../../secret'),null);assert.equal(api.path('https://untrusted'),null);});
test('retained output must match its immutable manifest bytes and identity',async()=>{const p=packet();delete p.replay;const output=new TextEncoder().encode(JSON.stringify(p)),sha=await api.sha(output),m={contract:'funding-original-replay.v1',generated_at:stamp,output_sha256:sha,output:{key:api.PREFIX+'outputs/'+sha+'.json',sha256:sha,bytes:output.length}},raw=new TextEncoder().encode(JSON.stringify(m)),id=await api.sha(raw),files={['/'+api.PREFIX+'runs/'+id+'.json']:raw,['/'+m.output.key]:output};const fetcher=async key=>new Response(files[key],{status:files[key]?200:404});assert.equal((await api.loadSnapshot(id,fetcher)).contract,api.CONTRACT);files['/'+m.output.key]=new TextEncoder().encode('{}');await assert.rejects(api.loadSnapshot(id,fetcher),/differs/);});
test('on-demand history verifies hash, row count, series, dates and endpoints',async()=>{const r=row(),h={contract:'funding-history.v1',id:r.id,unit:r.unit,frequency:'D',columns:['date','value_decimal','row_index','status'],rows:[['2026-09-18','0',0,'observed']]},raw=new TextEncoder().encode(JSON.stringify(h)),sha=await api.sha(raw);r.history={key:api.PREFIX+'histories/'+sha+'.json',sha256:sha,bytes:raw.length,observations:1,first:'2026-09-18',last:'2026-09-18'};assert.deepEqual(await api.loadHistory(r,async()=>new Response(raw)),h);r.id='OTHER';await assert.rejects(api.loadHistory(r,async()=>new Response(raw)),/contract/);assert.equal(await api.loadHistory(row(),async()=>{throw Error('must not fetch')}),null);});
test('page pins evidence, ignores stale selection responses, and has no mutable AI sidecar',()=>{const html=fs.readFileSync(require.resolve('../eurodollar.html'),'utf8'),js=fs.readFileSync(require.resolve('../jh-funding-page.js'),'utf8');assert.match(html,/jh-funding-research.js/);for(const forbidden of ['jh-page-ai','jh-enhance','jh-pd-fails-strip','s3.amazonaws.com'])assert.ok(!html.includes(forbidden));assert.match(js,/ticket!==request/);assert.match(js,/Current pointer differs/);assert.match(js,/setInterval\(\(\)=>render\(\),60000\)/);assert.match(html,/No account positions are read/);});
