const test=require('node:test'),assert=require('node:assert/strict'),api=require('../jh-holdings-research.js');
const permission={call:null,calls_eligible:false,sizing_eligible:false,execution_eligible:false,additional_independent_votes:0};
function doc(){const id='1'.repeat(64),identity={cusip:'191216100',class:'COM',quantity_type:'SH',put_call:null},position={identity,issuer_names:['COCA COLA CO'],reported_quantity:'400000000',row_ids:[]};return {contract:'holdings-native-fund.v1',fund:'BERKSHIRE',official_name:'BERKSHIRE',cik:'0001067983',current_holdings_period:'2026-06-30',prior_holdings_period:'2026-03-31',periods:{'2026-06-30':{positions:{[id]:{...position,reported_value_usd:'32508000000'}}},'2026-03-31':{positions:{[id]:{...position,reported_value_usd:'30420000000'}}}},comparison:{rows:[{position_id:id,identity,status:'reported_quantity_unchanged',reported_quantity_change:'0',reported_value_change_usd:'2088000000'}]},...permission};}
test('large exact decimals are not rounded through JavaScript numbers',()=>{assert.equal(api.exact('999999999999999999999999999999.123456789012'),'999,999,999,999,999,999,999,999,999,999.123456789012');assert.equal(api.exact(null),'Unavailable');assert.equal(api.exact('0'),'0');assert.throws(()=>api.exact(0));});
test('unchanged quantities remain distinct from positive market-value change',()=>{const result=api.positions(doc(),'191216100');assert.equal(result.count,1);assert.match(result.html,/Reported quantity unchanged/);assert.match(result.html,/2,088,000,000/);assert.doesNotMatch(result.html,/Bought|New purchase/);assert.equal(api.positions(doc(),'','reported_quantity_increased').count,0);});
test('search and issuer markup cannot inject HTML',()=>{const d=doc(),id=d.comparison.rows[0].position_id;d.periods[d.current_holdings_period].positions[id].issuer_names=['<img src=x onerror=alert(1)>'];const result=api.positions(d,'<img');assert.equal(result.count,1);assert.match(result.html,/&lt;img/);assert.doesNotMatch(result.html,/<img/);});
test('all securities available by pagination without default top-list truncation',()=>{const d=doc(),template=d.comparison.rows[0];d.comparison.rows=Array.from({length:81},(_,i)=>({...template,position_id:String(i).padStart(64,'0')}));for(const row of d.comparison.rows)d.periods[d.current_holdings_period].positions[row.position_id]={issuer_names:['TEST'],reported_quantity:'1',reported_value_usd:'1'};const result=api.positions(d,'','',2);assert.equal(result.count,81);assert.equal(result.pages,3);assert.equal((result.html.match(/data-evidence=/g)||[]).length,1);assert.equal(api.positions(d,'','',99).page,2);});
test('a notice does not imply a new holdings table',()=>{const d=doc();d.latest_submission={form:'13F-NT',period_of_report:'2026-09-30'};assert.match(api.summary(d),/latest submission is a notice/);assert.match(api.summary(d),/last acquired holdings period remains 2026-06-30/);});
test('stale source clock is not hidden by fresh compilation',()=>{const p={source_generated_at:'2026-09-10T00:00:00Z',generated_at:'2026-09-19T23:00:00Z'};assert.equal(api.status(p,Date.parse('2026-09-19T23:00:00Z')),'Source check expired');assert.equal(api.status(p,Date.now(),true),'Historical source snapshot');});
test('permission and fund identity mismatches fail closed',()=>{const d=doc();assert.equal(api.fund(d,'BERKSHIRE'),d);assert.throws(()=>api.fund({...d,calls_eligible:true},'BERKSHIRE'));assert.throws(()=>api.fund(d,'CITADEL'));assert.throws(()=>api.boundary({contract:api.CONTRACT,funds:{},...permission,sizing_eligible:true}));});
test('unbound native row cannot be rendered as evidence',()=>{const d=doc(),id=d.comparison.rows[0].position_id;d.filing_summaries={};d.periods[d.current_holdings_period].positions[id].row_ids=['0000000001-26-000001:'+('a'.repeat(64))+':1'];assert.throws(()=>api.evidence(d,id),/binding differs/);});
test('artifact hash and length verified before rendering',async()=>{global.crypto=require('node:crypto').webcrypto;const raw=Buffer.from(JSON.stringify(doc())),sha=require('node:crypto').createHash('sha256').update(raw).digest('hex'),ref={key:api.PREFIX+'funds/'+sha+'.json',sha256:sha,bytes:raw.length};assert.equal((await api.verified(async()=>new Response(raw),ref)).fund,'BERKSHIRE');await assert.rejects(()=>api.verified(async()=>new Response(Buffer.concat([raw,Buffer.from(' ')])),ref),/hash differs/);await assert.rejects(()=>api.verified(async()=>new Response(raw),{...ref,key:'data/private.json'}),/identity differs/);});
