const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs');
const ui=require('../jh-khalid-provider-flow.js');
const now=Date.parse('2026-09-30T19:15:00Z');
function packet(){return {contract:'khalid-provider-flow-evidence.v1',informational_only:true,independent_investment_votes:0,calls_eligible:false,sizing_eligible:false,execution_eligible:false,forecast_qualified:false,status:'partial',source_generated_at:'2026-09-29T22:01:00Z',generated_at:'2026-09-29T22:30:00Z',source_valid_until:'2026-10-01T00:00:00Z',funds:[{ticker:'XLU',category:'sector',subcategory:'utilities',source_acquired_at:'2026-09-29T22:00:00Z',source_valid_until:'2026-10-01T00:00:00Z',effective_date:'2026-09-28',processed_date:'2026-09-28',windows:{'1':{status:'available',flow_usd_decimal:'0',available_observations:1,start_date:'2026-09-28',end_date:'2026-09-28'},'5':{status:'unavailable',flow_usd_decimal:null,available_observations:4,reasons:['incomplete_window']}}}],baskets:[{name:'Configured basket',windows:{'5':{status:'partial',flow_usd_decimal:null,observed_subset_flow_usd_decimal:'12.50',included_count:1,required_count:2,reasons:['partial_configured_basket'],excluded:['SMH']}}}]};}
test('zero stays a reported measurement while null is unavailable',()=>{assert.equal(ui.view(packet(),'1','',now).funds[0].amount,'$0.00');assert.equal(ui.view(packet(),'5','',now).funds[0].amount,'Unavailable');});
test('partial groups explicitly retain subset label and missing members',()=>{const r=ui.view(packet(),'5','',now).baskets[0];assert.equal(r.amount,'$12.50 (partial subset)');assert.equal(r.coverage,'1/2');assert.equal(r.excluded,'SMH');});
test('old payload, future compilation and source expiry show no amounts',()=>{assert.equal(ui.view(undefined,'5','',now).funds.length,0);for(const [field,value] of [['generated_at','2026-10-02T00:00:00Z'],['source_valid_until','2026-09-30T18:00:00Z'],['calls_eligible',true]]){const p=packet();p[field]=value;assert.equal(ui.view(p,'5','',now).funds.length,0);}});
test('expired fund, numeric malformed values and future acquisition cannot render as flow',()=>{for(const x of [null,0,false,'NaN','Infinity','1e6','',{},[]]){const p=packet();p.funds[0].windows['1'].flow_usd_decimal=x;assert.equal(ui.view(p,'1','',now).funds[0].amount,'Unavailable');}const p=packet();p.funds[0].source_acquired_at='2027-01-01T00:00:00Z';assert.equal(ui.view(p,'1','',now).funds[0].amount,'Unavailable');});
test('filters and reporting-observation selector do not mutate packet',()=>{const p=packet(),before=JSON.stringify(p);assert.equal(ui.view(p,'1','XLU',now).funds.length,1);assert.equal(ui.view(p,'1','SOXX',now).funds.length,0);assert.throws(()=>ui.view(p,'month','',now));assert.equal(JSON.stringify(p),before);});
test('UI uses text nodes, bounded references and additive host without changing decision logic',()=>{const js=fs.readFileSync('jh-khalid-provider-flow.js','utf8'),html=fs.readFileSync('khalid.html','utf8');assert.doesNotMatch(js,/innerHTML\s*=|fetch\(/);assert.match(html,/id="provider-flow-research"/);assert.match(js,/partial subset/);assert.match(js,/setInterval\(update,60000\)/);});
