const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const v=require('../jh-macro-transport.js'),now=Date.parse('2026-09-28T16:00:00Z');
const fixture=name=>JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/'+name+'-calendar-browser.json'),'utf8'));
const legacy=kind=>kind==='freight'?{engine_class:'physical_trade_slow_confirmation',version:'2.0.0',series:{},generated_at:'2026-09-26T11:50:00Z',verdict:'ACCELERATING',composite:99,inflections:['LONG']}:{generated_at:'2026-09-26T11:20:00Z',ports:[{id:'shanghai',name:'Shanghai',status:'DISRUPTED'}],chokepoints:[{id:'bohai',name:'Bohai',vs_baseline_pct:-50}],exporters_slowing:['China'],n_disrupted:99};
class Element{constructor(){this.textContent='';this.innerHTML='';this.children=[];}appendChild(n){this.children.push(n);return n;}replaceChildren(){this.children=[];}}
const html=()=>fs.readFileSync(path.join(__dirname,'../macro-leads.html'),'utf8');
function document(){const nodes=new Map([...html().matchAll(/id="([^"]+)"/g)].map(m=>[m[1],new Element()]));return{getElementById:id=>nodes.get(id),createElement:()=>new Element()};}
test('complete freight and shipping contexts preserve source populations without inheriting portfolio votes',()=>{
 const f=v.context('freight',fixture('freight'),now),s=v.context('shipping',fixture('portwatch'),now);assert.equal(f.native,true);assert.equal(s.native,true);assert.equal(f.authority,false);assert.equal(s.authority,false);assert.match(f.description,/839 dated observations/);assert.match(s.description,/4800 retained observations/);assert.match(s.limitation,/cannot be counted as independent confirmation/);
 for(const key of ['freight','shipping']){const p=legacy(key),before=JSON.stringify(p),c=v.context(key,p,now);assert.equal(JSON.stringify(p),before);assert.equal(c.native,false);assert.equal(c.authority,false);assert.ok(!/ACCELERATING|DISRUPTED|99/.test(c.description));assert.equal(c.overdue,true);}
});
test('future, malformed and permission-drifted inputs cannot populate macro transport context',()=>{
 for(const key of ['freight','shipping']){const p=legacy(key);p.generated_at='2027-01-01T00:00:00Z';assert.throws(()=>v.context(key,p,now));}
 const p=fixture('freight');p.calls_eligible=true;assert.throws(()=>v.context('freight',p,now));const s=fixture('portwatch');s.measurement_review.history_rows++;assert.throws(()=>v.context('shipping',s,now));assert.throws(()=>v.context('other',{},now));
});
test('independent cards inspect every original field, preserve failures, and clear obsolete callbacks',async()=>{
 const doc=document();await v.mount(doc,async key=>legacy(key),now);for(const key of ['freight','shipping']){const d=doc.getElementById('transport-'+key+'-details');d.open=true;d.ontoggle();assert.deepEqual(JSON.parse(doc.getElementById('transport-'+key+'-original').textContent),legacy(key));}
 const old=doc.getElementById('transport-shipping-details').ontoggle;await v.mount(doc,async key=>{if(key==='shipping')throw Error('HTTP 403');return fixture('freight');},now);old();assert.equal(doc.getElementById('transport-shipping-original').textContent,'Unavailable');assert.match(doc.getElementById('transport-shipping-status').textContent,/No agreement or slowdown is inferred/);assert.match(doc.getElementById('transport-freight-description').textContent,/839/);
 const delayed=[];const first=v.mount(doc,()=>new Promise(resolve=>delayed.push(resolve)),now);await v.mount(doc,async()=>{throw Error('latest failed');},now);delayed.forEach((resolve,i)=>resolve(legacy(i?'shipping':'freight')));await first;assert.match(doc.getElementById('transport-freight-status').textContent,/latest failed/);
});
test('legacy HTML receives a fully escaped copy, including keys, without mutating original data',()=>{
 const p=JSON.parse('{"note":"<img src=x onerror=alert(1)>","zero":0,"null":null,"array":[false,"&\\\"\u0027"],"<script>":"text","__proto__":{"polluted":true}}'),before=JSON.stringify(p),safe=v.legacy(p);assert.equal(JSON.stringify(p),before);assert.equal(safe.zero,0);assert.equal(safe.null,null);assert.equal(safe.array[0],false);assert.match(safe.note,/&lt;img/);assert.equal(safe['&lt;script&gt;'],'text');assert.equal(Object.getPrototypeOf(safe),Object.prototype);assert.equal({}.polluted,undefined);assert.equal(safe.__proto__.polluted,true);
});
test('the real legacy inline renderer uses defined, read-only source paths and cannot rebuild old transport votes',async()=>{
 const doc=document(),calls=[],macro={generated_at:'2026-09-26T12:20:00Z',copper_gold_silver:{copper_gold:{ratio:0,z_1y:0,note:'<img onerror=alert(1)>',asof:'2026-09-25 <img onerror=alert(1)>'},gold_silver:{ratio:80,note:'safe'}},geopolitical_risk:{gpr:1,note:'safe'},heavy_truck_sales:{saar_millions:0},freight_activity:{composite:{avg_yoy_pct:999,read:'EXPANDING'}}};
 const packets={macro,asia:{korea_exports:{yoy_pct:1,chg_3m_pct:0},taiwan_exports:{yoy_pct:2,chg_3m_pct:0}},china:{tsf:{pboc_cn:{flow_trn_cny:0,yoy_delta_trn:-10}}},geo:{top_country:'China',global_temp:99,gssi_cross:{rows:[{country:'China',state:'NEWS_LEADS',gap:99}]}},calendar:{feed_status:'ok',generated_at:'2026-09-26T11:00:00Z',upcoming:[{date:'2026-09-29',event:'<img onerror=alert(1)>',estimate:0}]}};
 const sandbox={document:doc,console,JHAsiaCalendar:require('../jh-asia-calendar.js'),JHMacroCalendar:require('../jh-macro-calendar.js'),JHGeoResearch:require('../jh-geo-review.js'),JHMacroTransport:{...v,load:async key=>{calls.push(key);return packets[key];}}};vm.createContext(sandbox);
 const scripts=[...html().matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(m=>m[1]).filter(x=>x.trim());assert.equal(scripts.length,1);vm.runInContext(scripts[0],sandbox);for(let i=0;i<8;i++)await new Promise(resolve=>setImmediate(resolve));
 assert.deepEqual([...new Set(calls)].sort(),['asia','calendar','china','geo','macro']);assert.equal(doc.getElementById('macro-complete-original').textContent,JSON.stringify(macro,null,2));assert.match(doc.getElementById('copper-gold').innerHTML,/&lt;img/);assert.ok(!doc.getElementById('copper-gold').innerHTML.includes('<img'));assert.match(doc.getElementById('next-prints').innerHTML,/&lt;img/);assert.ok(!doc.getElementById('freight').innerHTML.includes('999'));assert.ok(!doc.getElementById('asia-pulse').innerHTML.includes('cross-confirmed'));
 packets.calendar.feed_status='HTTPError: HTTP Error 429';vm.runInContext(scripts[0],sandbox);for(let i=0;i<8;i++)await new Promise(resolve=>setImmediate(resolve));assert.match(doc.getElementById('next-prints').innerHTML,/Schedule unavailable.*429/);assert.match(doc.getElementById('next-prints').innerHTML,/does not mean no releases/);
 sandbox.JHMacroTransport.load=async key=>{if(key==='macro')throw Error('failed macro refresh');return packets[key];};vm.runInContext(scripts[0],sandbox);for(let i=0;i<8;i++)await new Promise(resolve=>setImmediate(resolve));for(const id of ['copper-gold','gold-silver','rate-cut','freight'])assert.match(doc.getElementById(id).textContent,/Macro source unavailable/);
});
test('complete same-origin reads reject bad clocks, truncation, duplicates and arbitrary paths',async()=>{
 let requested;const response=raw=>{let i=0;return{ok:true,body:{getReader:()=>({read:async()=>i++?{done:true}:{done:false,value:new TextEncoder().encode(raw)},cancel:async()=>{}})}};};
 const p={generated_at:'2026-09-26T12:20:00Z',values:Array.from({length:2000},(_,i)=>i)};assert.deepEqual(await v.load('macro',{now,fetcher:async(url,options)=>{requested={url,options};return response(JSON.stringify(p));}}),p);assert.equal(requested.url,'/data/macro-leads.json?exact=1&nogen=1');assert.equal(requested.options.redirect,'error');assert.equal(requested.options.cache,'no-store');
 for(const raw of ['{"generated_at":"2027-01-01T00:00:00Z"}','{"generated_at":"2026-02-30T00:00:00Z"}','{"x":1,"x":2}','{"incomplete":','[]'])await assert.rejects(v.load('asia',{now,fetcher:async()=>response(raw)}));
 await assert.rejects(v.load('private'),/Undeclared/);await assert.rejects(v.load('china',{fetcher:async()=>({ok:false})}),/unavailable/);await assert.rejects(v.load('geo',{timeout:5,fetcher:async()=>new Promise(()=>{})}),/timed out/);
});
test('whole predecessor and all source paths remain inspectable; existing geopolitical qualification is retained',()=>{
 const raw=fs.readFileSync(path.join(__dirname,'fixtures/pre-transport-research-macro-leads.html.txt'));assert.equal(raw.length,18123);assert.equal(require('node:crypto').createHash('sha256').update(raw).digest('hex'),'9aaec05a95e1a0bfff26f97612f75e9375310f26a0c810ccf99b8347f25efa44');
 const page=html();assert.match(page,/gr=JHGeoResearch.context\(gr\)/);assert.match(page,/jh-macro-transport.js/);for(const key of ['bis-crossborder','china-liquidity'])assert.ok(page.includes('/data/'+key+'.json?exact=1&amp;nogen=1'));assert.ok(!/cross-confirmed slowdown|pw\.worst|pw\.exporters|fp\.verdict|avg_yoy_pct|PX\+|s3\.amazonaws\.com|proven scalar leads|SEMIS DEMAND HOT|EXTERNAL-DEMAND-LED/.test(page));assert.equal(Object.keys(v.PATHS).length,8);
});
