const {test} = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const html = fs.readFileSync(require('node:path').join(__dirname, '../news.html'), 'utf8');
const script = [...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)].map(m => m[1]).find(s => s.includes('const BUCKET'));
const empty = () => ({public_alert_schema:'alert-history-public.v1', alerts:[], generated_at:'2026-10-01T10:00:00Z', as_of:'2026-10-01T09:00:00Z'});
const paths = ['data/alert-history.json','data/insider-trades.json','data/earnings-tracker.json','data/macro-surprise.json','divergence/current.json','data/correlation-surface.json','data/auction-crisis.json','data/whats-changed.json'];
const companion = () => [{recent_buys:[]},{pead_signals:[]},{composite:0},{divergences:[]},{regime_breaks:[]},{composite_score:0},{changes:[]}];
async function harness(packet = empty(), other = companion()) {
  const elements = {}, requests = [], buttons = ['all','ALERT','INSIDER','EARNINGS','MACRO','DIVERGENCE','CORRELATION','AUCTION','WHATS_CHANGED'].map(filter => ({filter, attrs:{},classList:{add(){},remove(){}},setAttribute(k,v){this.attrs[k]=v;},getAttribute(){return filter;},addEventListener(_e,fn){this.click=fn;}}));
  let packets = [packet,...other], pending = null;
  const context = vm.createContext({Date,console,document:{getElementById:id => elements[id] ||= {innerHTML:'',textContent:''},querySelectorAll:() => buttons},setInterval:()=>{},fetch:async url => {
    requests.push(url);
    const index = paths.findIndex(p => url.split('?')[0].endsWith('/'+p));
    assert.ok(index >= 0, url);
    const p = packets[index];
    if(pending) await pending;
    if(p?.transport) throw Error('SYNTHETIC transport');
    return {ok:!p?.status,status:p?.status || 200,json:async()=>{if(p?.parse)throw Error('SYNTHETIC parse'); return p;}};
  }});
  vm.runInContext(script, context);
  const settle = async () => {for(let n=0; n<20 && vm.runInContext('_loading',context); n++) await new Promise(r=>setImmediate(r));assert.equal(vm.runInContext('_loading',context),false);};
  await settle();
  return {elements, requests, buttons, context, async reload(p,otherPackets=other){packets=[p,...otherPackets];await vm.runInContext('load()',context);},async overlap(p){packets=[p,...other];let release;pending=new Promise(r=>release=r);const first=vm.runInContext('load()',context);await vm.runInContext('load()',context);release();await first;pending=null;}};
}
test('guarded route and exact eight-read parity on every completed reload',async()=>{const h=await harness();assert.equal(h.requests.length,8);assert.match(h.requests[0],/^\/data\/alert-history.json\?t=/);for(let i=1;i<8;i++)assert.equal(h.requests[i].split('?')[0],'https://justhodl-dashboard-live.s3.amazonaws.com/'+paths[i]);await h.reload(empty());assert.equal(h.requests.length,16);await h.overlap(empty());assert.equal(h.requests.length,24);});
test('valid empty public feed is measured zero with explicit received empty state',async()=>{const h=await harness();assert.equal(h.elements['kpi-alerts'].textContent,0);h.buttons[1].click();assert.match(h.elements.feed.innerHTML,/No events reported in the received feed/);assert.equal(h.buttons[1].attrs['aria-pressed'],'true');assert.equal(h.buttons[0].attrs['aria-pressed'],'false');});
test('nonempty valid projection counts missing clocks without inventing now',async()=>{const p=empty();delete p.generated_at;delete p.as_of;p.alerts=[{title:'Synthetic alert',detail:'Synthetic detail'}, {title:'Dated',sent_at:'2026-10-01T08:00:00Z',severity:'HIGH'}];const h=await harness(p);assert.equal(h.elements['kpi-alerts'].textContent,2);assert.match(h.elements.feed.innerHTML,/Synthetic detail/);assert.match(h.elements.feed.innerHTML,/Sent: time unavailable/);assert.doesNotMatch(h.elements.feed.innerHTML,/just now/);assert.match(h.elements['source-status'].innerHTML,/ALERT<\/b>: Received · Source publication: Unavailable · Source observation: Unavailable/);});
test('503,404,transport,parse,wrong contract and malformed projections stay unavailable',async()=>{for(const p of [{status:503},{status:404},{transport:true},{parse:true},null,[],{}, {...empty(),public_alert_schema:'wrong'}, {...empty(),alerts:{}}, {...empty(),alerts:[null]}, {...empty(),alerts:[{title:{nested:'synthetic'}}]}, {...empty(),alerts:[{detail:['synthetic']}]}, {...empty(),alerts:[{severity:{}}]}, {...empty(),alerts:[{sent_at:0}]}]){const h=await harness(p);assert.equal(h.elements['kpi-alerts'].textContent,'Unavailable');h.buttons[1].click();assert.match(h.elements.feed.innerHTML,/Source data unavailable/);assert.doesNotMatch(h.elements.feed.innerHTML,/No events/);assert.match(h.elements['kpi-events'].textContent,/partial/);}});
test('HTTP failures are distinguished without reading or exposing their bodies',async()=>{for(const [p,label] of [[{status:503,parse:true},'Unavailable or withheld (HTTP 503; cause unverified)'],[{status:404},'Unavailable (HTTP 404)'],[{transport:true},'Unavailable (fetch failed)'],[{parse:true},'Unavailable (invalid JSON)']]){const h=await harness(p);assert.ok(h.elements['source-status'].innerHTML.includes(label));}});
test('source publication and observation remain distinct from page retrieval',async()=>{const h=await harness();assert.match(h.elements['meta-updated'].innerHTML,/<b>Page retrieved<\/b>/);assert.match(h.elements['source-status'].innerHTML,/Source publication: 2026-10-01T10:00:00.000Z · Source observation: 2026-10-01T09:00:00.000Z/);for(const value of [null,false,0,'','not-a-time',{},[]]){const p=empty();p.generated_at=p.as_of=value;p.alerts=[{sent_at:'invalid',title:'No clock'}];await h.reload(p);assert.match(h.elements['source-status'].innerHTML,/ALERT<\/b>: Received · Source publication: Unavailable · Source observation: Unavailable/);assert.match(h.elements.feed.innerHTML,/Sent: time unavailable/);}});
test('hostile strings and severity never become markup; numeric-only pills survive',async()=>{const attack='<img src=x onerror="globalThis.pwned=1">';const p=empty();p.alerts=[{title:attack,detail:attack,severity:'HIGH" onclick="x'}];const other=[{recent_buys:[{ticker:attack,name:attack,value:0}]},{pead_signals:[{ticker:attack,signal:attack,eps_surprise_pct:0,price_return_1d_pct:0}]},{composite:0,regime:attack,regime_description:attack},{divergences:[{pair:attack,residual_z:0}]},{regime_breaks:[{ticker_a:attack,ticker_b:attack,delta_30d_vs_90d:0}]},{composite_score:0,regime:attack,interpretation:attack},{changes:[{title:attack,detail:attack,severity:attack}]}];const h=await harness(p,other);assert.doesNotMatch(h.elements.feed.innerHTML,/<img|onclick=|\[object Object\]|undefined/);assert.match(h.elements.feed.innerHTML,/&lt;img/);assert.match(h.elements.feed.innerHTML,/<span class="pill">0.0%<\/span>/);assert.match(h.elements.feed.innerHTML,/\$0K/);assert.match(h.elements.feed.innerHTML,/composite: \+0.00σ/);assert.match(h.elements.feed.innerHTML,/Residual z = <span class="pill">\+0.00/);});
test('malformed companion rows are isolated and cannot discard public alerts',async()=>{const p=empty();p.alerts=[{title:'Preserved public alert'}];for(let i=0;i<7;i++){const other=companion();other[i]=[{recent_buys:[null]},{pead_signals:[null]},{composite:{nested:true}},{divergences:[null]},{regime_breaks:[null]},{composite_score:{nested:true}},{changes:[null]}][i];const h=await harness(p,other);assert.match(h.elements.feed.innerHTML,/Preserved public alert/);assert.doesNotMatch(h.elements.feed.innerHTML,/NaN|\[object Object\]|undefined/);assert.equal(h.elements['kpi-alerts'].textContent,1);}});
test('repeated failure/recovery replaces old alert rows, counts and status',async()=>{const p=empty();p.alerts=[{title:'Old synthetic row'}];const h=await harness(p);h.buttons[1].click();for(let i=0;i<3;i++){await h.reload({status:503});assert.doesNotMatch(h.elements.feed.innerHTML,/Old synthetic row/);assert.equal(h.elements['kpi-alerts'].textContent,'Unavailable');await h.reload(empty());assert.equal(h.elements['kpi-alerts'].textContent,0);assert.match(h.elements.feed.innerHTML,/No events reported/);await h.reload(p);assert.equal(h.elements['kpi-alerts'].textContent,1);assert.match(h.elements.feed.innerHTML,/Old synthetic row/);}});
test('failed complete load never shows aggregate zero',async()=>{const h=await harness({status:503},Array(7).fill({transport:true}));for(const key of ['kpi-alerts','kpi-insider','kpi-events','kpi-high'])assert.equal(h.elements[key].textContent,'Unavailable');assert.match(h.elements.feed.innerHTML,/Source data unavailable/);});
