const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),api=require('../jh-official-research.js');
const now=Date.parse('2026-09-19T18:20:00Z');
function packet(){return {contract:api.CONTRACT,generated_at:'2026-09-19T18:01:00Z',call:null,calls_eligible:false,sizing_eligible:false,execution_eligible:false,measurements:{},dollar_leg:{available:0},source_clocks:{native_archive:'2026-09-19T18:00:00Z'},calendar:{calendar_expires_at:'2026-09-25T04:00:00Z'},quality:{status:'fresh'},foreign_rrp:{latest_bn:0,latest_date:'2026-09-16',chg_13w_bn:-10.4},custody:{latest_bn:2608.821,latest_date:'2026-09-16',chg_13w_bn:-22}};}
test('official balance current claims expire while a dated pinned snapshot remains inspectable',()=>{const p=packet();assert.match(api.summary(p,now,false).cards,/<strong>0<\/strong>/);assert.match(api.summary(p,now+49*3600000,false).cards,/<strong>—<\/strong>/);assert.match(api.summary(p,now+49*3600000,true).cards,/2,608.821/);p.quality.status='partial';assert.match(api.summary(p,now,false).cards,/<strong>—<\/strong>/);p.calls_eligible=true;assert.throws(()=>api.boundary(p));});
test('custody historical zeros stay in table but outside-scope points never enter chart',()=>{const doc={contract:'official-native-history.v1',rows:[{date:'2007-06-27',value_decimal:'0',analysis_eligible:false,observation_status:'A',scope_status:'outside_documented_current_face_history',row_index:0},{date:'2007-07-04',value_decimal:'1209781',analysis_eligible:true,observation_status:'A',scope_status:'reported_coverage',row_index:1}]};assert.match(api.history(doc).html,/outside_documented_current_face_history/);const chart=api.chart(doc,0,350);assert.match(chart,/viewBox="0 0 350 240"/);assert.equal((chart.match(/<path /g)||[]).length,1);assert.ok(!chart.includes('NaN'));assert.match(api.chart({...doc,rows:[doc.rows[0]]}),/No observations/);});
test('calendar gap creates separate weekly chart paths',()=>{const doc={contract:'official-native-history.v1',rows:[['2026-09-02','1'],['2026-09-16','3']].map(([date,value_decimal])=>({date,value_decimal,analysis_eligible:true}))};assert.equal((api.chart(doc).match(/<path /g)||[]).length,2);});
test('history tables preserve zero versus missing and escape source strings',()=>{const doc={contract:'official-distribution-history.v1',rows:[{date:'<img src=x>',native_usd_million_decimal:'0',fred_usd_million_decimal:null,status:'fred_missing'}]};const html=api.history(doc).html;assert.match(html,/&lt;img/);assert.match(html,/<td>0<\/td>/);assert.match(html,/<td>—<\/td>/);assert.throws(()=>api.history({contract:'unknown',rows:[]}));});
test('explicit bond scenario computes first-order duration with no balance-driven forecast',()=>{const x={exposure:1000000,duration:6,shockBp:100,income:5000,costs:1000,days:90},v=api.scenario(x);assert.equal(v.approximate_price_pnl,-60000);assert.equal(v.approximate_net_pnl,-56000);assert.equal(v.forecast,false);assert.equal(v.balance_to_yield_coefficient,null);assert.equal(api.scenario({...x,shockBp:-100}).approximate_price_pnl,60000);assert.equal(api.scenario({...x,days:365}).approximate_price_pnl,-60000);assert.throws(()=>api.scenario({...x,costs:undefined}));assert.throws(()=>api.scenario({...x,exposure:0}));assert.throws(()=>api.scenario({...x,days:1.5}));});
test('exact selected artifact bytes and namespace are required',async()=>{const raw=Buffer.from('{"rows":[]}'),sha=crypto.createHash('sha256').update(raw).digest('hex'),ref={key:api.PREFIX+'histories/'+sha+'.json',sha256:sha,bytes:raw.length};assert.deepEqual(await api.verified(async()=>new Response(raw),ref),{rows:[]});await assert.rejects(()=>api.verified(async()=>new Response('{}'),ref));await assert.rejects(()=>api.verified(async()=>new Response(raw),{...ref,key:'data/private/'+sha+'.json'}));await assert.rejects(()=>api.verified(async()=>new Response(raw),{...ref,bytes:20*1024*1024}));});
