const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const api=require('../jh-reversal-research.js'),stamp='2026-09-19T10:00:00Z',now=Date.parse(stamp);
function row(){return {symbol:'FRED:DGS10',inventory_entry:true,name:'Treasury ten-year',date:'2026-09-18',unit:'Percent',original_provider_verified:true,measurement_eligible:true,status:'fresh',calls_eligible:false,legacy_generated_at:stamp,legacy:{last:0},measurement:{current_decimal:'0',date:'2026-09-18',period_end:'2026-09-18',unit:'Percent',frequency:'D',definition:{},seasonal_adjustment:'Not Seasonally Adjusted',acquired_at:stamp,quality:{max_age_days:10},evidence:{definition:{key:'data/evidence/definition'},observations:{key:'data/evidence/observations'}},current_row_index:0,history:[],changes:{}},technical:{change_direction:'DOWN',z_signed:3,z_absolute:3,z_n_prior:90,z_mean_decimal:'-2',z_sd_decimal:'1',latest_change:{value_decimal:'-0.1',date:'2026-09-18',baseline_date:'2026-09-17'},change_unit:'percentage_points',trend:null,range_1y:null}};}
function packet(){return {contract:api.CONTRACT,call:null,calls_eligible:false,sizing_eligible:false,execution_eligible:false,generated_at:stamp,source_generated_at:stamp,rows:[row(),{symbol:'TVC:USOIL',inventory_entry:true,name:'Legacy oil',original_provider_verified:false,legacy_generated_at:stamp,legacy:{last:0,move_z:3}}],inventory:{entries:2,legacy_generated_at:stamp},quality:{original_verified_series:1},dependency_map:{groups:[]},replay:{manifest_key:api.PREFIX+'runs/'+'a'.repeat(64)+'.json'},pd_settlement_fails:{reasons:[]}};}
test('native zero, original units and exact previous dates survive rendering',()=>{const p=packet(),html=api.inventory(p,'','verified',0,now,false).html;assert.match(html,/0<div class="dim">Percent/);assert.match(html,/-0.1 percentage_points/);assert.match(html,/2026-09-17 → 2026-09-18/);assert.match(api.detail(p.rows[0],now),/positive z does not necessarily mean the value rose/);});
test('all inventory entries remain findable without mixing legacy into verified measurements',()=>{const p=packet();assert.equal(api.filtered(p,'','all').length,2);assert.equal(api.filtered(p,'oil','legacy').length,1);assert.equal(api.filtered(p,'oil','verified').length,0);assert.match(api.detail(p.rows[1],now),/original provider response, unit and instrument equivalence have not been verified/);assert.match(api.detail(p.rows[1],now),/<td>0<\/td>/);});
test('source expiry withholds current technical readings while retaining dated original values',()=>{const p=packet(),later=now+27*3600000;assert.equal(api.usable(p.rows[0],later),false);assert.equal(api.usable(p.rows[0],later,true),true);assert.match(api.inventory(p,'','verified',0,later,false).html,/Withheld/);assert.match(api.detail(p.rows[0],later),/Source expired/);assert.match(api.detail(p.rows[0],later),/<strong>0 Percent/);});
test('hostile labels, owner-supplied HTML and evidence paths cannot execute',()=>{const p=packet();p.rows[0].name='<script>bad()</script>';p.rows[0].measurement.evidence.definition.key='javascript:bad';const html=api.detail(p.rows[0],now)+api.inventory(p,'','all',0,now).html;assert.ok(!html.includes('<script>'));assert.ok(!html.includes('href="javascript'));assert.equal(api.path('data/../private'),null);});
test('pagination bounds do not hide the legacy universe or create empty pages',()=>{const p=packet();p.rows=Array.from({length:61},(_,i)=>({...row(),symbol:'FRED:X'+i}));const v=api.inventory(p,'','all',500,now);assert.equal(v.page,2);assert.equal(v.pages,3);assert.equal(v.count,61);assert.equal((v.html.match(/data-index=/g)||[]).length,1);});
test('snapshot identity, authority, size and bytes must match',async()=>{const p=packet();delete p.replay;const output=new TextEncoder().encode(JSON.stringify(p)),sha=await api.sha(output),manifest={contract:'reversal-replay.v1',generated_at:stamp,output_sha256:sha,output:{key:api.PREFIX+'outputs/'+sha+'.json',sha256:sha,bytes:output.length}},raw=new TextEncoder().encode(JSON.stringify(manifest)),id=await api.sha(raw),files={['/'+api.PREFIX+'runs/'+id+'.json']:raw,['/'+manifest.output.key]:output};const fetcher=async key=>new Response(files[key],{status:files[key]?200:404});assert.equal((await api.loadSnapshot(id,fetcher)).contract,api.CONTRACT);files['/'+manifest.output.key]=new TextEncoder().encode('{}');await assert.rejects(api.loadSnapshot(id,fetcher),/differs/);await assert.rejects(api.loadSnapshot('a'.repeat(64),async()=>new Response(new Uint8Array(256*1024+1))),/size bound/);p.calls_eligible=true;assert.throws(()=>api.filtered(p),/authority/);});
test('page binds one immutable snapshot and refreshes expiry without independent page AI or settlement reads',()=>{const html=fs.readFileSync(require.resolve('../liquidity-reversal.html'),'utf8'),js=fs.readFileSync(require.resolve('../jh-reversal-page.js'),'utf8');assert.match(html,/jh-reversal-research.js/);assert.ok(!html.includes('jh-page-ai'));assert.ok(!html.includes('jh-pd-context'));assert.match(js,/loadSnapshot/);assert.match(js,/setInterval\(render,60000\)/);assert.match(js,/signature===last/);assert.match(js,/Current pointer differs/);});

test("unavailable trend is not labeled no change",()=>{const p=packet();assert.match(api.inventory(p,"","verified",0,now).html,/<td>Unavailable<\/td>/);assert.ok(!api.inventory(p,"","verified",0,now).html.includes("No detected sign change"));assert.throws(()=>api.filtered(p,"","made-up"),/scope/);});

test("unavailable registered additions do not inflate retained legacy membership",()=>{const p=packet();p.rows.push({symbol:"FRED:NEW",inventory_entry:false,original_provider_verified:false});assert.equal(api.filtered(p,"","legacy").length,1);assert.match(api.detail(p.rows[2],now),/Registered native source unavailable/);});

test("legacy generation time is not presented as an observation date",()=>{assert.match(api.inventory(packet(),"","legacy",0,now).html,/Observation unavailable<div class="dim">Legacy engine/);});
