const test=require('node:test'),assert=require('node:assert/strict');
const widget=require('../jh-short-position-context.js');
const flags={calls_eligible:false,sizing_eligible:false,execution_eligible:false,forecast_qualified:false};
function fixture(){return {row:{...flags,observation_freshness_verified:false,identity_verified:false,ticker:'TEST',reported_ticker_key:'TEST',source_row:'/by_ticker/TEST',short_interest_shares:100,settlement_date:'2026-09-15',latest_reported:true,days_to_cover:2,reported_days_to_cover:999,reported_reconstructed_ratio:2,days_to_cover_basis:'producer_reconstructed_ratio',reported_dtc_status:'provider_differs_from_reconstructed_ratio'},meta:{...flags,artifact:'data/short-interest-tickers.json',read_status:'parsed',context_status:'descriptive_only',source_contract:'short-interest-tickers.v1',context_contract:'short-position-consumer-context.v1',body_sha256:'a'.repeat(64),body_bytes:1000}};}
test('descriptive quantities carry settlement, unit and exact body pointer without probability claims',()=>{const {row,meta}=fixture(),v=widget.view(row,meta,'TEST'),html=widget.render(row,meta,'TEST');assert.equal(v.shares,100);assert.equal(v.ratio,2);assert.match(html,/2 volume-days/);assert.match(html,/Provider display: 999/);assert.match(html,/producer-reconciled/);assert.match(html,/2026-09-15/);assert.match(html,/does not retain an immutable original/);assert.doesNotMatch(html,/Short <b>.*%/);});
test('unsafe self-qualification, identities, pointers and body metadata withhold the whole view',()=>{for(const change of [{calls_eligible:true},{reported_ticker_key:'/TEST'},{source_row:'/by_ticker/OTHER'},{ticker:'OTHER'},{identity_verified:true}]){const {row,meta}=fixture();Object.assign(row,change);assert.equal(widget.view(row,meta,'TEST').status,'unavailable');}for(const change of [{sizing_eligible:true},{artifact:'data/other.json'},{body_bytes:0},{body_bytes:16777217},{body_bytes:true},{body_sha256:'<img>'},{source_contract:'wrong'}]){const {row,meta}=fixture();Object.assign(meta,change);assert.equal(widget.view(row,meta,'TEST').status,'unavailable');}});
test('ratio requires matching declared reconciliation and does not use a provider fallback',()=>{for(const change of [{reported_reconstructed_ratio:3},{days_to_cover_basis:'unknown'},{reported_dtc_status:'unknown'},{days_to_cover:true},{days_to_cover:NaN}]){const {row,meta}=fixture();Object.assign(row,change);assert.equal(widget.view(row,meta,'TEST').ratio,null);}const {row,meta}=fixture();row.days_to_cover=row.reported_days_to_cover=0;row.days_to_cover_basis='producer_reconciled_provider_display';row.reported_dtc_status='provider_display_floor_one';assert.equal(widget.view(row,meta,'TEST').ratio,0);});
test('tiny positive quantities do not format as measured zero and true zero survives',()=>{const {row,meta}=fixture();row.days_to_cover=row.reported_reconstructed_ratio=1e-20;let html=widget.render(row,meta,'TEST');assert.doesNotMatch(html,/>0 volume-days/);row.short_interest_shares=0;assert.match(widget.render(row,meta,'TEST'),/0 shares/);for(const value of [true,NaN,Infinity,1.5,Number.MAX_SAFE_INTEGER+1,-1]){row.short_interest_shares=value;assert.equal(widget.view(row,meta,'TEST').shares,null);}});
test('historical status and invalid calendar dates remain explicit',()=>{const {row,meta}=fixture();row.latest_reported=false;assert.match(widget.render(row,meta,'TEST'),/Explicitly historical settlement row/);for(const date of ['2026-02-30','0000-01-01',true,'<img>',null]){row.settlement_date=date;assert.equal(widget.view(row,meta,'TEST').date,null);}});
test('hostile row content never becomes executable markup or a dynamic source link',()=>{const {row,meta}=fixture();row.settlement_date='<img src=x onerror=alert(1)>';row.reported_dtc_status='<img>';const html=widget.render(row,meta,'TEST');assert.doesNotMatch(html,/<img|onerror=/);assert.match(html,/href="\/data\/short-interest-tickers.json"/);});
