const {test}=require('node:test'),assert=require('node:assert/strict'),api=require('../jh-tic-research.js');
const now=Date.parse('2026-09-19T16:00:00Z');
function packet(){return {contract:api.CONTRACT,call:null,calls_eligible:false,sizing_eligible:false,execution_eligible:false,measurements:{},data_asof:'2026-07-01',headline:{foreign_net_into_us_lt_12mo_b:0,latest_month_b:-3.74},by_asset_class:{},quality:{status:'fresh',original_archive_acquired_at:'2026-09-19T15:00:00Z',calendar_acquired_at:'2026-09-19T15:00:00Z',calendar_expires_at:'2026-10-17T04:00:00Z'}};}
test('TIC current cards expire but pinned snapshots preserve explicitly dated values',()=>{const p=packet();assert.match(api.summary(p,now,false).cards,/<strong>0<\/strong>/);assert.match(api.summary(p,now+27*3600000,false).cards,/<strong>—<\/strong>/);assert.match(api.summary(p,now+27*3600000,true).cards,/<strong>0<\/strong>/);assert.equal(api.status(p,now+27*3600000,true),'historical snapshot');p.sizing_eligible=true;assert.throws(()=>api.boundary(p));});
test('source disagreement cannot appear as current qualified measurement totals',()=>{const p=packet();p.quality.status='partial';assert.match(api.summary(p,now,false).cards,/<strong>—<\/strong>/);assert.match(api.summary(p,now,true).cards,/-3.74/);});
test('TIC original history preserves missing values, signed flows and zero',()=>{const h={kind:'native_monthly_transactions',rows:[{date:'2026-01-01',value_decimal:'0',row_index:2},{date:'2026-02-01',value_decimal:null,row_index:1},{date:'2026-03-01',value_decimal:'-3740',row_index:0}]};const t=api.historyTable(h);assert.equal(t.count,3);assert.match(t.html,/>0<\/td>/);assert.match(t.html,/>—<\/td>/);assert.match(t.html,/-3.74/);assert.match(api.chart(h),/Missing months and values break the line/);assert.equal((api.chart(h).match(/<path /g)||[]).length,2);});
test('calendar gaps break charts even when a source omitted a month',()=>{const h={kind:'native_monthly_transactions',rows:[{date:'2026-01-01',value_decimal:'0'},{date:'2026-03-01',value_decimal:'1000'}]};assert.equal((api.chart(h).match(/<path /g)||[]).length,2);assert.ok(!api.chart(h).includes('NaN'));assert.ok(!api.chart(h).includes('Infinity'));});
test('mobile chart uses its container width and aggregate history cannot inherit a selected outflow label',()=>{const p=packet();p.measurements.X={role:'us_abroad'};assert.match(api.historyTitle(p,'X','native_monthly_transactions'),/^U.S. purchases of foreign/);assert.match(api.historyTitle(p,'X','rolling_twelve_months'),/^Foreign purchases of U.S./);assert.match(api.historyTitle(p,'X','component_reconciliation'),/component reconciliation/);assert.match(api.chart({kind:'native_monthly_transactions',rows:[{date:'2026-01-01',value_decimal:'0'}]},120,350),/viewBox="0 0 350 240"/);assert.equal(api.num(false),null);assert.equal(api.num(' '),null);});
test('TIC rolling charts use already-defined billions without a second division',()=>{const h={kind:'rolling_twelve_months',rows:[{date:'2026-06-01',rolling_12mo_b:1500,totals:{total:{status:'complete'}}},{date:'2026-07-01',rolling_12mo_b:1754.38,totals:{total:{status:'complete'}}}]};assert.match(api.chart(h),/1,754.4/);assert.match(api.historyTable(h).html,/1,754.38/);});
test('scenario uses explicit same-horizon assumptions and has no TIC-to-return coefficient',()=>{const x={exposure:1000000,priceMove:-8,income:10000,costs:2500,days:90},r=api.scenario(x);assert.equal(r.price_pnl,-80000);assert.equal(r.net_pnl,-72500);assert.equal(r.return_on_exposure_pct,-7.25);assert.equal(r.forecast,false);assert.equal(r.position_size,null);assert.equal(r.tic_flow_to_return_coefficient,null);assert.equal(api.scenario({...x,priceMove:r.break_even_price_move_pct}).net_pnl,0);});
test('scenario refuses missing, negative costs, boolean values and invalid horizons',()=>{const x={exposure:1000000,priceMove:0,income:0,costs:0,days:90};for(const change of [{costs:undefined},{exposure:0},{priceMove:-101},{costs:-1},{days:1.5},{income:NaN},{priceMove:true}])assert.throws(()=>api.scenario({...x,...change}));assert.equal(api.scenario(x).net_pnl,0);});
test('retained artifact bytes, length and SHA are verified before parsing',async()=>{const body=JSON.stringify({kind:'fixture',rows:[]}),raw=new TextEncoder().encode(body),sha=require('node:crypto').createHash('sha256').update(raw).digest('hex'),ref={key:api.PREFIX+'histories/'+sha+'.json',bytes:raw.length,sha256:sha};assert.deepEqual(await api.verified(async()=>new Response(raw),ref),JSON.parse(body));await assert.rejects(()=>api.verified(async()=>new Response('{}'),ref));await assert.rejects(()=>api.verified(async()=>new Response(raw),{...ref,key:'data/another/'+sha+'.json'}));});
