const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const rail=fs.readFileSync('jh-chart-tvrail.js','utf8'), watch=fs.readFileSync('jh-chart-tvwatch.js','utf8'), engine=fs.readFileSync('jh-chart-engine.js','utf8');
function store(values={}){const data=new Map(Object.entries(values).map(([k,v])=>[k,typeof v==='string'?v:JSON.stringify(v)]));return {writes:0,getItem(k){return data.has(k)?data.get(k):null;},setItem(){this.writes++;throw Error('Synthetic quota/write failure');},removeItem(){this.writes++;throw Error('Synthetic write failure');},data};}
function migration(){const context={window:{},Set,Number};vm.runInNewContext(fs.readFileSync('jh-watchlist-store.js','utf8'),context);return {prepare:context.window.JHWatchlistPersistence.prepare};}
function helpers(){const context={window:{},Date,Number,Set,AbortController,setTimeout,clearTimeout};vm.runInNewContext(fs.readFileSync('jh-watchlist-quotes.js','utf8'),context);return {api:context.window.JHWatchlistQuotes,window:context.window};}
const M=migration(),H=helpers();H.window.jhWatchlistResolve=s=>({engine:"equity",ticker:s,yahoo:s});const rules=JSON.parse(fs.readFileSync('data/tv-symbol-resolver.json','utf8'));
const K={src:'jh_custom_watchlists',dst:'jh-chart-custom-lists',ledger:'jh-chart-pro-imported',sf:'jh_symbol_flags',df:'jh-chart-flags',fav:'jh-chart-favs',pf:'jh_favorites',fa:'jh_favs'};
const parse=(p,k)=>JSON.parse(p.after[k]);
function fixtureApply(p,storage){Object.entries(p.after).forEach(([k,v])=>storage.data.set(k,v));}
for(const symbol of ['NYSE:AAPL','NASDAQ:AAPL','LSE:AAPL','FRED:DGS10','OANDA:EURUSD','FX:GBPJPY','EURUSD','GBPJPY','USDTRY','USDBRL','USDKRW','XAUUSD','XAGUSD','ESU6','GCZ6','CME_MINI:ES1!','ES1!','TVC:GOLD','GC=F','BINANCE:BTCUSDT','COINBASE:BTCUSD','BTCUSDT','ETH-USD','ECONOMICS:USCPMI','SPX','NDX'])test('withholds unsupported identity '+symbol,()=>assert.ok(H.api.resolve(symbol,rules).reason));
test('bare ticker resolves, never namespace-stripped',()=>{assert.equal(H.api.resolve('AAPL',rules).ticker,'AAPL');assert.ok(H.api.resolve('NASDAQ:AAPL',rules).reason);});
test('existing native aliases are withheld',()=>{H.window.jhWatchlistResolve=s=>({engine:s==='DGS10'?'fred':'equity',ticker:s==='GOLD'?'GC=F':s,yahoo:s});for(const s of ['DGS10','GOLD'])assert.ok(H.api.resolve(s,rules).reason);H.window.jhWatchlistResolve=s=>({engine:"equity",ticker:s,yahoo:s});});
const now=Date.UTC(2026,9,4),rows=[{time:Date.UTC(2026,8,1)/1000,close:100},{time:Date.UTC(2026,9,3)/1000,close:110}];
const packet=(bars=rows)=>({ticker:'AAPL',span:'day',mult:1,source:'invented warehouse',bars});
test('dated daily aggregates retain both timestamps/source and uncertainty',()=>{const q=H.api.packet(packet(),'AAPL',now);assert.equal(q.last,110);assert.equal(q.chgv,10);assert.equal(q.chg,.1);assert.equal(q.previousTime,rows[0].time);assert.equal(q.completion,'unverified');});
test('one aggregate yields close but unavailable delta',()=>{const q=H.api.packet(packet([rows[0]]),'AAPL',now);assert.equal(q.last,100);assert.equal(q.chg,null);assert.equal(q.chgv,null);});
for(const close of [null,true,false,'', '110',Infinity,NaN])test('rejects unmeasured close '+String(close),()=>{assert.ok(H.api.packet(packet([{...rows[0],close}]),'AAPL',now).reason);});
for(const bars of [rows.slice().reverse(),[{...rows[0],time:null}],rows.map(b=>({...b,time:rows[0].time})),[{...rows[0],time:now/1000+1}],[{time:Number.MAX_SAFE_INTEGER,close:1}]])test('rejects invalid chronological packet '+JSON.stringify(bars),()=>assert.ok(H.api.packet(packet(bars),'AAPL',now).reason));
test('overflow is withheld; zero baseline has no invented delta',()=>{assert.ok(H.api.packet(packet([{...rows[0],close:-Number.MAX_VALUE},{...rows[1],close:Number.MAX_VALUE}]),'AAPL',now).reason);assert.equal(H.api.packet(packet([{...rows[0],close:0},rows[1]]),'AAPL',now).chg,null);});
for(const change of [{ticker:null},{ticker:'MSFT'},{source:''},{span:'minute'},{mult:2},{bars:[]}])test('rejects missing/conflicting evidence '+JSON.stringify(change),()=>assert.ok(H.api.packet({...packet(),...change},'AAPL',now).reason));
test('duplicate names remain separate source IDs and stable order; no destination writes',()=>{const st=store({[K.src]:{a:{name:'Same',tickers:['NASDAQ:AAPL']},b:{name:'Same',tickers:['FRED:DGS10']}},[K.dst]:[{id:'mine',name:'Same',symbols:['MSFT']}]});const p=M.prepare(st),d=parse(p,K.dst);assert.deepEqual(d.map(l=>l.id),['mine','chart-pro:a','chart-pro:b']);assert.deepEqual(d.map(l=>l.symbols),[['MSFT'],['NASDAQ:AAPL'],['FRED:DGS10']]);assert.equal(st.writes,0);assert.equal(st.getItem(K.ledger),null);});
test('repeated preview, rename and source changes preserve user destination intent',()=>{const st=store({[K.src]:{a:{name:'Original',tickers:['AAPL','MSFT']}}});const p=M.prepare(st);fixtureApply(p,st);const d=JSON.parse(st.getItem(K.dst));d[0].name='User rename';d[0].symbols=['MSFT'];st.data.set(K.dst,JSON.stringify(d));st.data.set(K.src,JSON.stringify({a:{name:'Source rename',tickers:['AAPL','MSFT','NVDA']}}));const next=M.prepare(st);assert.deepEqual(parse(next,K.dst)[0].symbols,['MSFT','NVDA']);assert.equal(parse(next,K.dst)[0].name,'User rename');fixtureApply(next,st);assert.equal(M.prepare(st).changes,0);assert.equal(st.writes,0);});
test('deleted destination is tombstoned rather than recreated',()=>{const st=store({[K.src]:{a:{name:'Source',tickers:['AAPL']}}});fixtureApply(M.prepare(st),st);st.data.set(K.dst,'[]');const p=M.prepare(st);assert.deepEqual(parse(p,K.dst),[]);assert.equal(parse(p,K.ledger).lists.a.deleted,true);assert.equal(st.writes,0);});
test('source deletion preserves saved destination',()=>{const st=store({[K.src]:{a:{name:'Source',tickers:['AAPL']}}});fixtureApply(M.prepare(st),st);st.data.set(K.src,'{}');assert.equal(parse(M.prepare(st),K.dst).length,1);});
test('favorite/flag removal is never reimported',()=>{const st=store({[K.sf]:{AAPL:'red'},[K.pf]:{AAPL:true}});fixtureApply(M.prepare(st),st);st.data.set(K.df,'{}');st.data.set(K.fav,'[]');const p=M.prepare(st);assert.deepEqual(parse(p,K.df),{});assert.deepEqual(parse(p,K.fav),[]);assert.equal(st.writes,0);});
for(const flag of [null,false,'','unknown','constructor','toString'])test('invalid source flag cannot consume a corrected identity '+String(flag),()=>{const st=store({[K.sf]:{AAPL:flag}});assert.throws(()=>M.prepare(st),/Unsupported Chart Pro flag/);assert.equal(st.getItem(K.ledger),null);assert.equal(st.writes,0);st.data.set(K.sf,'{"AAPL":"red"}');assert.deepEqual(parse(M.prepare(st),K.df),{AAPL:'#f23645'});});
for(const favorite of [null,1,'true',{}])test('invalid source favorite retained '+JSON.stringify(favorite),()=>{const st=store({[K.pf]:{AAPL:favorite}});assert.throws(()=>M.prepare(st),/Malformed Chart Pro favorite/);assert.equal(st.getItem(K.ledger),null);assert.equal(st.writes,0);});
test('empty source identities never enter an import ledger',()=>{for(const key of [K.sf,K.pf]){const st=store({[key]:{' ':key===K.sf?'red':true}});assert.throws(()=>M.prepare(st),/original retained/);assert.equal(st.writes,0);}});
test('legacy ambiguous name mapping cannot overwrite stores',()=>{const st=store({[K.src]:{a:{name:'Same',tickers:['AAPL']}},[K.ledger]:{lists:{a:['AAPL']}}});assert.throws(()=>M.prepare(st),/source ID/);assert.equal(st.writes,0);});
test('legacy ID mapping adopts only explicit source-owned original; removed flags/favorites remain removed',()=>{const st=store({[K.src]:{a:{name:'Same',tickers:['AAPL']}},[K.dst]:[{id:'a',name:'Renamed',from:'chart-pro',symbols:[]}],[K.ledger]:{lists:{a:['AAPL']}},[K.sf]:{AAPL:'red'},[K.pf]:{AAPL:true}});const p=M.prepare(st);assert.equal(parse(p,K.dst)[0].name,'Renamed');assert.deepEqual(parse(p,K.dst)[0].symbols,[]);assert.deepEqual(parse(p,K.df),{});assert.deepEqual(parse(p,K.fav),[]);});
for(const [key,value] of [[K.src,'{'],[K.dst,'{'],[K.dst,'{}'],[K.dst,'null'],[K.df,'[]'],[K.fav,'{}'],[K.ledger,'null'],[K.ledger,{version:2,lists:{stale:{id:42}},favorites:[],flags:[]}],[K.dst,[{id:'a',name:'A',symbols:[]},{id:'a',name:'B',symbols:[]}]]])test('malformed original retained '+key+JSON.stringify(value),()=>{const st=store({[key]:value});const before=st.getItem(key);assert.throws(()=>M.prepare(st));assert.equal(st.getItem(key),before);assert.equal(st.writes,0);});
test('concurrent edit while reading preview is rejected without writes',()=>{const st=store();let calls=0;const get=st.getItem.bind(st);st.getItem=k=>{if(++calls===9)st.data.set(K.dst,'[{"id":"newer","name":"Concurrent","symbols":[]}]');return get(k);};assert.throws(()=>M.prepare(st),/Concurrent/);assert.equal(st.writes,0);assert.ok(st.getItem(K.dst).includes('newer'));});
test('read-only preview does not write any legacy destination or ledger',()=>{const st=store({[K.src]:{a:{name:'Source',tickers:['AAPL']}}});assert.ok(M.prepare(st));assert.equal(st.writes,0);assert.deepEqual(Object.keys(M),['prepare']);});
test('native writes await canonical transaction rather than overwrite legacy storage',()=>{const a=engine.indexOf('  async function saveWatchlist('),b=engine.indexOf('  function bindWatchOps(',a),body=engine.slice(a,b);assert.ok(body.includes('await window.jhWatchlistStore.save(k,v,revision)'));assert.ok(!body.includes('localStorage.setItem'));for(const call of engine.matchAll(/(?<!function )saveWatchlist\([^;]+/g)){if(call[0].startsWith('saveWatchlist(k,v,revision){'))continue;assert.ok(engine.slice(Math.max(0,call.index-6),call.index).includes('await'),call[0]);}});

test('every current-renderer persistence primitive requires a captured draft and one batch',()=>{assert.ok(watch.includes('await window.jhWatchlistStore.saveBatch(draft.patch,draft.revision)'));assert.ok(watch.includes('if(!actionDraft)throw Error("Watchlist mutation requires a captured user action")'));assert.ok(watch.includes('actionDraft.model[k]=clone(v)'));assert.ok(!watch.includes('localStorage.setItem(UI_KEY'));});
test('current renderer owns raw native Search/More Add target',()=>{assert.ok(engine.includes('if(window.jhWatchlistRendererAdd)return window.jhWatchlistRendererAdd(s)'));assert.ok(watch.includes('window.jhWatchlistRendererAdd=intent('));});
test('current UI source preserved under exact inverse fixture',()=>{const P=require('./helpers/watchlist-source-preservation.cjs');for(const file of Object.keys(P.manifest)){const raw=fs.readFileSync(file,'utf8');if(file==='jh-chart-engine.js')P.normalize(raw);else P.normalizeHelper(raw,file);}});

test('prototype source IDs and raw flag identities survive repeated migration review',()=>{const src=JSON.parse('{"__proto__":{"name":"Saved","tickers":["constructor"]}}');const st=store({[K.src]:src,[K.sf]:JSON.parse('{"__proto__":"red"}')});const first=M.prepare(st);assert.equal(Object.hasOwn(parse(first,K.ledger).lists,'__proto__'),true);assert.equal(Object.hasOwn(parse(first,K.df),'__proto__'),true);fixtureApply(first,st);assert.equal(M.prepare(st).changes,0);});
test('source-preservation negative control rejects an unrelated renderer note edit',()=>{const P=require('./helpers/watchlist-source-preservation.cjs');assert.throws(()=>P.normalizeHelper(watch.replace('var NOTES_KEY = "jh-tv-notes"','var NOTES_KEY = "changed-private-notes"'),'jh-chart-tvwatch.js'),/jh-chart-tvwatch\.js exact watchlist candidate/);});
test('body-inclusive request deadline frees even an abort-ignoring JSON read',async()=>{const H=helpers();let release;const fetcher=async()=>({ok:true,json:()=>new Promise(r=>{release=r;})});await assert.rejects(H.api.request('fixture',fetcher,10),/request timeout/);release(packet());});
