// Actual source functions and native Enter handler; no network, application storage or map feed.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const read=f=>fs.readFileSync(f,'utf8'),watch=read('jh-chart-tvwatch.js'),engine=read('jh-chart-engine.js'),catalog=read('jh-chart-catalog.js');
const acorn={exports:{}};Function('exports','module',process.binding('natives')['internal/deps/acorn/acorn/dist/acorn'])(acorn.exports,acorn);
const trees=new Map();function nodes(src){if(trees.has(src))return trees.get(src);const out=[],stack=[acorn.exports.parse(src,{ecmaVersion:'latest'})];while(stack.length){const n=stack.pop();if(!n||typeof n!=='object')continue;if(n.type)out.push(n);for(const v of Object.values(n)){if(Array.isArray(v))stack.push(...v);else if(v&&typeof v==='object')stack.push(v);}}trees.set(src,out);return out;}
function fn(src,name){const a=nodes(src).filter(n=>n.type==='FunctionDeclaration'&&n.id.name===name);assert.equal(a.length,1,name);return src.slice(a[0].start,a[0].end);}
function variable(src,name){const n=nodes(src).find(n=>n.type==='VariableDeclarator'&&n.id.name===name);assert.ok(n,name);return 'var '+src.slice(n.start,n.end)+';';}
const assignments=nodes(engine).filter(n=>n.type==='AssignmentExpression'&&n.left.type==='MemberExpression'&&n.left.object.name==='q'&&n.left.property.name==='onkeydown'&&n.right.type==='FunctionExpression'&&engine.slice(n.right.start,n.right.end).includes('var s=q.value.trim().toUpperCase(); if(TABS.indexOf(s)<0)'));assert.equal(assignments.length,1);const nativeQ=engine.slice(assignments[0].right.start,assignments[0].right.end);
let previous=watch;const changes=JSON.parse(read('tests/fixtures/watchlist-correctness/source-transition.json'))['jh-chart-tvwatch.js'].edits.filter(e=>e.scope==='watchlist-identity-guard-1');assert.ok(changes.length);for(const e of changes.slice().reverse()){assert.equal(previous.slice(e.start,e.end),e.after);previous=previous.slice(0,e.start)+e.before+previous.slice(e.end);}
function harness(map=null,old=false){
 const c={window:{},Set,Number,Date,AbortController,setTimeout,clearTimeout,painted:[],toasts:[],loads:[],symMap:map,symMapReady:1,chartSelection:null,TABS:[],active:'INITIAL',filter:''};c.q={value:'',dispatchEvent(e){this.onkeydown(e);}};c.document={getElementById(id){return id==='q'?c.q:null;}};c.KeyboardEvent=function(_,o){return o;};c.paintCard=s=>c.painted.push(s);c.toast=s=>c.toasts.push(s);c.loadSymMap=()=>Promise.resolve();c.loadDraw=c.renderTabs=c.renderList=()=>{};c.load=()=>c.loads.push(c.active);c.activeSym=()=>c.active;c.lookupSym=()=>'';
 vm.createContext(c);vm.runInContext(fn(catalog,'H')+['EXCH','SERIES_PROV','CURATED'].map(n=>variable(catalog,n)).join('\n')+fn(catalog,'isWarehouse')+fn(catalog,'chartId'),c);c.window.JHChartCatalog={isWarehouse:c.isWarehouse,chartId:c.chartId};
 vm.runInContext(['resolveSym','yahooSym','bare','observationId'].map(n=>fn(engine,n)).join('\n'),c);vm.runInContext(fn(engine,'normQ')+fn(engine,'classifySym')+variable(engine,'SEARCH_ALIASES'),c);const exported=nodes(engine).find(n=>n.type==='AssignmentExpression'&&n.left.type==='MemberExpression'&&n.left.property.name==='jhWatchlistResolve');assert.ok(exported);vm.runInContext(engine.slice(exported.start,exported.end),c);c.q.onkeydown=vm.runInContext('('+nativeQ+')',c);
 vm.runInContext((old?[fn(previous,'fredId'),fn(previous,'chartSymbol'),fn(previous,'openSym')]:['chartCandidate','chartRoute','openSym'].map(n=>fn(watch,n))).join('\n'),c);return c;
}
const counterexamples=[
 ['NASDAQ:AAPL','AAPL',null],['NYSE:AAPL','AAPL',null],['IEX:AAPL','AAPL',null],['BINANCE:BTCUSDT','BTC-USD',null],['BINANCE:BTCUSDC','BTC-USD',null],['COINBASE:BTCUSD','BTC-USD',null],['BINANCE:ETHBTC','ETHBTC-USD',null],['TVC:GOLD','GC=F',null],['TVC:US10Y','FRED:DGS10',null],['OANDA:EURUSD','EURUSD=X',null],['CME_MINI:ES1!','ES=F',null],['FRED:DGS10','FRED:DGS10','FRED:DGS10'],['AAPL','AAPL','AAPL'],['worldbank:NY.GDP.MKTP.CD:USA',null,'worldbank:NY.GDP.MKTP.CD:USA'],['FRED:BSCICP03DEUM665S','FRED:BSCICP03DEM665S','FRED:BSCICP03DEUM665S'],['ECONOMICS:USDXY','FRED:DTWEXBGS',null],
 ['NASDAQ:AAPL','MSFT',null,{'NASDAQ:AAPL':{source:'MARKET',id:'MSFT'}}],['FRED:DGS10','FRED:DGS2','FRED:DGS10',{'FRED:DGS10':{source:'FRED',id:'DGS2'}}],['WB:USA|NY.GDP.MKTP.CD','worldbank:NY.GDP.MKTP.CD:USA',null,{'WB:USA|NY.GDP.MKTP.CD':{source:'WORLDBANK',id:'USA|NY.GDP.MKTP.CD'}}]
];
for(const [id,before,target,map] of counterexamples)test('identity counterexample: '+id+' / '+before,()=>{const old=harness(map,true),c=harness(map);old.openSym(id);assert.equal(old.loads[0]||null,before?.toUpperCase()||null);const r=c.chartRoute(id);assert.equal(r.requested,id);assert.equal(r.target,target);c.openSym(id);assert.deepEqual(c.loads,target?[id.toUpperCase()]:[]);assert.equal(c.active,target?id.toUpperCase():'INITIAL');if(!target){assert.match(c.chartSelection.reason,/unverified/);assert.equal(c.q.value,'');}assert.deepEqual(c.painted,[id]);});
for(const id of ['NASDAQ:AAPL','NYSE:AAPL','BINANCE:BTCUSDT','TVC:GOLD','FRED:DGS10','worldbank:NY.GDP.MKTP.CD:USA'])test('original quote guard remains withheld: '+id,()=>{const c=harness();vm.runInContext(read('jh-watchlist-quotes.js'),c);assert.ok(c.window.JHWatchlistQuotes.resolve(id,JSON.parse(read('data/tv-symbol-resolver.json'))).reason);});
for(const id of ['DGS2','DGS5','DGS10','DGS30','T10Y2Y'])test('bounded native prefix alias retains original: '+id,()=>{const c=harness();assert.equal(c.observationId(id),true);assert.equal(c.resolveSym(id).raw,'FRED:'+id);assert.equal(c.chartId(id),'FRED:'+id);assert.equal(c.window.jhWatchlistResolve(id).engine,'unqualified-economic');c.openSym(id);assert.equal(c.chartSelection.relation,'provider-prefix');assert.equal(c.chartSelection.candidate,'FRED:'+id);assert.deepEqual(c.loads,[id]);});
for(const id of ['US10Y','US10','US10Y2Y','DFF','SOFR','CPIAUCSL','GOLD','SPX','BTC','BTCUSD','BTCUSDT','USDJPY','FRED:','FRED:DGS10:EXTRA','worldbank:NY.GDP.MKTP.CD','###Section','A APL',null,true,42])test('no guessed identity handoff: '+String(id),()=>{const c=harness();c.openSym(id);assert.deepEqual(c.loads,[]);assert.equal(c.chartSelection.target,null);});
for(const id of ['BTC-USD','GC=F','EURUSD=X','^VIX','ecb:EXR.D.USD.EUR.SP00.A','FRED:SOFR','worldbank:NY.GDP.MKTP.CD:DEU'])test('unchanged explicit identifier is not blanket-blocked: '+id,()=>{const c=harness();c.openSym(id);assert.deepEqual(c.loads,[id.toUpperCase()]);assert.equal(c.chartSelection.requested,id);});
test('a map cannot override an independently unchanged bare ID',()=>{const c=harness({AAPL:{source:'MARKET',id:'MSFT'}});c.openSym('AAPL');assert.deepEqual(c.loads,['AAPL']);assert.equal(c.chartSelection.candidate,'MSFT');});
test('catalog disagreement refuses a prefix alias',()=>{const c=harness();c.window.JHChartCatalog.chartId=()=> 'FRED:DGS2';c.openSym('DGS10');assert.deepEqual(c.loads,[]);});
test('resolver exception and unavailable native input fail closed',()=>{for(const mode of ['throw','missing','handler']){const c=harness();if(mode==='throw')c.window.jhWatchlistResolve=()=>{throw Error('fixture');};if(mode==='missing')c.document.getElementById=()=>null;if(mode==='handler')c.q.onkeydown=null;c.openSym('AAPL');assert.deepEqual(c.loads,[]);assert.equal(c.chartSelection.target,null);assert.equal(c.q.value,'');}});
test('pending map never queues an old click for replay',()=>{const c=harness();c.symMapReady=0;c.loadSymMap=()=>{throw Error('Must not wait for candidate map');};c.openSym('NASDAQ:AAPL');c.openSym('FRED:DGS10');assert.deepEqual(c.loads,['FRED:DGS10']);});

for(const id of ['DATA:example','DESK:inst'])test('catalog browse item never becomes a market ticker: '+id,()=>{const c=harness();assert.equal(c.isWarehouse(id),true);assert.equal(c.chartId(id),id);assert.equal(c.observationId(id),false);c.openSym(id);assert.deepEqual(c.loads,[]);assert.equal(c.q.value,'');assert.match(c.chartSelection.reason,/no qualified scalar/);});
for(const id of ['CQ:btc_mvrv','CISS:stress'])test('qualified native scalar providers stay eligible: '+id,()=>{const c=harness();assert.equal(c.observationId(id),true);assert.equal(c.chartRoute(id).target,id);});
