// Actual source functions and native Enter handler; no network, application storage or map feed.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const read=f=>fs.readFileSync(f,'utf8'),watch=read('jh-chart-tvwatch.js'),engine=read('jh-chart-engine.js'),catalog=read('jh-chart-catalog.js');
const acorn={exports:{}};Function('exports','module',process.binding('natives')['internal/deps/acorn/acorn/dist/acorn'])(acorn.exports,acorn);
const trees=new Map();function nodes(src){if(trees.has(src))return trees.get(src);const out=[],stack=[acorn.exports.parse(src,{ecmaVersion:'latest'})];while(stack.length){const n=stack.pop();if(!n||typeof n!=='object')continue;if(n.type)out.push(n);for(const v of Object.values(n)){if(Array.isArray(v))stack.push(...v);else if(v&&typeof v==='object')stack.push(v);}}trees.set(src,out);return out;}
function fn(src,name){const a=nodes(src).filter(n=>n.type==='FunctionDeclaration'&&n.id.name===name);assert.equal(a.length,1,name);return src.slice(a[0].start,a[0].end);}
function variable(src,name){const n=nodes(src).find(n=>n.type==='VariableDeclarator'&&n.id.name===name);assert.ok(n,name);return 'var '+src.slice(n.start,n.end)+';';}
const assignments=nodes(engine).filter(n=>n.type==='AssignmentExpression'&&n.left.type==='MemberExpression'&&n.left.object.name==='q'&&n.left.property.name==='onkeydown'&&n.right.type==='FunctionExpression'&&engine.slice(n.right.start,n.right.end).includes('var s=q.value.trim().toUpperCase(); if(TABS.indexOf(s)<0)'));assert.equal(assignments.length,1);const nativeQ=engine.slice(assignments[0].right.start,assignments[0].right.end);
let previous=watch;const changes=JSON.parse(read('tests/fixtures/watchlist-correctness/source-transition.json'))['jh-chart-tvwatch.js'].edits.filter(e=>e.scope==='watchlist-handoff-coverage-2');assert.ok(changes.length);for(const e of changes.slice().reverse()){assert.equal(previous.slice(e.start,e.end),e.after);previous=previous.slice(0,e.start)+e.before+previous.slice(e.end);}
function harness(map=null,old=false){
 const c={window:{},Set,Number,Date,AbortController,setTimeout,clearTimeout,painted:[],toasts:[],loads:[],symMap:map,symMapReady:1,chartSelection:null,chartRouteObserver:null,TABS:[],active:'INITIAL',filter:''};c.q={value:'',dispatchEvent(e){this.onkeydown(e);}};c.document={getElementById(id){return id==='q'?c.q:null;}};c.KeyboardEvent=function(_,o){return o;};c.paintCard=s=>c.painted.push(s);c.toast=s=>c.toasts.push(s);c.loadSymMap=()=>Promise.resolve();c.loadDraw=c.renderTabs=c.renderList=()=>{};c.load=()=>c.loads.push(c.active);c.activeSym=()=>c.active;c.lookupSym=()=>'';
 vm.createContext(c);vm.runInContext(fn(catalog,'H')+['EXCH','SERIES_PROV','CURATED'].map(n=>variable(catalog,n)).join('\n')+fn(catalog,'isWarehouse')+fn(catalog,'chartId'),c);c.window.JHChartCatalog={isWarehouse:c.isWarehouse,chartId:c.chartId,curated:c.CURATED};
 vm.runInContext(['resolveSym','yahooSym','bare','observationId'].map(n=>fn(engine,n)).join('\n'),c);vm.runInContext(fn(engine,'normQ')+fn(engine,'classifySym')+variable(engine,'SEARCH_ALIASES'),c);const exported=nodes(engine).find(n=>n.type==='AssignmentExpression'&&n.left.type==='MemberExpression'&&n.left.property.name==='jhWatchlistResolve');assert.ok(exported);vm.runInContext(engine.slice(exported.start,exported.end),c);c.q.onkeydown=vm.runInContext('('+nativeQ+')',c);
 c.paintChartRoute=()=>{};vm.runInContext(['extraChart','fredId','chartSymbol'].map(n=>fn(old?previous:watch,n)).join('\n')+'\n'+(old?fn(previous,'openSym'):['routeHints','chartRoute','chartRouteText','openSym'].map(n=>fn(watch,n)).join('\n')),c);return c;
}
const baseline=harness(null,true);baseline.extraChart('NONE');const extraEntries=Object.entries(baseline.extraChart.map);assert.equal(extraEntries.length,461);
for(const [requested,target]of extraEntries)test('preserves current-main extra route '+requested,()=>{const c=harness();const r=c.chartRoute(requested);assert.equal(r.handoff,target);assert.equal(r.resolved,target);assert.equal(r.requested,requested);assert.equal(r.relation,'mapped-route');c.openSym(requested);assert.deepEqual(c.loads,[target.toUpperCase()]);assert.match(c.chartRouteText(r,null,[]),/equivalence unverified/);});
const cases=[['NASDAQ:AAPL','NASDAQ:AAPL','AAPL'],['NYSE:AAPL','NYSE:AAPL','AAPL'],['IEX:AAPL','IEX:AAPL','AAPL'],['BINANCE:BTCUSDT','BINANCE:BTCUSDT','BTCUSDT'],['BINANCE:BTCUSDC','BINANCE:BTCUSDC','BTCUSDC'],['COINBASE:BTCUSD','BTC-USD','BTC-USD'],['BINANCE:ETHBTC','BINANCE:ETHBTC','ETHBTC'],['TVC:GOLD','GC=F','GC=F'],['TVC:US10Y','FRED:DGS10','FRED:DGS10'],['OANDA:EURUSD','EURUSD=X','EURUSD=X'],['CME_MINI:ES1!','ES=F','ES=F'],['FRED:DGS10','FRED:DGS10','FRED:DGS10'],['AAPL','AAPL','AAPL'],['worldbank:NY.GDP.MKTP.CD:USA','worldbank:NY.GDP.MKTP.CD:USA','worldbank:NY.GDP.MKTP.CD:USA'],['FRED:BSCICP03DEUM665S','FRED:BSCICP03DEUM665S','FRED:BSCICP03DEUM665S'],['ECONOMICS:USDXY','FRED:DTWEXBGS','FRED:DTWEXBGS']];
for(const[id,handoff,resolved]of cases)test('supported handoff preserves requested identity '+id,()=>{const c=harness(),r=c.chartRoute(id);assert.equal(r.requested,id);assert.equal(r.handoff,handoff);assert.equal(r.resolved,resolved);c.openSym(id);assert.deepEqual(c.loads,[handoff.toUpperCase()]);const text=c.chartRouteText(r,null,[]);assert.ok(text.includes(id));assert.match(text,/Returned instrument, venue and currency: unverified/);});
for(const id of ['DGS2','DGS5','DGS10','DGS30','T10Y2Y'])test('native prefix-only original request '+id,()=>{const c=harness(),r=c.chartRoute(id);assert.equal(c.observationId(id),true);assert.equal(r.handoff,id);assert.equal(r.resolved,'FRED:'+id);assert.equal(r.relation,'provider-prefix');});
for(const id of ['DFF','SOFR','CPIAUCSL'])test('catalog prefix route bypasses bare non-scalar fallback '+id,()=>{const c=harness(),r=c.chartRoute(id);assert.equal(c.observationId(id),false);assert.equal(r.handoff,'FRED:'+id);assert.equal(r.relation,'provider-prefix');});
for(const id of ['ABCDEF','ESU6','USDJPY','BTC','ETH','GC=F','EURUSD=X','^VIX','BTC-USD'])test('no broad bare-identifier coverage cut '+id,()=>{const c=harness();assert.ok(c.chartRoute(id).handoff,id);});
for(const [id,target]of [['NASDAQ:AAPL','MSFT'],['AAPL','MSFT'],['LSE:IEMD','MSFT']])test('conflicting MARKET suggestion never replaces security '+id,()=>{const c=harness({[id]:{source:'MARKET',id:target}});c.openSym(id);assert.notEqual(c.loads[0],'MSFT');assert.ok(c.loads.length);assert.match(c.chartSelection.reason,/ignored/);});
test('canonical FRED/WB identifiers override conflicting maps and country heuristics',()=>{for(const id of ['FRED:DGS10','FRED:BSCICP03DEUM665S','worldbank:NY.GDP.MKTP.CD:USA']){const c=harness({[id.toUpperCase()]:{source:'FRED',id:'DGS2'}});c.openSym(id);assert.deepEqual(c.loads,[id.toUpperCase()]);}});
test('mapped WB alias remains explicit possible substitution',()=>{const c=harness({'WB:USA|NY.GDP.MKTP.CD':{source:'WORLDBANK',id:'USA|NY.GDP.MKTP.CD'}});const r=c.chartRoute('WB:USA|NY.GDP.MKTP.CD');assert.equal(r.handoff,'worldbank:NY.GDP.MKTP.CD:USA');assert.equal(r.relation,'mapped-route');});
for(const id of ['DATA:example','DESK:inst','FRED:','FRED:DGS10:EXTRA','worldbank:NY.GDP.MKTP.CD','###Section','A APL',null,true,42])test('unsafe/non-chartable request remains unavailable '+String(id),()=>{const c=harness();c.openSym(id);assert.deepEqual(c.loads,[]);assert.equal(c.q.value,'');});
for(const id of ['CQ:btc_mvrv','CISS:stress','ecb:EXR.D.USD.EUR.SP00.A'])test('exact scalar provider remains eligible '+id,()=>{const c=harness();assert.ok(c.chartRoute(id).handoff);assert.equal(c.observationId(id),true);});
for(const id of ['NASDAQ:AAPL','NYSE:AAPL','BINANCE:BTCUSDT','TVC:GOLD','FRED:DGS10','worldbank:NY.GDP.MKTP.CD:USA'])test('daily quote guard remains withheld '+id,()=>{const c=harness();vm.runInContext(read('jh-watchlist-quotes.js'),c);assert.ok(c.window.JHWatchlistQuotes.resolve(id,JSON.parse(read('data/tv-symbol-resolver.json'))).reason);});
test('identifier hints never infer currency from a listing suffix',()=>{const c=harness();assert.equal(c.routeHints('IEMD.L').pair,'unknown');assert.equal(c.routeHints('BINANCE:BTCUSDT').pair,'BTC/USDT');assert.equal(c.routeHints('OANDA:EURUSD').pair,'EUR/USD');assert.equal(c.routeHints('BTC-USD').pair,'BTC/USD');});
test('retained/loading/unavailable frame qualification is explicit',()=>{const c=harness(),r=c.chartRoute('TVC:GOLD');r.frame='GC=F';assert.match(c.chartRouteText(r,{symbol:'SPY',source:'invented'},[{}]),/previous chart label SPY/);assert.match(c.chartRouteText(r,{symbol:'GC=F',source:'invented'},[]),/Unavailable: no accepted/);assert.match(c.chartRouteText(r,{symbol:'GC=F',source:'invented'},[{}]),/Retained bars displayed; routing is not provenance/);});
test('pending candidate map cannot replay a stale click',()=>{const c=harness();c.symMapReady=0;c.loadSymMap=()=>{throw Error('No queued click');};c.openSym('TVC:GOLD');c.openSym('FRED:DGS10');assert.deepEqual(c.loads,['GC=F','FRED:DGS10']);});
test('missing native handler leaves input and chart unchanged',()=>{const c=harness();c.q.onkeydown=null;c.openSym('AAPL');assert.deepEqual(c.loads,[]);assert.equal(c.q.value,'');assert.equal(c.chartSelection.handoff,null);});

test('all current-main routing helpers remain byte identical',()=>{for(const id of ['extraChart','fredId','chartSymbol'])assert.equal(fn(watch,id),fn(previous,id));});

test("native market supplemental histories are explicit, including successful primary lookups",()=>{const c=harness(),r=c.chartRoute("BINANCE:BTCUSDT");r.frame=r.handoff;const text=c.chartRouteText(r,{symbol:r.frame,source:"invented+yahoo"},[{}]);assert.match(text,/fallback\/supplemental lookup: BTC-USD/);assert.match(text,/supplementary Yahoo data, including after a successful primary lookup/);assert.match(text,/BTC\/USDT/);assert.match(text,/BTC\/USD/);});

test("expired handoff cannot revive on a direct return and status updates preserve card editors",()=>{const c=harness(),banner={hidden:false,textContent:"",dataset:{}},card={dataset:{requested:"TVC:GOLD"},textContent:"loading",removed:false,remove(){this.removed=true;}};c.document.getElementById=id=>id==="watchlist-chart-route"?banner:null;c.document.querySelector=()=>card;c.window.jhChartEvidence={symbol:"GC=F",source:"invented"};c.window.lastBars=[{}];c.chartSelection=c.chartRoute("TVC:GOLD");c.chartSelection.frame="GC=F";c.active="GC=F";vm.runInContext(fn(watch,"paintChartRoute"),c);c.paintChartRoute();assert.equal(card.textContent,banner.textContent);c.active="MSFT";c.paintChartRoute();assert.equal(c.chartSelection,null);assert.equal(card.removed,true);c.active="GC=F";c.paintChartRoute();assert.equal(banner.hidden,true);assert.equal(c.window.jhWatchlistHandoff,null);});
