const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const rail=fs.readFileSync('jh-chart-tvrail.js','utf8'), watch=fs.readFileSync('jh-chart-tvwatch.js','utf8'), engine=fs.readFileSync('jh-chart-engine.js','utf8');
function store(values={}){const data=new Map(Object.entries(values).map(([k,v])=>[k,typeof v==='string'?v:JSON.stringify(v)]));return {writes:0,getItem(k){return data.has(k)?data.get(k):null;},setItem(){this.writes++;throw Error('Synthetic quota/write failure');},removeItem(){this.writes++;throw Error('Synthetic write failure');},data};}
function migration(){const context={window:{}};vm.runInNewContext(rail.slice(0,rail.indexOf('  if (!document.getElementById("jh-tvwatch-js"'))+'})();',context);return context.window.jhWatchlistStore;}
function helpers(){const context={window:{},document:{createElement(){return {};},documentElement:{appendChild(){}}},Date,Number,Set,AbortController};vm.runInNewContext(watch.slice(0,watch.indexOf('  function visible('))+'})();',context);return {api:context.window.jhWatchlistQuote,window:context.window};}
const M=migration(),H=helpers();H.window.jhWatchlistResolve=s=>({engine:"equity",ticker:s,yahoo:s});const rules=JSON.parse(fs.readFileSync('data/tv-symbol-resolver.json','utf8'));
const K={src:'jh_custom_watchlists',dst:'jh-chart-custom-lists',ledger:'jh-chart-pro-imported',sf:'jh_symbol_flags',df:'jh-chart-flags',fav:'jh-chart-favs',pf:'jh_favorites',fa:'jh_favs'};
const parse=(p,k)=>JSON.parse(p.after[k]);
function fixtureApply(p,storage){Object.entries(p.after).forEach(([k,v])=>storage.data.set(k,v));}
for(const symbol of ['NYSE:AAPL','NASDAQ:AAPL','LSE:AAPL','FRED:DGS10','OANDA:EURUSD','FX:GBPJPY','EURUSD','GBPJPY','USDTRY','USDBRL','USDKRW','XAUUSD','XAGUSD','ESU6','GCZ6','CME_MINI:ES1!','ES1!','TVC:GOLD','GC=F','BINANCE:BTCUSDT','COINBASE:BTCUSD','BTCUSDT','ETH-USD','ECONOMICS:USCPMI','SPX','NDX'])test('withholds unsupported identity '+symbol,()=>assert.ok(H.api.resolve(symbol,rules).reason));
test('bare ticker resolves, never namespace-stripped',()=>{assert.equal(H.api.resolve('AAPL',rules).ticker,'AAPL');assert.ok(H.api.resolve('NASDAQ:AAPL',rules).reason);});
test('existing native aliases are withheld',()=>{H.window.jhWatchlistResolve=s=>({engine:s==='DGS10'?'fred':'equity',ticker:s==='GOLD'?'GC=F':s,yahoo:s});for(const s of ['DGS10','GOLD'])assert.ok(H.api.resolve(s,rules).reason);H.window.jhWatchlistResolve=s=>({engine:"equity",ticker:s,yahoo:s});});
const now=Date.UTC(2026,9,4),rows=[{time:Date.UTC(2026,8,1)/1000,close:100},{time:Date.UTC(2026,9,3)/1000,close:110}];
const packet=(bars=rows)=>({ticker:'AAPL',span:'day',mult:1,source:'invented warehouse',bars});
test('dated daily aggregates retain both timestamps/source and uncertainty',()=>{const q=H.api.packet(packet(),'AAPL',now);assert.equal(q.last,110);assert.equal(q.chgv,10);assert.equal(q.chg,.1);assert.equal(q.previousTime,rows[0].time);assert.equal(q.completion,'unverified');});
test('one aggregate yields close but unavailable delta',()=>{const q=H.api.packet(packet([rows[0]]),'AAPL',now);assert.equal(q.last,100);assert.equal(q.chg,null);assert.equal(q.chgv,null);});
for(const close of [null,true,false,'', '110',Infinity,NaN])test('rejects unmeasured close '+String(close),()=>{assert.ok(H.api.packet(packet([{...rows[0],close}]),'AAPL',now).reason);});
for(const bars of [rows.slice().reverse(),[{...rows[0],time:null}],rows.map(b=>({...b,time:rows[0].time})),[{...rows[0],time:now/1000+1}],[{time:Number.MAX_SAFE_INTEGER,close:1}]])test('rejects invalid chronological packet '+JSON.stringify(bars),()=>assert.ok(H.api.packet(packet(bars),'AAPL',now).reason));
test('overflow is withheld; zero baseline has no invented delta',()=>{assert.ok(H.api.packet(packet([{...rows[0],close:-Number.MAX_VALUE},{...rows[1],close:Number.MAX_VALUE}]),'AAPL',now).reason);assert.equal(H.api.packet(packet([{...rows[0],close:0},rows[1]]),'AAPL',now).chg,null);});
for(const change of [{ticker:null},{ticker:'MSFT'},{source:''},{span:'minute'},{mult:2},{bars:[]}])test('rejects missing/conflicting evidence '+JSON.stringify(change),()=>assert.ok(H.api.packet({...packet(),...change},'AAPL',now).reason));
test('duplicate names remain separate source IDs and stable order; no destination writes',()=>{const st=store({[K.src]:{a:{name:'Same',tickers:['NASDAQ:AAPL']},b:{name:'Same',tickers:['FRED:DGS10']}},[K.dst]:[{id:'mine',name:'Same',symbols:['MSFT']}]});const p=M.prepare(st),d=parse(p,K.dst);assert.deepEqual(d.map(l=>l.id),['mine','chart-pro:a','chart-pro:b']);assert.deepEqual(d.map(l=>l.symbols),[['MSFT'],['NASDAQ:AAPL'],['FRED:DGS10']]);assert.equal(st.writes,0);assert.equal(st.getItem(K.ledger),null);});
test('repeated preview, rename and source changes preserve user destination intent',()=>{const st=store({[K.src]:{a:{name:'Original',tickers:['AAPL','MSFT']}}});const p=M.prepare(st);fixtureApply(p,st);const d=JSON.parse(st.getItem(K.dst));d[0].name='User rename';d[0].symbols=['MSFT'];st.data.set(K.dst,JSON.stringify(d));st.data.set(K.src,JSON.stringify({a:{name:'Source rename',tickers:['AAPL','MSFT','NVDA']}}));const next=M.prepare(st);assert.deepEqual(parse(next,K.dst)[0].symbols,['MSFT','NVDA']);assert.equal(parse(next,K.dst)[0].name,'User rename');fixtureApply(next,st);assert.equal(M.prepare(st).changes,0);assert.equal(st.writes,0);});
test('deleted destination is tombstoned rather than recreated',()=>{const st=store({[K.src]:{a:{name:'Source',tickers:['AAPL']}}});fixtureApply(M.prepare(st),st);st.data.set(K.dst,'[]');const p=M.prepare(st);assert.deepEqual(parse(p,K.dst),[]);assert.equal(parse(p,K.ledger).lists.a.deleted,true);assert.equal(st.writes,0);});
test('source deletion preserves saved destination',()=>{const st=store({[K.src]:{a:{name:'Source',tickers:['AAPL']}}});fixtureApply(M.prepare(st),st);st.data.set(K.src,'{}');assert.equal(parse(M.prepare(st),K.dst).length,1);});
test('favorite/flag removal is never reimported',()=>{const st=store({[K.sf]:{AAPL:'red'},[K.pf]:{AAPL:true}});fixtureApply(M.prepare(st),st);st.data.set(K.df,'{}');st.data.set(K.fav,'[]');const p=M.prepare(st);assert.deepEqual(parse(p,K.df),{});assert.deepEqual(parse(p,K.fav),[]);assert.equal(st.writes,0);});
test('legacy ambiguous name mapping cannot overwrite stores',()=>{const st=store({[K.src]:{a:{name:'Same',tickers:['AAPL']}},[K.ledger]:{lists:{a:['AAPL']}}});assert.throws(()=>M.prepare(st),/source ID/);assert.equal(st.writes,0);});
test('legacy ID mapping adopts only explicit source-owned original; removed flags/favorites remain removed',()=>{const st=store({[K.src]:{a:{name:'Same',tickers:['AAPL']}},[K.dst]:[{id:'a',name:'Renamed',from:'chart-pro',symbols:[]}],[K.ledger]:{lists:{a:['AAPL']}},[K.sf]:{AAPL:'red'},[K.pf]:{AAPL:true}});const p=M.prepare(st);assert.equal(parse(p,K.dst)[0].name,'Renamed');assert.deepEqual(parse(p,K.dst)[0].symbols,[]);assert.deepEqual(parse(p,K.df),{});assert.deepEqual(parse(p,K.fav),[]);});
for(const [key,value] of [[K.src,'{'],[K.dst,'{'],[K.dst,'{}'],[K.dst,'null'],[K.df,'[]'],[K.fav,'{}'],[K.ledger,'null'],[K.ledger,{version:2,lists:{stale:{id:42}},favorites:[],flags:[]}],[K.dst,[{id:'a',name:'A',symbols:[]},{id:'a',name:'B',symbols:[]}]]])test('malformed original retained '+key+JSON.stringify(value),()=>{const st=store({[key]:value});const before=st.getItem(key);assert.throws(()=>M.prepare(st));assert.equal(st.getItem(key),before);assert.equal(st.writes,0);});
test('concurrent edit while reading preview is rejected without writes',()=>{const st=store();let calls=0;const get=st.getItem.bind(st);st.getItem=k=>{if(++calls===9)st.data.set(K.dst,'[{"id":"newer","name":"Concurrent","symbols":[]}]');return get(k);};assert.throws(()=>M.prepare(st),/Concurrent/);assert.equal(st.writes,0);assert.ok(st.getItem(K.dst).includes('newer'));});
test('quota/destination/ledger writes are impossible while migration is held',()=>{const st=store({[K.src]:{a:{name:'Source',tickers:['AAPL']}}});assert.ok(M.prepare(st));assert.equal(st.writes,0);assert.deepEqual(Object.keys(M),['prepare']);});
function engineSave(storage){const a=engine.indexOf('  function watchlistShape('),b=engine.indexOf('  function bindWatchOps(',a);const context={localStorage:storage,CUSTOM_KEY:K.dst,FAV_KEY:K.fav,FLAG_KEY:K.df,toast(){}};vm.runInNewContext(engine.slice(a,b)+'this.save=saveWatchlist;',context);return context.save;}
test('native edit writer rejects quota and malformed original instead of claiming saved',()=>{const malformed=store({[K.dst]:'{'});assert.equal(engineSave(malformed)(K.dst,[]),false);assert.equal(malformed.getItem(K.dst),'{');assert.equal(malformed.writes,0);const quota=store({[K.dst]:[]});assert.equal(engineSave(quota)(K.dst,[{id:'x',name:'X',symbols:['NASDAQ:AAPL']}]),false);assert.equal(quota.getItem(K.dst),'[]');});
test('native watchlist adapters preserve source identity and row menu rather than flag-cycle replacement',()=>{assert.ok(engine.includes('window.jhWatchlistContext=function(x,y,s){openCtx(x,y,s);}'));assert.ok(watch.includes('window.jhWatchlistContext(e.clientX,e.clientY,b.dataset.s)'));assert.ok(!watch.includes('localStorage.setItem("jh-chart-flags"'));for(const name of ['addToList','toggleFav']){const start=engine.indexOf('  function '+name+'(');assert.ok(start>0);const snippet=engine.slice(start,engine.indexOf('\n  function ',start+1));assert.ok(!snippet.includes('s=bare(s)'));}});
test('all unrelated engine and historical helper bytes survive exact watchlist reversal',()=>{const P=require('./helpers/watchlist-source-preservation.cjs');for(const file of Object.keys(P.manifest)){const raw=fs.readFileSync(file,'utf8');if(file==='jh-chart-engine.js')P.normalize(raw);else P.normalizeHelper(raw,file);}});
test('mutating any unrelated chart byte is rejected by preservation guard',()=>{const P=require('./helpers/watchlist-source-preservation.cjs');assert.throws(()=>P.normalize(engine.replace('var active="SPY"','var active="MSFT"')),/exact watchlist candidate/);});

test("missing native resolver cannot route bare aliases",()=>{const fresh=helpers();for(const s of ["DGS10","US10Y","GOLD","AAPL"])assert.ok(fresh.api.resolve(s,rules).reason);});

test('ordinary Add Symbol retains original ID before any chart/catalog mapping',()=>{const a=engine.indexOf('  function goSymbol('),b=engine.indexOf('  async function loadTicker(',a);let added;const context={ssRows:[],window:{JHChartCatalog:{go(){throw Error('chart routing must not consume add');}}},addToList(s){added=s;},closeSymSearch(){},chartId(){throw Error('qualified add must not chart-normalize');}};vm.runInNewContext(engine.slice(a,b)+'this.go=goSymbol;',context);context.go('NASDAQ:NVDA','add');assert.equal(added,'NASDAQ:NVDA');});

test('existing economic aliases are unqualified without rewriting saved members',()=>{const a=engine.indexOf('  window.jhWatchlistResolve='),b=engine.indexOf('  window.jhWatchlistNativeList=',a);const context={window:{},normQ:s=>s.toLowerCase(),classifySym:s=>/^(SOFR|EFFR|GDP|CPI)/.test(s)?'macro':'stock',SEARCH_ALIASES:[{type:'economy',q:['dff']}],resolveSym:s=>({engine:'equity',ticker:s,yahoo:s})};vm.runInNewContext(engine.slice(a,b),context);for(const s of ['SOFR','EFFR','GDP','CPIAUCSL','DFF'])assert.equal(context.window.jhWatchlistResolve(s).engine,'unqualified-economic');assert.equal(context.window.jhWatchlistResolve('AAPL').ticker,'AAPL');});

test('chart-search More add uses retained watchlist identity independently of chart ID',()=>{assert.ok(engine.includes('rows.push({s:full, watchId:watchId||s'));assert.ok(engine.includes('ssRows.push({s:s,watchId:id'));assert.ok(engine.includes('goSymbol(x.dataset.a==="add"?watchId:s, x.dataset.a)'));assert.ok(engine.includes('escHtml(r.watchId||r.s)'));});
