// Actual source functions and native Enter handler; no network, application storage or map feed.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const read=f=>fs.readFileSync(f,'utf8'),watch=read('jh-chart-tvwatch.js'),engine=read('jh-chart-engine.js'),catalog=read('jh-chart-catalog.js');
const acorn={exports:{}};Function('exports','module',process.binding('natives')['internal/deps/acorn/acorn/dist/acorn'])(acorn.exports,acorn);
const trees=new Map();function nodes(src){if(trees.has(src))return trees.get(src);const out=[],stack=[acorn.exports.parse(src,{ecmaVersion:'latest'})];while(stack.length){const n=stack.pop();if(!n||typeof n!=='object')continue;if(n.type)out.push(n);for(const v of Object.values(n)){if(Array.isArray(v))stack.push(...v);else if(v&&typeof v==='object')stack.push(v);}}trees.set(src,out);return out;}
function fn(src,name){const a=nodes(src).filter(n=>n.type==='FunctionDeclaration'&&n.id.name===name);assert.equal(a.length,1,name);return src.slice(a[0].start,a[0].end);}
function variable(src,name){const n=nodes(src).find(n=>n.type==='VariableDeclarator'&&n.id.name===name);assert.ok(n,name);return 'var '+src.slice(n.start,n.end)+';';}
const assignments=nodes(engine).filter(n=>n.type==='AssignmentExpression'&&n.left.type==='MemberExpression'&&n.left.object.name==='q'&&n.left.property.name==='onkeydown'&&n.right.type==='FunctionExpression'&&engine.slice(n.right.start,n.right.end).includes('var s=q.value.trim().toUpperCase(); if(TABS.indexOf(s)<0)'));assert.equal(assignments.length,1);const nativeQ=engine.slice(assignments[0].right.start,assignments[0].right.end);
let previous=require("./helpers/chart-census-preservation.cjs").normalize(watch,"jh-chart-tvwatch.js");const edits=JSON.parse(read('tests/fixtures/watchlist-correctness/source-transition.json'))['jh-chart-tvwatch.js'].edits,lastCoverage=edits.map(e=>e.scope).lastIndexOf('watchlist-handoff-coverage-2');assert.ok(lastCoverage>=0);for(const e of edits.slice(lastCoverage+1).reverse()){assert.equal(previous.slice(e.start,e.end),e.after);previous=previous.slice(0,e.start)+e.before+previous.slice(e.end);}const changes=edits.filter(e=>e.scope==='watchlist-handoff-coverage-2');assert.equal(changes.length,6);for(const e of changes.slice().reverse()){assert.equal(previous.slice(e.start,e.end),e.after);previous=previous.slice(0,e.start)+e.before+previous.slice(e.end);}
function harness(map=null,old=false){
 const c={window:{},Set,Number,Date,AbortController,setTimeout,clearTimeout,painted:[],toasts:[],loads:[],symMap:map,symMapReady:1,chartSelection:null,chartRouteObserver:null,TABS:[],active:'INITIAL',filter:''};c.q={value:'',dispatchEvent(e){this.onkeydown(e);}};c.document={getElementById(id){return id==='q'?c.q:null;}};c.KeyboardEvent=function(_,o){return o;};c.paintCard=s=>c.painted.push(s);c.toast=s=>c.toasts.push(s);c.loadSymMap=()=>Promise.resolve();c.loadDraw=c.renderTabs=c.renderList=()=>{};c.load=()=>c.loads.push(c.active);c.activeSym=()=>c.active;c.lookupSym=()=>'';
 vm.createContext(c);vm.runInContext(fn(catalog,'H')+['EXCH','SERIES_PROV','CURATED'].map(n=>variable(catalog,n)).join('\n')+fn(catalog,'isWarehouse')+fn(catalog,'chartId'),c);c.window.JHChartCatalog={isWarehouse:c.isWarehouse,chartId:c.chartId,curated:c.CURATED};
 vm.runInContext(['resolveSym','yahooSym','bare','observationId'].map(n=>fn(engine,n)).join('\n'),c);vm.runInContext(fn(engine,'normQ')+fn(engine,'classifySym')+variable(engine,'SEARCH_ALIASES'),c);const exported=nodes(engine).find(n=>n.type==='AssignmentExpression'&&n.left.type==='MemberExpression'&&n.left.property.name==='jhWatchlistResolve');assert.ok(exported);vm.runInContext(engine.slice(exported.start,exported.end),c);c.q.onkeydown=vm.runInContext('('+nativeQ+')',c);
 c.paintChartRoute=()=>{};c.paintEconomicSources=()=>{};vm.runInContext(['extraChart','fredId','chartSymbol'].map(n=>fn(old?previous:watch,n)).join('\n')+'\n'+(old?fn(previous,'openSym'):['providerRest','routeHints','chartRoute','economicQualification','economicQualificationText','chartRouteText','openSym'].map(n=>fn(watch,n)).join('\n')),c);return c;
}
const baseline=harness(null,true);baseline.extraChart('NONE');const extraEntries=Object.entries(baseline.extraChart.map);assert.equal(extraEntries.length,461);
for(const [requested,target]of extraEntries)test('preserves current-main extra route '+requested,()=>{const c=harness();const r=c.chartRoute(requested);assert.equal(r.handoff,target);assert.equal(r.resolved,target);assert.equal(r.requested,requested);assert.equal(r.relation,'mapped-route');c.openSym(requested);assert.deepEqual(c.loads,[target.toUpperCase()]);assert.match(c.chartRouteText(r,null,[]),/equivalence unverified/);});
const cases=[['NASDAQ:AAPL','NASDAQ:AAPL','AAPL'],['NYSE:AAPL','NYSE:AAPL','AAPL'],['IEX:AAPL','IEX:AAPL','AAPL'],['BINANCE:BTCUSDT','BINANCE:BTCUSDT','BTCUSDT'],['BINANCE:BTCUSDC','BINANCE:BTCUSDC','BTCUSDC'],['COINBASE:BTCUSD','BTC-USD','BTC-USD'],['BINANCE:ETHBTC','BINANCE:ETHBTC','ETHBTC'],['TVC:GOLD','GC=F','GC=F'],['TVC:US10Y','FRED:DGS10','FRED:DGS10'],['OANDA:EURUSD','EURUSD=X','EURUSD=X'],['CME_MINI:ES1!','ES=F','ES=F'],['FRED:DGS10','FRED:DGS10','FRED:DGS10'],['AAPL','AAPL','AAPL'],['worldbank:NY.GDP.MKTP.CD:USA','worldbank:NY.GDP.MKTP.CD:USA','worldbank:NY.GDP.MKTP.CD:USA'],['FRED:BSCICP03DEUM665S','FRED:BSCICP03DEUM665S','FRED:BSCICP03DEUM665S'],['ECONOMICS:USDXY','FRED:DTWEXBGS','FRED:DTWEXBGS']];
for(const[id,handoff,resolved]of cases)test('supported handoff preserves requested identity '+id,()=>{const c=harness(),r=c.chartRoute(id);assert.equal(r.requested,id);assert.equal(r.handoff,handoff);assert.equal(r.resolved,resolved);c.openSym(id);assert.deepEqual(c.loads,[handoff.toUpperCase()]);const text=c.chartRouteText(r,null,[]);assert.ok(text.includes(id));assert.match(text,/Returned instrument, venue and currency: unverified/);});
for(const id of ['DGS2','DGS5','DGS10','DGS30','T10Y2Y'])test('native prefix-only original request '+id,()=>{const c=harness(),r=c.chartRoute(id);assert.equal(c.observationId(id),true);assert.equal(r.handoff,id);assert.equal(r.resolved,'FRED:'+id);assert.equal(r.relation,'provider-prefix');});
for(const id of ['DFF','SOFR','CPIAUCSL'])test('catalog prefix route bypasses bare non-scalar fallback '+id,()=>{const c=harness(),r=c.chartRoute(id);assert.equal(c.observationId(id),false);assert.equal(r.handoff,'FRED:'+id);assert.equal(r.relation,'provider-prefix');});
for(const id of ['ABCDEF','ESU6','USDJPY','BTC','ETH','GC=F','EURUSD=X','^VIX','BTC-USD'])test('no broad bare-identifier coverage cut '+id,()=>{const c=harness();assert.ok(c.chartRoute(id).handoff,id);});
for(const [id,target]of [['NASDAQ:AAPL','MSFT'],['AAPL','MSFT'],['LSE:IEMD','MSFT']])test('conflicting MARKET suggestion never replaces security '+id,()=>{const c=harness({[id]:{source:'MARKET',id:target}});c.openSym(id);assert.notEqual(c.loads[0],'MSFT');assert.ok(c.loads.length);assert.match(c.chartSelection.reason,/ignored/);});
test('canonical FRED/WB identifiers override conflicting maps and country heuristics',()=>{for(const id of ['FRED:DGS10','FRED:BSCICP03DEUM665S','worldbank:NY.GDP.MKTP.CD:USA']){const c=harness({[id.toUpperCase()]:{source:'FRED',id:'DGS2'}});c.openSym(id);assert.deepEqual(c.loads,[id.toUpperCase()]);}});
test('mapped WB alias remains explicit possible substitution',()=>{const c=harness({'WB:USA|NY.GDP.MKTP.CD':{source:'WORLDBANK',id:'USA|NY.GDP.MKTP.CD'}});const r=c.chartRoute('WB:USA|NY.GDP.MKTP.CD');assert.equal(r.handoff,'worldbank:NY.GDP.MKTP.CD:USA');assert.equal(r.relation,'mapped-route');});
for(const id of ['DATA:example','DESK:inst','FRED:','FRED:DGS10:EXTRA','worldbank:NY.GDP.MKTP.CD','###Section','A APL',null,true,42])test('unsafe/non-chartable request remains unavailable '+String(id),()=>{const c=harness();c.openSym(id);assert.deepEqual(c.loads,[]);assert.equal(c.q.value,'');});
for(const id of ['CQ:btc_mvrv','CISS:stress','ecb:EXR.D.USD.EUR.SP00.A'])test('exact scalar provider remains eligible '+id,()=>{const c=harness();assert.ok(c.chartRoute(id).handoff);assert.equal(c.observationId(id),true);});
for(const id of ['NASDAQ:AAPL','NYSE:AAPL','BINANCE:BTCUSDT','TVC:GOLD','FRED:DGS10','worldbank:NY.GDP.MKTP.CD:USA'])test('daily quote guard remains withheld '+id,()=>{const c=harness();vm.runInContext(read('jh-watchlist-quotes.js'),c);assert.ok(c.window.JHWatchlistQuotes.resolve(id,JSON.parse(read('data/tv-symbol-resolver.json'))).reason);});
test('identifier hints never infer currency from a listing suffix',()=>{const c=harness();assert.equal(c.routeHints('IEMD.L').pair,'unknown');assert.equal(c.routeHints('BINANCE:BTCUSDT').pair,'BTC/USDT');assert.equal(c.routeHints('OANDA:EURUSD').pair,'EUR/USD');assert.equal(c.routeHints('BTC-USD').pair,'BTC/USD');});
test('retained/loading/unavailable frame qualification is explicit',()=>{const c=harness(),r=c.chartRoute('TVC:GOLD');r.frame='GC=F';assert.match(c.chartRouteText(r,{symbol:'SPY',source:'invented'},[{}]),/previous chart label SPY/);assert.match(c.chartRouteText(r,{symbol:'GC=F',source:'invented'},[]),/Unavailable: no accepted/);assert.match(c.chartRouteText(r,{symbol:'GC=F',source:'invented'},[{}]),/Retained bars displayed; routing is not provenance/);});
test('pending candidate map cannot replay a stale click',()=>{const c=harness();c.symMapReady=0;c.loadSymMap=()=>{throw Error('No queued click');};c.openSym('TVC:GOLD');c.openSym('FRED:DGS10');assert.deepEqual(c.loads,['GC=F','FRED:DGS10']);});
test('missing native handler leaves input and chart unchanged',()=>{const c=harness();c.q.onkeydown=null;c.openSym('AAPL');assert.deepEqual(c.loads,[]);assert.equal(c.q.value,'');assert.equal(c.chartSelection.handoff,null);});

test('all current-main routing helpers remain byte identical',()=>{for(const id of ['extraChart','fredId','chartSymbol'])assert.equal(fn(watch,id),fn(previous,id));});

test("native market supplemental histories are explicit, including successful primary lookups",()=>{const c=harness(),r=c.chartRoute("BINANCE:BTCUSDT");r.frame=r.handoff;const text=c.chartRouteText(r,{symbol:r.frame,source:"invented+yahoo"},[{}]);assert.match(text,/fallback\/supplemental lookup: BTC-USD/);assert.match(text,/supplementary Yahoo data, including after a successful primary lookup/);assert.match(text,/BTC\/USDT/);assert.match(text,/BTC\/USD/);});

test("expired handoff cannot revive on a direct return and status updates preserve card editors",()=>{const c=harness(),banner={hidden:false,textContent:"",dataset:{}},card={dataset:{requested:"TVC:GOLD"},textContent:"loading",removed:false,remove(){this.removed=true;}};c.document.getElementById=id=>id==="watchlist-chart-route"?banner:null;c.document.querySelector=()=>card;c.window.jhChartEvidence={symbol:"GC=F",source:"invented"};c.window.lastBars=[{}];c.chartSelection=c.chartRoute("TVC:GOLD");c.chartSelection.frame="GC=F";c.active="GC=F";vm.runInContext(fn(watch,"paintChartRoute"),c);c.paintChartRoute();assert.equal(card.textContent,banner.textContent);c.active="MSFT";c.paintChartRoute();assert.equal(c.chartSelection,null);assert.equal(card.removed,true);c.active="GC=F";c.paintChartRoute();assert.equal(banner.hidden,true);assert.equal(c.window.jhWatchlistHandoff,null);});

const providerContext=harness();providerContext.providerRest('NONE');const providerEntries=Object.entries(providerContext.providerRest.map);assert.equal(providerEntries.length,997);
const priorProvider=harness();vm.runInContext(fn(require("./helpers/chart-bis-fx-preservation.cjs").normalize(watch,"jh-chart-tvwatch.js"),"providerRest"),priorProvider);priorProvider.providerRest("NONE");assert.equal(Object.keys(priorProvider.providerRest.map).length,698);for(const [key,value] of Object.entries(priorProvider.providerRest.map))assert.equal(providerContext.providerRest.map[key],value);
function callback(object,property){const matches=nodes(watch).filter(n=>n.type==='AssignmentExpression'&&n.left.type==='MemberExpression'&&n.left.object.name===object&&n.left.property.name===property&&n.right.type==='FunctionExpression'&&watch.slice(n.right.start,n.right.end).includes('openSym('));assert.equal(matches.length,1);return watch.slice(matches[0].right.start,matches[0].right.end);}
const navigation={mouse:callback('b','onclick'),keyboard:callback('b','onkeydown'),advanced:callback('tr','onclick'),arrow:(()=>{const n=nodes(watch).find(n=>n.type==='VariableDeclarator'&&n.id.name==='watchlistKeyAction');return watch.slice(n.init.arguments[0].start,n.init.arguments[0].end);})()};
for(const [requested,target]of providerEntries)test('provider route retains original identity on all four controls '+requested,()=>{for(const [mode,body]of Object.entries(navigation)){const c=harness();c.s=requested;c.tr={getAttribute:()=>requested};const row={getAttribute:()=>requested,focus(){},scrollIntoView(){},closest(selector){return selector==="#wlist .wrow"?this:null;}};c.document.getElementById=id=>id==='q'?c.q:id==='watch'?{classList:{contains:()=>true}}:null;c.document.querySelectorAll=()=>[row];const invoke=vm.runInContext('('+body+')',c);invoke({key:mode==='arrow'?'ArrowUp':'Enter',target:row,preventDefault(){},stopPropagation(){}});assert.deepEqual(c.loads,[target.toUpperCase()],mode);assert.equal(c.chartSelection.requested,requested,mode);assert.equal(c.chartSelection.handoff,target,mode);assert.equal(c.chartSelection.resolved,target,mode);assert.equal(c.chartSelection.relation,'mapped-route',mode);assert.deepEqual(c.painted,[requested],mode);const text=c.chartRouteText(c.chartSelection,null,[]);assert.ok(text.includes('Requested: '+requested),mode);if(target.startsWith('cboeindex:')){assert.match(text,/Cboe published index or settlement close; source equivalence unverified/);assert.match(text,/market OHLC and traded volume unqualified/);}else assert.match(text,/Possible proxy or source substitution; equivalence unverified/);assert.equal(c.chartSelection.requestHints.namespace,requested.split(':')[0]);}});
test('provider table never rewrites an already canonical request',()=>{for(const target of new Set(providerEntries.map(p=>p[1]).filter(s=>/^(FRED|worldbank):/i.test(s)))){const c=harness({[target.toUpperCase()]:{source:'FRED',id:'WRONG'}}),route=c.chartRoute(target);assert.equal(route.requested,target);assert.equal(route.handoff,target);assert.equal(route.resolved,target);assert.equal(route.relation,'exact');}});

const economicFixture=JSON.parse(read('tests/fixtures/watchlist-correctness/economic-qualifications.json'));
test('economic qualification preserves every exact current provider pair',()=>{const c=harness();c.providerRest('NONE');const bisAdditions=Object.fromEntries(['AR','CO','HR','HK','KW','PE','MY','MA','SA','RS','RO','PH','TH'].map(cc=>['ECONOMICS:'+cc+'INTR','bis:WS_CBPOL:D.'+cc]));const preservedPeerYieldAliases={"TVC:US01MY":"FRED:DGS1MO","TVC:US01Y":"FRED:DGS1","TVC:US02Y":"FRED:DGS2","TVC:US03MY":"FRED:DGS3MO","TVC:US03Y":"FRED:DGS3","TVC:US05Y":"FRED:DGS5","TVC:US06MY":"FRED:DGS6MO","TVC:US10Y":"FRED:DGS10","TVC:US30Y":"FRED:DGS30"};assert.deepEqual(JSON.parse(JSON.stringify(c.providerRest.map)),{...economicFixture.routes,...preservedPeerYieldAliases,...bisAdditions,...Object.fromEntries(Object.entries(JSON.parse(read("docs/audit/2026-10-04/chart-bis-fx-source-review.json")).alternatives).map(([id,d])=>[id,d.id])),...Object.fromEntries(Object.entries(JSON.parse(read("docs/audit/2026-10-04/chart-bis-monthly-source-review.json")).alternatives).map(([id,d])=>[id,d.id])),...Object.fromEntries(Object.entries(JSON.parse(read("docs/audit/2026-10-04/chart-oecd-source-review.json")).alternatives).map(([id,d])=>[id,d.alternative])),...Object.fromEntries(Object.entries(JSON.parse(read("docs/audit/2026-10-04/chart-census-watchlist-source-review.json")).alternatives).map(([id,d])=>[id,d.alternative])),...Object.fromEntries(Object.entries(JSON.parse(read("docs/audit/2026-10-04/chart-census-additional-watchlist-review.json")).alternatives).map(([id,d])=>[id,d.alternative])),...Object.fromEntries(Object.entries(JSON.parse(read("docs/audit/2026-10-04/chart-imf-watchlist-review.json")).alternatives).map(([id,d])=>[id,d.alternative])),...Object.fromEntries(Object.entries(JSON.parse(read("docs/audit/2026-10-04/chart-cboe-watchlist-review.json")).alternatives).map(([id,d])=>[id,d.alternative]))});assert.equal(economicFixture.records.length,36);assert.equal(economicFixture.records.filter(r=>r.definition_status==='verified-mismatch').length,13);assert.equal(economicFixture.records.filter(r=>r.definition_status==='historical-source').length,11);assert.equal(economicFixture.records.filter(r=>r.definition_status==='unverified').length,12);});
for(const entry of economicFixture.records)test('economic qualification is exact, dated and does not certify runtime '+entry.requested,()=>{const c=harness(),r=c.chartRoute(entry.requested),q=c.economicQualification(r);assert.equal(r.resolved,entry.resolved);assert.ok(Object.isFrozen(q));for(const[k,v]of Object.entries(entry))assert.equal(q[k],v,k);assert.equal(q.qualification_checked_date,'2026-10-04');assert.equal(q.source_observation_period,null);assert.equal(q.runtime_source_availability,'unknown');assert.equal(q.warehouse_freshness,'unknown');assert.equal(q.historical_vintage_availability,'unverified');for(const[evidence,bars]of [[null,[]],[{symbol:r.handoff,source:'invented'},[{}]],[{symbol:'PREVIOUS'},[{}]]]){r.frame=r.handoff;const text=c.chartRouteText(r,evidence,bars);assert.ok(text.includes(entry.warning));assert.match(text,/Source-page latest observation period: unverified/);assert.match(text,/Warehouse freshness and runtime source availability: unknown/);}assert.equal(c.economicQualification({...r,resolved:'FRED:OTHER'}),null);assert.equal(c.economicQualification({...r,requested:entry.resolved}),null);assert.equal(c.economicQualification({...r,requested:'DATA:example'}),null);});
test('economic qualification tolerates absent and unrelated routes without inventing facts',()=>{const c=harness();for(const route of [null,{},c.chartRoute('FRED:DGS10'),c.chartRoute('MSFT')])assert.equal(c.economicQualification(route),null);assert.equal(c.economicQualificationText(c.chartRoute('MSFT')),'');});
