const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const W=__dirname,source=fs.readFileSync(path.join(W,'../jh-ai-insights.js'),'utf8'),fixture=JSON.parse(fs.readFileSync(path.join(W,'fixtures/website-research-status/invented-packet.json'),'utf8'));
function harness(){
 const cache=new Map(),ctx={window:{},location:{pathname:'/bonds.html'},document:{readyState:'loading',addEventListener(){}},Date,Number,JSON,Promise,Array,Object,String,setTimeout,clearTimeout,AbortController,sessionStorage:{getItem:k=>cache.get(k)||null,setItem:(k,v)=>cache.set(k,v)}};
 vm.runInNewContext(source.replace("  if(document.readyState==='loading')",'  window.testAPI={valid,ageStr,getCached,setCached,buildPanel,clock,currentPageKey};\n  if(document.readyState===\'loading\')'),ctx);
 return {api:ctx.window.testAPI,cache};
}
const copy=()=>structuredClone(fixture);
test('complete invented contract parses as availability only',()=>{const {api}=harness();assert.equal(api.valid(copy()),true);assert.match(api.buildPanel(copy()),/WAIT · UNQUALIFIED/);assert.doesNotMatch(api.buildPanel(copy()),/Decisive Call|claude-haiku/);});
test('legacy, null and self-promoted packets cannot reintroduce a market posture',()=>{const {api}=harness();for(const p of [null,{},[],{synthesis:{global_posture:'RISK_ON'}}, {...copy(),calls_eligible:true}]){assert.equal(api.valid(p),false);assert.match(api.buildPanel(p),/unavailable/);assert.doesNotMatch(api.buildPanel(p),/NEUTRAL|RISK.ON/);}});
test('malformed count, scope and missing provenance rejected',()=>{const {api}=harness();for(const change of [p=>p.engines_loaded=true,p=>p.engines_loaded=11,p=>delete p.input_status.bonds,p=>p.input_status.bonds.artifact='data/account.json',p=>p.input_status.bonds.body_sha256=null,p=>p.input_status.bonds.body_bytes='10',p=>p.input_status.bonds.decision_eligible=true]){let p=copy();change(p);assert.equal(api.valid(p),false);}});
test('array-shaped synthesis and decisions rejected',()=>{const {api}=harness();assert.equal(api.valid({...copy(),synthesis:[]}),false);assert.equal(api.valid({...copy(),decision:[]}),false);});
test('missing, impossible and invalid publication times remain unavailable',()=>{const {api}=harness();for(const value of [null,'','not-a-time','2026-02-30T00:00:00Z','2026-09-30T24:00:00Z','2026-01-01'])assert.equal(api.ageStr(value),'publication time unavailable');});
test('future publication is never labeled now',()=>{const {api}=harness();assert.equal(api.ageStr('2099-01-01T00:00:00Z'),'publication time is in the future');});
test('cache requires bounded finite nonfuture local clock',()=>{const {api,cache}=harness();for(const t of [undefined,null,true,'123',Date.now()+100000,Date.now()-901000]){cache.set('jh_research_status_cache_v2',JSON.stringify({version:2,cached_at:t,payload:copy()}));assert.equal(api.getCached(),null);}});
test('old cache and cached self-promotion are withheld',()=>{const {api,cache}=harness();for(const p of [{_cached_at:Date.now(),synthesis:{global_posture:'NEUTRAL'}},{version:2,cached_at:Date.now(),payload:{...copy(),sizing_eligible:true}}]){cache.set('jh_research_status_cache_v2',JSON.stringify(p));assert.equal(api.getCached(),null);}});
test('cache envelope does not mutate the original packet',()=>{const {api}=harness(),p=copy(),before=JSON.stringify(p);api.setCached(p);assert.equal(JSON.stringify(p),before);assert.equal(JSON.stringify(api.getCached()),before);});
test('literal source labels, dates and watch entries cannot create executable markup',()=>{const {api}=harness(),p=copy();p.synthesis.per_page_focus.bonds='<img src=x onerror=alert(1)>';p.synthesis.watch_list=['<script>bad()</script>'];p.input_status.bonds.reported_as_of='</div><svg onload=bad()>';let html=api.buildPanel(p);assert.doesNotMatch(html,/<img|<script|<svg/);assert.match(html,/&lt;img/);assert.match(html,/&lt;svg/);});
test('malformed lists and page focus do not crash rendering',()=>{const {api}=harness(),p=copy();p.synthesis.watch_list='text';p.synthesis.per_page_focus=[];assert.doesNotThrow(()=>api.buildPanel(p));});
test('fixed metadata rows remain inspectable without source-body summaries',()=>{const {api}=harness(),p=copy();let html=api.buildPanel(p);assert.equal((html.match(/class="jhi-input"/g)||[]).length,12);assert.match(html,/Body SHA-256/);assert.match(html,/Observation freshness and source evidence: unverified/);});
