const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const R=path.join(__dirname,'..'),S=path.join(R,'cloudflare/workers/justhodl-data-proxy/src'),D=path.join(R,'tests/fixtures/worker-oecd-path');
const key='data/warm/oecd/data/DSD_STES@DF_INDSERV.dat.gz',url='https://invented-worker.test/';
const raw=Buffer.from([31,139,8,0,0,0,0,0,0,3,11,73,45,46,1,0,50,209,77,120,4,0,0,0]);
async function withWorker(fn,{before=false,status=200}={}){
 const oldFetch=global.fetch,oldCaches=global.caches,calls=[],puts=[],waits=[],cache=new Map();
 global.caches={default:{match:async req=>cache.get(req.url)?.clone(),put:async(req,res)=>{puts.push(req.url);cache.set(req.url,res.clone());}}};
 global.fetch=async(input,init={})=>{calls.push({url:String(input),init});assert.equal(String(input),'https://justhodl-dashboard-live.s3.us-east-1.amazonaws.com/'+key,'Only exact public object origin');return new Response(raw,{status,headers:{'Content-Type':'application/gzip','ETag':'"invented-etag"','Last-Modified':'Sun, 04 Oct 2026 00:00:00 GMT',...(status===206?{'Content-Range':'bytes 0-23/24','Content-Length':'24'}:{})}});};
 try{
  let worker;
  if(before){let code=fs.readFileSync(path.join(D,'cloudflare__workers__justhodl-data-proxy__src__index.js.before.txt'),'utf8');code=code.replace(/from (['"])(\.\/[^'"]+)\1/g,(_,q,relative)=>'from '+JSON.stringify(pathToFileURL(path.join(S,relative)).href));worker=(await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'))).default;}
  else worker=(await import(pathToFileURL(path.join(S,'index.js')).href)).default;
  const request=async(p,opts)=>{const res=await worker.fetch(new Request(url+p,opts),{},{waitUntil:p=>waits.push(p)});await Promise.all(waits);return res;};
  await fn({request,calls,puts});
 }finally{global.fetch=oldFetch;global.caches=oldCaches;}
}
test('complete preceding handler reproduces OECD at-sign rejection before any origin request',async()=>withWorker(async({request,calls})=>{for(const p of [key,key.replace('@','%40')])assert.equal((await request(p+'?exact=1&nogen=1')).status,400);assert.equal(calls.length,0);},{before:true}));
test('raw and singly encoded OECD separators preserve original bytes and exact object identity',async()=>withWorker(async({request,calls,puts})=>{for(const p of [key,key.replace('@','%40')]){const res=await request(p+'?exact=1&nogen=1');assert.equal(res.status,200);assert.equal(res.headers.get('X-JH-Artifact-Key'),key);assert.equal(res.headers.get('Cache-Control'),'no-store');assert.equal(res.headers.get('ETag'),'"invented-etag"');assert.deepEqual(Buffer.from(await res.arrayBuffer()),raw);}assert.equal(calls.length,2);assert.equal(puts.length,0);}));
test('ordinary encoded and raw requests share one cache identity',async()=>withWorker(async({request,calls,puts})=>{for(const p of [key.replace('@','%40'),key]){const res=await request(p);assert.equal(res.status,200);assert.deepEqual(Buffer.from(await res.arrayBuffer()),raw);}assert.equal(calls.length,1);assert.equal(puts.length,1);assert.ok(puts[0].endsWith('/'+key));}));
test('OECD byte ranges retain exact bytes and never populate the whole-object cache',async()=>withWorker(async({request,calls,puts})=>{const res=await request(key.replace('@','%40')+'?exact=1&nogen=1',{headers:{Range:'bytes=0-23'}});assert.equal(res.status,206);assert.equal(res.headers.get('Content-Range'),'bytes 0-23/24');assert.equal(res.headers.get('Cache-Control'),'no-store');assert.deepEqual(Buffer.from(await res.arrayBuffer()),raw);assert.equal(calls[0].init.headers.Range,'bytes=0-23');assert.equal(puts.length,0);},{status:206}));
for(const status of [403,404,429,503])test('OECD upstream '+status+' passes through once without alias, invocation or retry',async()=>withWorker(async({request,calls,puts})=>{const res=await request(key+'?exact=1&nogen=1');assert.equal(res.status,status);assert.equal(res.headers.get('Cache-Control'),'no-store');assert.deepEqual(await res.json(),{error:'upstream not ok',status,path:key});assert.equal(calls.length,1);assert.equal(puts.length,0);},{status}));
test('new path support cannot open private namespaces or encoded traversal',async()=>withWorker(async({request,calls,puts})=>{
 const bad=['data/warm/oecd/data/DSD_STES%2540DF_INDSERV.dat.gz','data/warm/oecd/data/DSD_STES%2Fsecret@DF_INDSERV.dat.gz','data/warm/oecd/data/DSD_STES@DF_INDSERV%00.dat.gz','data/warm/oecd/data/DSD_STES@DF_INDSERV.json','data/warm/oecd/data/DSD_STES@DF_INDSERV.csv.gz','data/warm/other/data/DSD_STES@DF_INDSERV.dat.gz','data/private@example.com.json','data/warm/oecd/data/DSD_STES%252F..%252F@DF_INDSERV.dat.gz','data/warm/oecd/data/DSD_STES@DF_INDSERV.dat.gz%3Fx=1'];
 for(const p of bad)assert.equal((await request(p)).status,400,p);
 for(const p of ['data/ai-brief.md','data/history/archive/feed/ai-brief.json/2026-01-01.json','data/audit-private/example@private.dat.gz','data/portfolio/holdings.json'])assert.equal((await request(p)).status,403,p);
 assert.equal((await request('data/ai-brief.json')).status,401);assert.equal((await request(key,{method:'POST',body:'invented'})).status,405);assert.equal(calls.length,0);assert.equal(puts.length,0);
}));
test('strict helper preserves safe legacy paths without general decoding',async()=>{const {publicObjectPath}=await import(pathToFileURL(path.join(S,'public-object-path.mjs')).href);for(const value of ['/data/a.json','/data/providers/oecd/page-001.json','/data/series-cache/oecd-source/abc/responses/def.csv.gz'])assert.equal(publicObjectPath(value),value.slice(1));for(const value of [null,{},'', '/data/warm/oecd/data/../DSD_STES@DF_INDSERV.dat.gz','/'+key+'?x=1','/'+key+'#x'])assert.equal(publicObjectPath(value),null);});
test('whole worker and prior preservation hooks permit only the declared additive path repair',()=>{const {normalize,manifest}=require('./helpers/worker-oecd-path-preservation.cjs');for(const file of Object.keys(manifest.entries)){const current=fs.readFileSync(path.join(R,file),'utf8');normalize(current,file);assert.throws(()=>normalize(current+'\n// unrelated change',file));}const file='cloudflare/workers/justhodl-data-proxy/src/index.js',current=fs.readFileSync(path.join(R,file),'utf8');assert.throws(()=>normalize(current.replace('if (privateArchive(url.pathname))','if (false)'),file));});
