const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),cp=require('node:child_process');
const source=fs.readFileSync('wyckoff-desk.html','utf8');
const baseline=fs.readFileSync('tests/fixtures/wyckoff-desk-before-permission.html','utf8');
const fixture=JSON.parse(cp.execFileSync('python3',['tests/fixtures/capital_view_fixture.py'],{encoding:'utf8'})).katlin;
class Node {constructor(tag){this.tag=tag;this.childNodes=[];this.style={};this.dataset={};this.events={};this.textContent='';this.innerHTML='';}append(...n){this.childNodes.push(...n);}appendChild(n){this.append(n);}replaceChildren(){this.childNodes=[];}addEventListener(k,f){this.events[k]=f;}querySelector(t){return this.childNodes.find(n=>n.tag===t);} }
async function load(p,tab='spread',html=source){
 const nodes={},events={},timers=[],requests=[];const document={hidden:false,createElement:t=>new Node(t),getElementById:id=>nodes[id]||(nodes[id]=new Node('div')),querySelectorAll:()=>[],addEventListener:(k,f)=>events[k]=f};
 let now=Date.now();class Clock extends Date{static now(){return now;}}
 const feeds={katlin:p,phase:{tickers:{AAA:{phase:'ACCUMULATION',price:5,days_in_phase:20}}},radar:{},bottom:{board:[]}};
 const c={document,window:{},location:{search:'?tab='+tab},history:{replaceState(){}},URLSearchParams,Date:Clock,setInterval:f=>timers.push(f),fetch:async u=>{requests.push(u);return {ok:true,json:async()=>feeds[u.match(/\/([^/]+)\.json/)[1]==='phase-detector'?'phase':u.match(/\/([^/]+)\.json/)[1]==='accumulation-radar'?'radar':u.match(/\/([^/]+)\.json/)[1]]};}};
 vm.createContext(c);vm.runInContext(fs.readFileSync('capital-view.js','utf8'),c);vm.runInContext([...html.matchAll(/<script>([\s\S]*?)<\/script>/g)][0][1],c);await new Promise(r=>setImmediate(r));
 function text(n){return n.textContent+' '+n.childNodes.map(text).join(' ');}
 return {nodes,requests,tick:t=>{now=t;timers.forEach(f=>f());},visible:()=>events.visibilitychange(),text:()=>text(nodes['katlin-permission']),expand(){function go(n){if(n.tag==='details'){n.open=true;n.events.toggle();}n.childNodes.forEach(go);}go(nodes['katlin-permission']);}};
}
function packet(){const p=structuredClone(fixture);p.picks=[{ticker:'AAA',tier:'BASING',bbw_pctile:0,squeeze:true,last:5,pillars:{accumulation:90},posture_note:'<img src=x onerror=alert(1)>'},{ticker:'BBB',tier:'CRASH_BARBELL',bbw_pctile:10,squeeze:true,pillars:{accumulation:80}}];return p;}
test('funding hold retains rows, mixed-source measures, tiers and request parity on every tab',async()=>{for(const tab of ['spread','accum','sc','capit','bc','spring','bottom','pump','dist','top']){const p=packet();p.war_room.entries_allowed=false;p.war_room.exposure_cap_pct=0;p.war_room.posture='DATA_HOLD';p.war_room.hold_reasons=['funding unavailable'];const original=JSON.stringify(p),a=await load(p,tab),b=await load(p,tab,baseline);assert.equal(a.nodes.board.innerHTML,b.nodes.board.innerHTML);assert.deepEqual(a.requests,b.requests);assert.equal(JSON.stringify(p),original);assert.equal(a.nodes['katlin-permission'].hidden,!['spread','accum'].includes(tab));if(tab==='spread'){assert.match(a.text(),/blocked/);assert.match(a.text(),/Effective cap: 0%/);assert.match(a.text(),/funding unavailable/);a.expand();assert.match(a.text(),/<img src=x onerror=alert\(1\)>/);}}});
test('valid permission, zero, missing and malformed stay explicit',async()=>{let a=await load(packet());assert.match(a.text(),/allowed by loaded/);for(const mutate of [p=>delete p.war_room,p=>p.war_room.exposure_cap_pct='',p=>p.war_room.exposure_cap_pct=false,p=>p.war_room.hold_reasons={},p=>p.generated_at='2099-01-01T00:00:00Z',p=>p.research_generated_at='2020-01-01T00:00:00Z',p=>p.expires_at='2020-01-01T00:00:00Z']){let p=packet();mutate(p);if(p.war_room?.hold_reasons && !Array.isArray(p.war_room.hold_reasons))p.expires_at='invalid';a=await load(p);assert.match(a.text(),/unavailable/);}a=await load({});assert.match(a.text(),/unavailable/);});
test('expiry and visibility recheck loaded packet without row or request changes',async()=>{const p=packet(),a=await load(p);const rows=a.nodes.board.innerHTML,requests=[...a.requests];a.tick(Date.parse(p.expires_at)+1);assert.match(a.text(),/permission expired/);a.visible();assert.deepEqual(a.requests,requests);assert.equal(a.nodes.board.innerHTML,rows);assert.match(a.text(),/Original research:/);assert.match(a.text(),/Permission refresh \/ publication:/);a.expand();assert.match(a.text(),/bond_warroom/);});
