const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),api=require('../jh-yen-research.js');
const stamp='2026-09-19T13:00:00Z',at=Date.parse(stamp);
function row(id='DEXJPUS'){return {id,name:'Reported FX',unit:'Japanese Yen to One U.S. Dollar',frequency:'D',value:0,value_decimal:'0',as_of:'2026-09-11',history:null,quality:{status:'fresh',acquired_at:stamp,observation_age_days:8,max_observation_age_days:null}};}
function packet(){return {contract:api.CONTRACT,generated_at:stamp,call:null,calls_eligible:false,sizing_eligible:false,execution_eligible:false,portfolio_action:'WAIT',unwind_risk_score:null,measurements:{DEXJPUS:row()},comparisons:{},positioning:null,quality:{},errors:{},legacy:{},monthly_changes:{},replay:{manifest_key:api.PREFIX+'runs/'+'a'.repeat(64)+'.json'}};}
test('H10 is a weekly release with daily observations and Eastern cutoff',()=>{assert.equal(api.h10Expected(at),'2026-09-11');assert.equal(api.h10Expected(Date.parse('2026-09-21T20:14:00Z')),'2026-09-11');assert.equal(api.h10Expected(Date.parse('2026-09-21T20:15:00Z')),'2026-09-18');assert.equal(api.h10Expected(Date.parse('2026-12-07T21:14:00Z')),'2026-11-27');});
test('expired source is withheld while archived snapshot remains inspectable',()=>{const p=packet();assert.equal(api.status(row(),at),'fresh');assert.equal(api.status(row(),at+27*3600000),'expired_source');assert.equal(api.status(row(),at+27*3600000,true),'fresh_at_snapshot');assert.match(api.summary(p,at+27*3600000).board,/— Japanese Yen/);assert.match(api.detail(p,'DEXJPUS',at+27*3600000),/<strong>0 Japanese Yen/);p.calls_eligible=true;assert.throws(()=>api.boundary(p),/contract/);});
test('funding scenario reconciles FX, USD interest, JPY interest and explicit fees',()=>{const r=api.scenario(1000000,150,140,5,1,360,360,360,100000);assert.equal(r.fx_principal_pnl_jpy,-10000000);assert.equal(r.usd_interest_converted_jpy,7000000);assert.equal(r.jpy_funding_interest,1500000);assert.equal(r.net_pnl_jpy,-4600000);assert.ok(Math.abs(r.break_even_jpy_per_usd-151600000/1050000)<1e-10);const b=api.scenario(1000000,150,r.break_even_jpy_per_usd,5,1,360,360,360,100000);assert.ok(Math.abs(b.net_pnl_jpy)<1e-7);assert.equal(r.forecast,false);assert.equal(r.position_size,null);});
test('scenario has no default exposures and does not coerce blank or null to zero',()=>{for(const args of [[null,150,140,5,1,360,360,360,0],[1,0,140,5,1,360,360,360,0],[1,150,140,5,1,360.5,360,360,0],[1,150,140,5,1,360,0,360,0],[1,150,140,5,1,360,360,360,-1]])assert.throws(()=>api.scenario(...args));assert.equal(api.scenario(0,150,140,0,0,1,360,365,0).net_pnl_jpy,0);assert.equal(api.scenario(0,150,140,0,0,1,360,365,0).break_even_jpy_per_usd,null);});
test('history chart honors dates and breaks missing records',()=>{const h={id:'x',unit:'Percent',frequency:'D',rows:[{date:'2026-09-01',value_decimal:'-2'},{date:'2026-09-02',value_decimal:null},{date:'2026-09-03',value_decimal:'3'}]};const path=api.chart(h).match(/<path d="([^"]*)"/)[1];assert.equal((path.match(/M/g)||[]).length,2);assert.ok(!path.includes('L'));assert.match(api.history(h).html,/—/);});
test('source labels and links cannot inject markup or leave public evidence paths',()=>{const p=packet();p.measurements.DEXJPUS.name='<script>bad()</script>';assert.match(api.detail(p,'DEXJPUS',at),/&lt;script&gt;/);assert.equal(api.path('data/../../secret'),null);assert.equal(api.path('https://example.com'),null);});
test('immutable snapshot validates manifest and output hashes',async()=>{const p=packet();delete p.replay;const output=new TextEncoder().encode(JSON.stringify(p)),sha=await api.sha(output),m={contract:'yen-original-replay.v1',generated_at:stamp,output_sha256:sha,output:{key:api.PREFIX+'outputs/'+sha+'.json',sha256:sha,bytes:output.length}},raw=new TextEncoder().encode(JSON.stringify(m)),id=await api.sha(raw),files={['/'+api.PREFIX+'runs/'+id+'.json']:raw,['/'+m.output.key]:output};const fetcher=async key=>new Response(files[key],{status:files[key]?200:404});assert.equal((await api.loadSnapshot(id,fetcher)).contract,api.CONTRACT);files['/'+m.output.key]=new TextEncoder().encode('{}');await assert.rejects(api.loadSnapshot(id,fetcher),/differs/);});
test('history hashes, series and endpoints must all match',async()=>{const r=row(),h={contract:'yen-history.v1',id:r.id,unit:r.unit,frequency:'D',rows:[{date:r.as_of,value_decimal:'0',row_index:0}]},raw=new TextEncoder().encode(JSON.stringify(h)),sha=await api.sha(raw);r.history={key:api.PREFIX+'histories/'+sha+'.json',sha256:sha,bytes:raw.length,observations:1,from:r.as_of,to:r.as_of};assert.deepEqual(await api.loadHistory(r,async()=>new Response(raw)),h);r.id='OTHER';await assert.rejects(api.loadHistory(r,async()=>new Response(raw)),/contract/);});
test('page pins one snapshot and invalidates scenarios after assumption edits',()=>{const html=fs.readFileSync(require.resolve('../yen-carry.html'),'utf8'),js=fs.readFileSync(require.resolve('../jh-yen-page.js'),'utf8');assert.match(html,/jh-yen-research.js/);for(const s of ['jh-page-ai','interp-kit','s3.amazonaws.com'])assert.ok(!html.includes(s));assert.match(js,/ticket!==request/);assert.match(js,/Current pointer differs/);assert.match(js,/Assumptions changed/);assert.match(js,/research_snapshot:packet.replay/);assert.match(js,/setInterval\(\(\)=>render\(\),60000\)/);});
