#!/usr/bin/env python3
"""Add probed FRED routes whose name and units match the watchlist code."""
import hashlib, json, pathlib, sys

LINES = """
ECONOMICS:ATIPYY|FRED:PRINTO01ATQ659S
ECONOMICS:ATRSYY|FRED:SLRTTO01ATQ659S
ECONOMICS:AUCLI|FRED:AUSLOLITOAASTSAM
ECONOMICS:AUIPYY|FRED:PRINTO01AUQ659S
ECONOMICS:BECIR|FRED:IR3TIB01BEM156N
ECONOMICS:BEIPYY|FRED:PRINTO01BEQ659S
ECONOMICS:BERSYY|FRED:SLRTTO01BEQ659S
ECONOMICS:BRCLI|FRED:BRALOLITOAASTSAM
ECONOMICS:BRINTR|FRED:IRSTCB01BRM156N
ECONOMICS:BRIPYY|FRED:PRINTO01BRQ659S
ECONOMICS:BRRSYY|FRED:SLRTTO01BRQ659S
ECONOMICS:CACIR|FRED:IR3TIB01CAM156N
ECONOMICS:CACLI|FRED:CANLOLITOAASTSAM
ECONOMICS:CAIPYY|FRED:PRINTO01CAQ659S
ECONOMICS:CARSYY|FRED:SLRTTO01CAQ659S
ECONOMICS:CHIPYY|FRED:PRINTO01CHQ659S
ECONOMICS:CHRSYY|FRED:SLRTTO01CHQ659S
ECONOMICS:CLCIR|FRED:IR3TIB01CLM156N
ECONOMICS:CLIPYY|FRED:PRINTO01CLQ659S
ECONOMICS:CLM1|FRED:MANMM101CLM189S
ECONOMICS:CNCIR|FRED:IR3TIB01CNM156N
ECONOMICS:CNCLI|FRED:CHNLOLITOAASTSAM
ECONOMICS:CNINTR|FRED:IRSTCB01CNM156N
ECONOMICS:CZIPYY|FRED:PRINTO01CZQ659S
ECONOMICS:CZRSYY|FRED:SLRTTO01CZQ659S
ECONOMICS:DECIR|FRED:IR3TIB01DEM156N
ECONOMICS:DEIPYY|FRED:PRINTO01DEQ659S
ECONOMICS:DERSYY|FRED:SLRTTO01DEQ659S
ECONOMICS:DKIPYY|FRED:PRINTO01DKQ659S
ECONOMICS:DKRSYY|FRED:SLRTTO01DKQ659S
ECONOMICS:EECIR|FRED:IR3TIB01EEM156N
ECONOMICS:EEIPYY|FRED:PRINTO01EEQ659S
ECONOMICS:EERSYY|FRED:SLRTTO01EEQ659S
ECONOMICS:ESIPYY|FRED:PRINTO01ESQ659S
ECONOMICS:ESRSYY|FRED:SLRTTO01ESQ659S
ECONOMICS:EUCIR|FRED:IR3TIB01EZM156N
ECONOMICS:EUIPYY|FRED:PRINTO01EZQ659S
ECONOMICS:EUM1|FRED:MANMM101EZM189S
ECONOMICS:EURSYY|FRED:SLRTTO01EZQ659S
ECONOMICS:FICIR|FRED:IR3TIB01FIM156N
ECONOMICS:FIIPYY|FRED:PRINTO01FIQ659S
ECONOMICS:FIRSYY|FRED:SLRTTO01FIQ659S
ECONOMICS:FRIPYY|FRED:PRINTO01FRQ659S
ECONOMICS:FRRSYY|FRED:SLRTTO01FRQ659S
ECONOMICS:GBCLI|FRED:GBRLOLITOAASTSAM
ECONOMICS:GBIPYY|FRED:PRINTO01GBQ659S
ECONOMICS:GBRSYY|FRED:SLRTTO01GBQ659S
ECONOMICS:GRIPYY|FRED:PRINTO01GRQ659S
ECONOMICS:GRRSYY|FRED:SLRTTO01GRQ659S
ECONOMICS:HUCIR|FRED:IR3TIB01HUM156N
ECONOMICS:HUIPYY|FRED:PRINTO01HUQ659S
ECONOMICS:HURSYY|FRED:SLRTTO01HUQ659S
ECONOMICS:IDCLI|FRED:IDNLOLITOAASTSAM
ECONOMICS:IECIR|FRED:IR3TIB01IEM156N
ECONOMICS:IEIPYY|FRED:PRINTO01IEQ659S
ECONOMICS:IERSYY|FRED:SLRTTO01IEQ659S
ECONOMICS:ILCIR|FRED:IR3TIB01ILM156N
ECONOMICS:ILIPYY|FRED:PRINTO01ILQ659S
ECONOMICS:ILRSYY|FRED:SLRTTO01ILQ659S
ECONOMICS:INCLI|FRED:INDLOLITOAASTSAM
ECONOMICS:ININTR|FRED:IRSTCB01INM156N
ECONOMICS:INIPYY|FRED:PRINTO01INQ659S
ECONOMICS:ISCIR|FRED:IR3TIB01ISM156N
ECONOMICS:ITIPYY|FRED:PRINTO01ITQ659S
ECONOMICS:ITRSYY|FRED:SLRTTO01ITQ659S
ECONOMICS:JPCIR|FRED:IR3TIB01JPM156N
ECONOMICS:JPIPYY|FRED:PRINTO01JPQ659S
ECONOMICS:JPM1|FRED:MANMM101JPM189S
ECONOMICS:JPRSYY|FRED:SLRTTO01JPQ659S
ECONOMICS:KRIPYY|FRED:PRINTO01KRQ659S
ECONOMICS:KRRSYY|FRED:SLRTTO01KRQ659S
ECONOMICS:LUIPYY|FRED:PRINTO01LUQ659S
ECONOMICS:LURSYY|FRED:SLRTTO01LUQ659S
ECONOMICS:MXCLI|FRED:MEXLOLITOAASTSAM
ECONOMICS:MXRSYY|FRED:SLRTTO01MXQ659S
ECONOMICS:NLIPYY|FRED:PRINTO01NLQ659S
ECONOMICS:NLRSYY|FRED:SLRTTO01NLQ659S
ECONOMICS:NOCIR|FRED:IR3TIB01NOM156N
ECONOMICS:NOIPYY|FRED:PRINTO01NOQ659S
ECONOMICS:NZIPYY|FRED:PRINTO01NZQ659S
ECONOMICS:NZRSYY|FRED:SLRTTO01NZQ659S
ECONOMICS:PLCIR|FRED:IR3TIB01PLM156N
ECONOMICS:PLIPYY|FRED:PRINTO01PLQ659S
ECONOMICS:PLRSYY|FRED:SLRTTO01PLQ659S
ECONOMICS:PTCIR|FRED:IR3TIB01PTM156N
ECONOMICS:PTIPYY|FRED:PRINTO01PTQ659S
ECONOMICS:PTRSYY|FRED:SLRTTO01PTQ659S
ECONOMICS:RUINTR|FRED:IRSTCB01RUM156N
ECONOMICS:RUIPYY|FRED:PRINTO01RUQ659S
ECONOMICS:RURSYY|FRED:SLRTTO01RUQ659S
ECONOMICS:SEIPYY|FRED:PRINTO01SEQ659S
ECONOMICS:SERSYY|FRED:SLRTTO01SEQ659S
ECONOMICS:SICIR|FRED:IR3TIB01SIM156N
ECONOMICS:SIIPYY|FRED:PRINTO01SIQ659S
ECONOMICS:SIRSYY|FRED:SLRTTO01SIQ659S
ECONOMICS:SKCIR|FRED:IR3TIB01SKM156N
ECONOMICS:SKIPYY|FRED:PRINTO01SKQ659S
ECONOMICS:SKRSYY|FRED:SLRTTO01SKQ659S
ECONOMICS:TRCIR|FRED:IR3TIB01TRM156N
ECONOMICS:TRCLI|FRED:TURLOLITOAASTSAM
ECONOMICS:TRIPYY|FRED:PRINTO01TRQ659S
ECONOMICS:USCIR|FRED:IR3TIB01USM156N
ECONOMICS:USCU|FRED:TCU
ECONOMICS:USIPYY|FRED:PRINTO01USQ659S
ECONOMICS:USM0|FRED:BOGMBASE
ECONOMICS:USM1|FRED:M1SL
ECONOMICS:USM3|FRED:M3SL
ECONOMICS:USRSYY|FRED:SLRTTO01USQ659S
ECONOMICS:USUP|FRED:UNEMPLOY
ECONOMICS:ZACLI|FRED:ZAFLOLITOAASTSAM
ECONOMICS:ZARSYY|FRED:SLRTTO01ZAQ659S
TVC:DE10|FRED:IRLTLT01DEM156N
TVC:ES10|FRED:IRLTLT01ESM156N
TVC:EU10|FRED:IRLTLT01EZM156N
TVC:FI10|FRED:IRLTLT01FIM156N
TVC:FR10|FRED:IRLTLT01FRM156N
TVC:GB10|FRED:IRLTLT01GBM156N
TVC:GR10|FRED:IRLTLT01GRM156N
TVC:IT10|FRED:IRLTLT01ITM156N
TVC:JP10|FRED:IRLTLT01JPM156N
TVC:RU10Y|FRED:IRLTLT01RUM156N
TVC:RU10|FRED:IRLTLT01RUM156N
TVC:US01M|FRED:DGS1MO
TVC:US01|FRED:DGS1
TVC:US02|FRED:DGS2
TVC:US03M|FRED:DGS3MO
TVC:US03|FRED:DGS3
TVC:US05|FRED:DGS5
TVC:US06M|FRED:DGS6MO
TVC:US07|FRED:DGS7
TVC:US10|FRED:DGS10
TVC:US20Y|FRED:DGS20
TVC:US20|FRED:DGS20
TVC:US30|FRED:DGS30
TVC:ZA10Y|FRED:IRLTLT01ZAM156N
""".strip("\n")

ROOT = pathlib.Path(__file__).resolve()
while ROOT != ROOT.parent and not (ROOT / "jh-chart-tvwatch.js").exists():
    ROOT = ROOT.parent
TV = ROOT / "jh-chart-tvwatch.js"
FIX = ROOT / "tests/fixtures/watchlist-correctness/source-transition.json"
BEFORE = ROOT / "tests/fixtures/watchlist-correctness/jh-chart-tvwatch.js.txt"
TEST = ROOT / "tests/watchlist-identity.test.js"
MARKER = "ECONOMICS:ATIPYY|FRED:PRINTO01ATQ659S"
ANCHOR = 'TVC:US07Y|FRED:DGS7", lines = raw.split("\\n")'
COUNT_OLD = "assert.equal(providerEntries.length,55);"
COUNT_NEW = "assert.equal(providerEntries.length,%d);" % (55 + len(LINES.split("\n")))

def sha(b):
    return hashlib.sha256(b).hexdigest()

def reverse(text, edits):
    for e in reversed(edits):
        got = text[e["start"]:e["end"]]
        if got != e["after"]:
            sys.exit("reverse mismatch at %s" % e["start"])
        text = text[:e["start"]] + e["before"] + text[e["end"]:]
    return text

text = TV.read_text()
if MARKER in text:
    print("already applied")
    sys.exit(0)
if text.count(ANCHOR) != 1:
    sys.exit("anchor count %s" % text.count(ANCHOR))
insert = "\\n" + "\\n".join(LINES.split("\n"))
after = "TVC:US07Y|FRED:DGS7" + insert + '", lines = raw.split("\\n")'
new = text.replace(ANCHOR, after, 1)
if new.count(MARKER) != 1 or new.count("function providerRest(") != 1:
    sys.exit("splice drifted")
for name in ("function extraChart(", "function fredId(", "function chartSymbol("):
    if text.count(name) != 1 or new.count(name) != 1:
        sys.exit("helper count " + name)

fix = json.loads(FIX.read_text())
entry = fix["jh-chart-tvwatch.js"]
if sha(text.encode()) != entry["after_sha256"]:
    sys.exit("working tree hash != fixture")
start = new.find(after)
edit = {"start": start, "end": start + len(after), "before": ANCHOR, "after": after}
edits = list(entry["edits"]) + [edit]
restored = reverse(new, edits)
base = BEFORE.read_bytes()
if restored.encode() != base:
    rb, bb = restored.encode(), base
    n = min(len(rb), len(bb))
    i = next((k for k in range(n) if rb[k] != bb[k]), n)
    sys.exit("preservation reverse failed at %s" % i)

# Same order as tests/watchlist-identity.test.js
prev = new
scopes = [e.get("scope") for e in edits]
last = max(i for i, s in enumerate(scopes) if s == "watchlist-handoff-coverage-2")
for e in reversed(edits[last+1:]):
    if prev[e["start"]:e["end"]] != e["after"]:
        sys.exit("post-coverage mismatch at %s" % e["start"])
    prev = prev[:e["start"]] + e["before"] + prev[e["end"]:]
for e in reversed(edits[:last+1]):
    if e.get("scope") != "watchlist-handoff-coverage-2":
        continue
    if prev[e["start"]:e["end"]] != e["after"]:
        sys.exit("coverage mismatch at %s" % e["start"])
    prev = prev[:e["start"]] + e["before"] + prev[e["end"]:]

test = TEST.read_text()
if test.count(COUNT_OLD) != 1:
    sys.exit("identity count anchor %s" % test.count(COUNT_OLD))
test = test.replace(COUNT_OLD, COUNT_NEW, 1)

entry["edits"] = edits
entry["after_sha256"] = sha(new.encode())
TV.write_text(new)
FIX.write_text(json.dumps(fix, indent=2) + "\n")
TEST.write_text(test)
print("ok bytes", len(new.encode()), "added", len(LINES.split("\n")), "edits", len(edits))
