"""Requested LCE series identities; official metadata supplies the displayed definition.

Invalid or discontinued provider identities remain explicit acquisition gaps.
The catalog contains no inferred substitute, threshold or trading authority.
"""
SERIES = {
    'WALCL': {'category': 'balance_sheet', 'display_name': 'Fed Balance Sheet (total assets)'},
    'WSHOTSL': {'category': 'balance_sheet', 'display_name': 'Securities Held Outright: U.S. Treasury (TOTAL)'},
    'WSHOMCB': {'category': 'balance_sheet', 'display_name': 'Securities Held Outright: Mortgage-Backed Securities'},
    'RESPPALGUONNWW': {'category': 'balance_sheet', 'display_name': 'Securities Held Outright: Treasury Notes & Bonds'},
    'WGCAL': {'category': 'balance_sheet', 'display_name': 'Gold Stock (assets)'},
    'RESPPNTEPNWW': {'category': 'balance_sheet', 'display_name': 'MEMO: Treasury/Agency/MBS Eligible to Be Pledged'},
    'WRESBAL': {'category': 'balance_sheet', 'display_name': 'Bank Reserves (depository institutions)'},
    'TOTRESNS': {'category': 'balance_sheet', 'display_name': 'Total Reserves of Depository Institutions'},
    'WTREGEN': {'category': 'balance_sheet', 'display_name': 'Treasury General Account (TGA)'},
    'WCURCIR': {'category': 'balance_sheet', 'display_name': 'Currency in Circulation (liability)'},
    'RRPONTSYD': {'category': 'balance_sheet', 'display_name': 'Overnight Reverse Repo (RRP)'},
    'WLRRAL': {'category': 'balance_sheet', 'display_name': 'Reverse Repos with Foreign Officials'},
    'DPCREDIT': {'category': 'liquidity_facilities', 'display_name': 'Primary Credit (Discount Window)'},
    'OTHL1690': {'category': 'liquidity_facilities', 'display_name': 'Liquidity & Credit Facilities Loans 16-90 Day'},
    'SWP1690': {'category': 'liquidity_facilities', 'display_name': 'Central Bank Liquidity Swaps: 16-90 Day Maturity'},
    'SWPT': {'category': 'liquidity_facilities', 'display_name': 'Central Bank Liquidity Swaps: TOTAL'},
    'WLODL': {'category': 'liquidity_facilities', 'display_name': 'Other Liabilities & Capital: Other Liabilities (BTFP proxy)'},
    'BAMLH0A0HYM2': {'category': 'credit_spreads', 'display_name': 'ICE BofA US High Yield Master OAS'},
    'BAMLH0A1HYBB': {'category': 'credit_spreads', 'display_name': 'ICE BofA BB US High Yield OAS'},
    'BAMLH0A2HYB': {'category': 'credit_spreads', 'display_name': 'ICE BofA Single-B US High Yield OAS'},
    'BAMLH0A3HYC': {'category': 'credit_spreads', 'display_name': 'ICE BofA CCC & Lower US High Yield OAS'},
    'BAMLC0A0CM': {'category': 'credit_spreads', 'display_name': 'ICE BofA US Corporate IG OAS'},
    'BAMLC0A1CAAA': {'category': 'credit_spreads', 'display_name': 'ICE BofA AAA US Corporate OAS'},
    'BAMLC0A2CAA': {'category': 'credit_spreads', 'display_name': 'ICE BofA AA US Corporate OAS'},
    'BAMLC0A3CA': {'category': 'credit_spreads', 'display_name': 'ICE BofA Single-A US Corporate OAS'},
    'BAMLC0A4CBBB': {'category': 'credit_spreads', 'display_name': 'ICE BofA BBB US Corporate OAS'},
    'BAMLHE00EHYIOAS': {'category': 'credit_spreads', 'display_name': 'ICE BofA Euro High Yield OAS'},
    'BAMLEMHBHYCRPIOAS': {'category': 'credit_spreads', 'display_name': 'ICE BofA EM High Yield Corp Plus OAS'},
    'BAMLEMCBPIOAS': {'category': 'credit_spreads', 'display_name': 'ICE BofA EM Corporate Plus OAS'},
    'HQMCB1YR': {'category': 'corporate_yields', 'display_name': 'HQM Corporate Bond Spot Rate (1y)'},
    'HQMCB2YR': {'category': 'corporate_yields', 'display_name': 'HQM Corporate Bond Spot Rate (2y)'},
    'HQMCB5YR': {'category': 'corporate_yields', 'display_name': 'HQM Corporate Bond Spot Rate (5y)'},
    'HQMCB10YR': {'category': 'corporate_yields', 'display_name': 'HQM Corporate Bond Spot Rate (10y)'},
    'HQMCB30YR': {'category': 'corporate_yields', 'display_name': 'HQM Corporate Bond Spot Rate (30y)'},
    'DGS1': {'category': 'corporate_yields', 'display_name': '1-Year US Treasury'},
    'DGS2': {'category': 'corporate_yields', 'display_name': '2-Year US Treasury'},
    'DGS5': {'category': 'corporate_yields', 'display_name': '5-Year US Treasury'},
    'DGS10': {'category': 'corporate_yields', 'display_name': '10-Year US Treasury'},
    'DGS30': {'category': 'corporate_yields', 'display_name': '30-Year US Treasury'},
    'DRTSCILM': {'category': 'lending_standards', 'display_name': 'C&I Loans: Tightening (Large/Middle Firms)'},
    'DRTSCIS': {'category': 'lending_standards', 'display_name': 'C&I Loans: Tightening (Small Firms)'},
    'DRSDCILM': {'category': 'lending_standards', 'display_name': 'C&I Loans: Demand (Large/Middle Firms)'},
    'DRSDCIS': {'category': 'lending_standards', 'display_name': 'C&I Loans: Demand (Small Firms)'},
    'SUBLPDRCSC': {'category': 'lending_standards', 'display_name': 'CRE Tightening: Construction & Land Development'},
    'SUBLPDRCSN': {'category': 'lending_standards', 'display_name': 'CRE Tightening: Nonfarm Nonresidential'},
    'SUBLPDRCSM': {'category': 'lending_standards', 'display_name': 'CRE Tightening: Multifamily Residential'},
    'DRTSSP': {'category': 'lending_standards', 'display_name': 'Mortgage: Subprime Tightening Standards'},
    'DRTSCLCC': {'category': 'lending_standards', 'display_name': 'Credit Cards: Tightening Standards'},
    'STDSAUTO': {'category': 'lending_standards', 'display_name': 'Auto Loans: Tightening Standards'},
    'STDSOTHCONS': {'category': 'lending_standards', 'display_name': 'Other Consumer Loans: Tightening Standards'},
    'DRIWCIL': {'category': 'lending_standards', 'display_name': 'Willingness to Make Consumer Installment Loans'},
}

def extend_catalog(catalog):
    return {**SERIES, **catalog}
