"""Complete inherited fund and radar catalogs, retained without investment authority.

Membership and strategy labels are configured research classifications. The
legacy smart_money tag does not identify investors and is never scored.
No historical membership, leverage multiple or underlying exposure is inferred.
"""
ETF_UNIVERSE = {'SPY': {'category': 'broad',
         'subcategory': 'us_large_cap',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'VOO': {'category': 'broad',
         'subcategory': 'us_large_cap',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'IVV': {'category': 'broad',
         'subcategory': 'us_large_cap',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'QQQ': {'category': 'broad',
         'subcategory': 'us_megacap_tech',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'IWM': {'category': 'broad',
         'subcategory': 'us_small_cap',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'VTI': {'category': 'broad',
         'subcategory': 'us_total',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'DIA': {'category': 'broad',
         'subcategory': 'us_dow',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'XLK': {'category': 'sector',
         'subcategory': 'technology',
         'smart_money': True,
         'region': 'US',
         'ref_sector': 'Technology'},
 'XLF': {'category': 'sector',
         'subcategory': 'financials',
         'smart_money': True,
         'region': 'US',
         'ref_sector': 'Financial Services'},
 'XLE': {'category': 'sector',
         'subcategory': 'energy',
         'smart_money': True,
         'region': 'US',
         'ref_sector': 'Energy'},
 'XLV': {'category': 'sector',
         'subcategory': 'healthcare',
         'smart_money': True,
         'region': 'US',
         'ref_sector': 'Healthcare'},
 'XLP': {'category': 'sector',
         'subcategory': 'staples',
         'smart_money': True,
         'region': 'US',
         'ref_sector': 'Consumer Defensive'},
 'XLY': {'category': 'sector',
         'subcategory': 'discretionary',
         'smart_money': True,
         'region': 'US',
         'ref_sector': 'Consumer Cyclical'},
 'XLI': {'category': 'sector',
         'subcategory': 'industrials',
         'smart_money': True,
         'region': 'US',
         'ref_sector': 'Industrials'},
 'XLB': {'category': 'sector',
         'subcategory': 'materials',
         'smart_money': True,
         'region': 'US',
         'ref_sector': 'Basic Materials'},
 'XLU': {'category': 'sector',
         'subcategory': 'utilities',
         'smart_money': True,
         'region': 'US',
         'ref_sector': 'Utilities'},
 'XLRE': {'category': 'sector',
          'subcategory': 'real_estate',
          'smart_money': True,
          'region': 'US',
          'ref_sector': 'Real Estate'},
 'XLC': {'category': 'sector',
         'subcategory': 'communication',
         'smart_money': True,
         'region': 'US',
         'ref_sector': 'Communication Services'},
 'MTUM': {'category': 'factor',
          'subcategory': 'momentum',
          'smart_money': True,
          'region': 'US',
          'ref_sector': None},
 'VLUE': {'category': 'factor',
          'subcategory': 'value',
          'smart_money': True,
          'region': 'US',
          'ref_sector': None},
 'QUAL': {'category': 'factor',
          'subcategory': 'quality',
          'smart_money': True,
          'region': 'US',
          'ref_sector': None},
 'USMV': {'category': 'factor',
          'subcategory': 'min_vol',
          'smart_money': True,
          'region': 'US',
          'ref_sector': None},
 'IWD': {'category': 'factor',
         'subcategory': 'russell_value',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'IWF': {'category': 'factor',
         'subcategory': 'russell_growth',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'SPLV': {'category': 'factor',
          'subcategory': 'low_vol',
          'smart_money': True,
          'region': 'US',
          'ref_sector': None},
 'VUG': {'category': 'factor',
         'subcategory': 'vanguard_growth',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'VTV': {'category': 'factor',
         'subcategory': 'vanguard_value',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'EFA': {'category': 'country',
         'subcategory': 'eafe',
         'smart_money': True,
         'region': 'Intl',
         'ref_sector': None},
 'VEA': {'category': 'country',
         'subcategory': 'developed_intl',
         'smart_money': True,
         'region': 'Intl',
         'ref_sector': None},
 'EEM': {'category': 'country',
         'subcategory': 'emerging_markets',
         'smart_money': True,
         'region': 'EM',
         'ref_sector': None},
 'VWO': {'category': 'country',
         'subcategory': 'emerging_markets',
         'smart_money': True,
         'region': 'EM',
         'ref_sector': None},
 'EWJ': {'category': 'country',
         'subcategory': 'japan',
         'smart_money': True,
         'region': 'Intl',
         'ref_sector': None},
 'FXI': {'category': 'country',
         'subcategory': 'china_large',
         'smart_money': True,
         'region': 'EM',
         'ref_sector': None},
 'MCHI': {'category': 'country',
          'subcategory': 'china_broad',
          'smart_money': True,
          'region': 'EM',
          'ref_sector': None},
 'KWEB': {'category': 'country',
          'subcategory': 'china_internet',
          'smart_money': False,
          'region': 'EM',
          'ref_sector': None},
 'EWZ': {'category': 'country',
         'subcategory': 'brazil',
         'smart_money': True,
         'region': 'EM',
         'ref_sector': None},
 'INDA': {'category': 'country',
          'subcategory': 'india',
          'smart_money': True,
          'region': 'EM',
          'ref_sector': None},
 'EWG': {'category': 'country',
         'subcategory': 'germany',
         'smart_money': True,
         'region': 'Intl',
         'ref_sector': None},
 'EWU': {'category': 'country',
         'subcategory': 'uk',
         'smart_money': True,
         'region': 'Intl',
         'ref_sector': None},
 'EWY': {'category': 'country',
         'subcategory': 'south_korea',
         'smart_money': True,
         'region': 'EM',
         'ref_sector': None},
 'EWT': {'category': 'country',
         'subcategory': 'taiwan',
         'smart_money': True,
         'region': 'EM',
         'ref_sector': None},
 'EWA': {'category': 'country',
         'subcategory': 'australia',
         'smart_money': True,
         'region': 'Intl',
         'ref_sector': None},
 'EWC': {'category': 'country',
         'subcategory': 'canada',
         'smart_money': True,
         'region': 'Intl',
         'ref_sector': None},
 'TLT': {'category': 'treasury',
         'subcategory': 'long_20plus',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'IEF': {'category': 'treasury',
         'subcategory': '7_10yr',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'SHY': {'category': 'treasury',
         'subcategory': '1_3yr',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'GOVT': {'category': 'treasury',
          'subcategory': 'broad',
          'smart_money': True,
          'region': 'US',
          'ref_sector': None},
 'BIL': {'category': 'treasury',
         'subcategory': 'tbill',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'TIP': {'category': 'treasury',
         'subcategory': 'tips',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'AGG': {'category': 'treasury',
         'subcategory': 'agg_bond',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'HYG': {'category': 'credit',
         'subcategory': 'high_yield',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'JNK': {'category': 'credit',
         'subcategory': 'high_yield',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'LQD': {'category': 'credit',
         'subcategory': 'investment_grade',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'EMB': {'category': 'credit',
         'subcategory': 'em_bond',
         'smart_money': True,
         'region': 'EM',
         'ref_sector': None},
 'GLD': {'category': 'commodity',
         'subcategory': 'gold',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'IAU': {'category': 'commodity',
         'subcategory': 'gold',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'SLV': {'category': 'commodity',
         'subcategory': 'silver',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'USO': {'category': 'commodity',
         'subcategory': 'oil',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'UNG': {'category': 'commodity',
         'subcategory': 'nat_gas',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'DBC': {'category': 'commodity',
         'subcategory': 'broad',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'DBA': {'category': 'commodity',
         'subcategory': 'agriculture',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'CPER': {'category': 'commodity',
          'subcategory': 'copper',
          'smart_money': True,
          'region': 'US',
          'ref_sector': None},
 'ARKK': {'category': 'thematic',
          'subcategory': 'innovation',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'ARKW': {'category': 'thematic',
          'subcategory': 'web3',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'ARKG': {'category': 'thematic',
          'subcategory': 'genomics',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'SOXX': {'category': 'thematic',
          'subcategory': 'semiconductors',
          'smart_money': True,
          'region': 'US',
          'ref_sector': 'Technology'},
 'SMH': {'category': 'thematic',
         'subcategory': 'semiconductors',
         'smart_money': True,
         'region': 'US',
         'ref_sector': 'Technology'},
 'TAN': {'category': 'thematic',
         'subcategory': 'solar',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'ICLN': {'category': 'thematic',
          'subcategory': 'clean_energy',
          'smart_money': False,
          'region': 'Global',
          'ref_sector': None},
 'LIT': {'category': 'thematic',
         'subcategory': 'lithium',
         'smart_money': False,
         'region': 'Global',
         'ref_sector': None},
 'IBB': {'category': 'thematic',
         'subcategory': 'biotech',
         'smart_money': True,
         'region': 'US',
         'ref_sector': 'Healthcare'},
 'XBI': {'category': 'thematic',
         'subcategory': 'biotech',
         'smart_money': True,
         'region': 'US',
         'ref_sector': 'Healthcare'},
 'KRE': {'category': 'thematic',
         'subcategory': 'regional_banks',
         'smart_money': True,
         'region': 'US',
         'ref_sector': 'Financial Services'},
 'TQQQ': {'category': 'leveraged',
          'subcategory': '3x_qqq_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'SQQQ': {'category': 'leveraged',
          'subcategory': '3x_qqq_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'SOXL': {'category': 'leveraged',
          'subcategory': '3x_semi_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'SOXS': {'category': 'leveraged',
          'subcategory': '3x_semi_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'TMF': {'category': 'leveraged',
         'subcategory': '3x_treasury',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'UVXY': {'category': 'leveraged',
          'subcategory': 'vol_long',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'SVXY': {'category': 'leveraged',
          'subcategory': 'vol_short',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'IBIT': {'category': 'crypto',
          'subcategory': 'bitcoin',
          'smart_money': True,
          'region': 'US',
          'ref_sector': None},
 'FBTC': {'category': 'crypto',
          'subcategory': 'bitcoin',
          'smart_money': True,
          'region': 'US',
          'ref_sector': None},
 'ETHA': {'category': 'crypto',
          'subcategory': 'ethereum',
          'smart_money': True,
          'region': 'US',
          'ref_sector': None},
 'BITO': {'category': 'crypto',
          'subcategory': 'bitcoin_futures',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'SPXL': {'category': 'leveraged',
          'subcategory': '3x_sp500_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'SPXS': {'category': 'leveraged',
          'subcategory': '3x_sp500_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'UPRO': {'category': 'leveraged',
          'subcategory': '3x_sp500_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'SPXU': {'category': 'leveraged',
          'subcategory': '3x_sp500_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'SSO': {'category': 'leveraged',
         'subcategory': '2x_sp500_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'SDS': {'category': 'leveraged',
         'subcategory': '2x_sp500_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'SH': {'category': 'leveraged',
        'subcategory': '1x_sp500_bear',
        'smart_money': False,
        'region': 'US',
        'ref_sector': None},
 'UDOW': {'category': 'leveraged',
          'subcategory': '3x_dow_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'SDOW': {'category': 'leveraged',
          'subcategory': '3x_dow_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'QLD': {'category': 'leveraged',
         'subcategory': '2x_qqq_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'QID': {'category': 'leveraged',
         'subcategory': '2x_qqq_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'TNA': {'category': 'leveraged',
         'subcategory': '3x_smallcap_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'TZA': {'category': 'leveraged',
         'subcategory': '3x_smallcap_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'UWM': {'category': 'leveraged',
         'subcategory': '2x_smallcap_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'TWM': {'category': 'leveraged',
         'subcategory': '2x_smallcap_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'TECL': {'category': 'leveraged',
          'subcategory': '3x_tech_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'TECS': {'category': 'leveraged',
          'subcategory': '3x_tech_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'FAS': {'category': 'leveraged',
         'subcategory': '3x_financials_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'FAZ': {'category': 'leveraged',
         'subcategory': '3x_financials_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'ERX': {'category': 'leveraged',
         'subcategory': '3x_energy_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'ERY': {'category': 'leveraged',
         'subcategory': '3x_energy_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'GUSH': {'category': 'leveraged',
          'subcategory': '2x_oilgas_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'DRIP': {'category': 'leveraged',
          'subcategory': '2x_oilgas_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'LABU': {'category': 'leveraged',
          'subcategory': '3x_biotech_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'LABD': {'category': 'leveraged',
          'subcategory': '3x_biotech_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'CURE': {'category': 'leveraged',
          'subcategory': '3x_healthcare_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'DRN': {'category': 'leveraged',
         'subcategory': '3x_realestate_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'DRV': {'category': 'leveraged',
         'subcategory': '3x_realestate_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'UTSL': {'category': 'leveraged',
          'subcategory': '3x_utilities_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'DUSL': {'category': 'leveraged',
          'subcategory': '3x_industrials_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'DPST': {'category': 'leveraged',
          'subcategory': '3x_regionalbank_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'RETL': {'category': 'leveraged',
          'subcategory': '3x_retail_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'DFEN': {'category': 'leveraged',
          'subcategory': '3x_defense_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'NAIL': {'category': 'leveraged',
          'subcategory': '3x_homebuilder_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'WANT': {'category': 'leveraged',
          'subcategory': '3x_discretionary_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'PILL': {'category': 'leveraged',
          'subcategory': '3x_pharma_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'WEBL': {'category': 'leveraged',
          'subcategory': '3x_internet_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'WEBS': {'category': 'leveraged',
          'subcategory': '3x_internet_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'CWEB': {'category': 'leveraged',
          'subcategory': '2x_chinainternet_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'YINN': {'category': 'leveraged',
          'subcategory': '3x_china_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'YANG': {'category': 'leveraged',
          'subcategory': '3x_china_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'NUGT': {'category': 'leveraged',
          'subcategory': '2x_goldminers_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'DUST': {'category': 'leveraged',
          'subcategory': '2x_goldminers_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'JNUG': {'category': 'leveraged',
          'subcategory': '2x_juniorgold_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'JDST': {'category': 'leveraged',
          'subcategory': '2x_juniorgold_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'UGL': {'category': 'leveraged',
         'subcategory': '2x_gold_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'GLL': {'category': 'leveraged',
         'subcategory': '2x_gold_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'AGQ': {'category': 'leveraged',
         'subcategory': '2x_silver_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'ZSL': {'category': 'leveraged',
         'subcategory': '2x_silver_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'UCO': {'category': 'leveraged',
         'subcategory': '2x_crude_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'SCO': {'category': 'leveraged',
         'subcategory': '2x_crude_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'BOIL': {'category': 'leveraged',
          'subcategory': '2x_natgas_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'KOLD': {'category': 'leveraged',
          'subcategory': '2x_natgas_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'TMV': {'category': 'leveraged',
         'subcategory': '3x_treasury_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'TYD': {'category': 'leveraged',
         'subcategory': '3x_7_10yr_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'TYO': {'category': 'leveraged',
         'subcategory': '3x_7_10yr_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'BITX': {'category': 'leveraged',
          'subcategory': '2x_bitcoin_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'BITI': {'category': 'leveraged',
          'subcategory': '1x_bitcoin_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'ETHU': {'category': 'leveraged',
          'subcategory': '2x_ethereum_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'NVDL': {'category': 'leveraged',
          'subcategory': '2x_nvda_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'NVDS': {'category': 'leveraged',
          'subcategory': '1x_nvda_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'TSLL': {'category': 'leveraged',
          'subcategory': '2x_tsla_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'TSLQ': {'category': 'leveraged',
          'subcategory': '1x_tsla_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'CONL': {'category': 'leveraged',
          'subcategory': '2x_coin_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'MSTU': {'category': 'leveraged',
          'subcategory': '2x_mstr_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'VGT': {'category': 'thematic',
         'subcategory': 'technology',
         'smart_money': False,
         'region': 'US',
         'ref_sector': 'Technology'},
 'IGV': {'category': 'thematic',
         'subcategory': 'software',
         'smart_money': False,
         'region': 'US',
         'ref_sector': 'Technology'},
 'WCLD': {'category': 'thematic',
          'subcategory': 'cloud',
          'smart_money': False,
          'region': 'US',
          'ref_sector': 'Technology'},
 'SKYY': {'category': 'thematic',
          'subcategory': 'cloud',
          'smart_money': False,
          'region': 'US',
          'ref_sector': 'Technology'},
 'XOP': {'category': 'thematic',
         'subcategory': 'oil_gas_ep',
         'smart_money': False,
         'region': 'US',
         'ref_sector': 'Energy'},
 'OIH': {'category': 'thematic',
         'subcategory': 'oil_services',
         'smart_money': False,
         'region': 'US',
         'ref_sector': 'Energy'},
 'GDX': {'category': 'thematic',
         'subcategory': 'gold_miners',
         'smart_money': False,
         'region': 'US',
         'ref_sector': 'Basic Materials'},
 'GDXJ': {'category': 'thematic',
          'subcategory': 'junior_gold_miners',
          'smart_money': False,
          'region': 'US',
          'ref_sector': 'Basic Materials'},
 'XME': {'category': 'thematic',
         'subcategory': 'metals_mining',
         'smart_money': False,
         'region': 'US',
         'ref_sector': 'Basic Materials'},
 'COPX': {'category': 'thematic',
          'subcategory': 'copper_miners',
          'smart_money': False,
          'region': 'US',
          'ref_sector': 'Basic Materials'},
 'URA': {'category': 'thematic',
         'subcategory': 'uranium',
         'smart_money': False,
         'region': 'US',
         'ref_sector': 'Energy'},
 'URNM': {'category': 'thematic',
          'subcategory': 'uranium_miners',
          'smart_money': False,
          'region': 'US',
          'ref_sector': 'Energy'},
 'ITB': {'category': 'thematic',
         'subcategory': 'homebuilders',
         'smart_money': False,
         'region': 'US',
         'ref_sector': 'Consumer Cyclical'},
 'XHB': {'category': 'thematic',
         'subcategory': 'homebuilders',
         'smart_money': False,
         'region': 'US',
         'ref_sector': 'Consumer Cyclical'},
 'JETS': {'category': 'thematic',
          'subcategory': 'airlines',
          'smart_money': False,
          'region': 'US',
          'ref_sector': 'Industrials'},
 'IYT': {'category': 'thematic',
         'subcategory': 'transports',
         'smart_money': False,
         'region': 'US',
         'ref_sector': 'Industrials'},
 'PAVE': {'category': 'thematic',
          'subcategory': 'infrastructure',
          'smart_money': False,
          'region': 'US',
          'ref_sector': 'Industrials'},
 'KBE': {'category': 'thematic',
         'subcategory': 'banks',
         'smart_money': False,
         'region': 'US',
         'ref_sector': 'Financial Services'},
 'XRT': {'category': 'thematic',
         'subcategory': 'retail',
         'smart_money': False,
         'region': 'US',
         'ref_sector': 'Consumer Cyclical'},
 'BOTZ': {'category': 'thematic',
          'subcategory': 'robotics_ai',
          'smart_money': False,
          'region': 'US',
          'ref_sector': 'Technology'},
 'ITA': {'category': 'thematic',
         'subcategory': 'aerospace_defense',
         'smart_money': False,
         'region': 'US',
         'ref_sector': 'Industrials'},
 'KARS': {'category': 'thematic',
          'subcategory': 'electric_vehicles',
          'smart_money': False,
          'region': 'US',
          'ref_sector': 'Consumer Cyclical'},
 'HACK': {'category': 'thematic',
          'subcategory': 'cybersecurity',
          'smart_money': False,
          'region': 'US',
          'ref_sector': 'Technology'},
 'CIBR': {'category': 'thematic',
          'subcategory': 'cybersecurity',
          'smart_money': False,
          'region': 'US',
          'ref_sector': 'Technology'},
 'ARKB': {'category': 'thematic',
          'subcategory': 'bitcoin',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'AMDL': {'category': 'leveraged',
          'subcategory': '2x_amd_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'AMDD': {'category': 'leveraged',
          'subcategory': '1x_amd_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'GGLL': {'category': 'leveraged',
          'subcategory': '2x_googl_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'AAPU': {'category': 'leveraged',
          'subcategory': '2x_aapl_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'AAPD': {'category': 'leveraged',
          'subcategory': '1x_aapl_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'METU': {'category': 'leveraged',
          'subcategory': '2x_meta_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'AMZU': {'category': 'leveraged',
          'subcategory': '2x_amzn_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'MSFU': {'category': 'leveraged',
          'subcategory': '2x_msft_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'PLTU': {'category': 'leveraged',
          'subcategory': '2x_pltr_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'MSTZ': {'category': 'leveraged',
          'subcategory': '1x_mstr_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'SMCL': {'category': 'leveraged',
          'subcategory': '2x_smci_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'AVGX': {'category': 'leveraged',
          'subcategory': '2x_avgo_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'FNGU': {'category': 'leveraged',
          'subcategory': '3x_fangplus_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'FNGD': {'category': 'leveraged',
          'subcategory': '3x_fangplus_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'BULZ': {'category': 'leveraged',
          'subcategory': '3x_fang_innovation_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'BERZ': {'category': 'leveraged',
          'subcategory': '3x_fang_innovation_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'DDM': {'category': 'leveraged',
         'subcategory': '2x_dow_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'DXD': {'category': 'leveraged',
         'subcategory': '2x_dow_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'DOG': {'category': 'leveraged',
         'subcategory': '1x_dow_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'PSQ': {'category': 'leveraged',
         'subcategory': '1x_qqq_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'SPUU': {'category': 'leveraged',
          'subcategory': '2x_sp500_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'HIBL': {'category': 'leveraged',
          'subcategory': '3x_highbeta_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'HIBS': {'category': 'leveraged',
          'subcategory': '3x_highbeta_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'MIDU': {'category': 'leveraged',
          'subcategory': '3x_midcap_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'MVV': {'category': 'leveraged',
         'subcategory': '2x_midcap_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'MZZ': {'category': 'leveraged',
         'subcategory': '2x_midcap_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'RWM': {'category': 'leveraged',
         'subcategory': '1x_smallcap_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'SAA': {'category': 'leveraged',
         'subcategory': '2x_smallcap_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'ROM': {'category': 'leveraged',
         'subcategory': '2x_tech_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'REW': {'category': 'leveraged',
         'subcategory': '2x_tech_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'USD': {'category': 'leveraged',
         'subcategory': '2x_semi_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'SSG': {'category': 'leveraged',
         'subcategory': '2x_semi_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'UYG': {'category': 'leveraged',
         'subcategory': '2x_financials_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'SKF': {'category': 'leveraged',
         'subcategory': '2x_financials_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'DIG': {'category': 'leveraged',
         'subcategory': '2x_energy_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'DUG': {'category': 'leveraged',
         'subcategory': '2x_energy_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'RXL': {'category': 'leveraged',
         'subcategory': '2x_healthcare_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'BIB': {'category': 'leveraged',
         'subcategory': '2x_biotech_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'BIS': {'category': 'leveraged',
         'subcategory': '2x_biotech_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'UXI': {'category': 'leveraged',
         'subcategory': '2x_industrials_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'UCC': {'category': 'leveraged',
         'subcategory': '2x_discretionary_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'URE': {'category': 'leveraged',
         'subcategory': '2x_realestate_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'SRS': {'category': 'leveraged',
         'subcategory': '2x_realestate_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'UYM': {'category': 'leveraged',
         'subcategory': '2x_materials_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'SMN': {'category': 'leveraged',
         'subcategory': '2x_materials_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'UPW': {'category': 'leveraged',
         'subcategory': '2x_utilities_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'EDC': {'category': 'leveraged',
         'subcategory': '3x_em_bull',
         'smart_money': False,
         'region': 'EM',
         'ref_sector': None},
 'EDZ': {'category': 'leveraged',
         'subcategory': '3x_em_bear',
         'smart_money': False,
         'region': 'EM',
         'ref_sector': None},
 'EURL': {'category': 'leveraged',
          'subcategory': '3x_europe_bull',
          'smart_money': False,
          'region': 'Intl',
          'ref_sector': None},
 'INDL': {'category': 'leveraged',
          'subcategory': '2x_india_bull',
          'smart_money': False,
          'region': 'EM',
          'ref_sector': None},
 'BRZU': {'category': 'leveraged',
          'subcategory': '2x_brazil_bull',
          'smart_money': False,
          'region': 'EM',
          'ref_sector': None},
 'KORU': {'category': 'leveraged',
          'subcategory': '3x_korea_bull',
          'smart_money': False,
          'region': 'EM',
          'ref_sector': None},
 'MEXX': {'category': 'leveraged',
          'subcategory': '3x_mexico_bull',
          'smart_money': False,
          'region': 'EM',
          'ref_sector': None},
 'TPOR': {'category': 'leveraged',
          'subcategory': '3x_transports_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'UUP': {'category': 'fx',
         'subcategory': 'usd_bull',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'UDN': {'category': 'fx',
         'subcategory': 'usd_bear',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'EUO': {'category': 'fx',
         'subcategory': '2x_euro_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'ULE': {'category': 'fx',
         'subcategory': '2x_euro_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'YCS': {'category': 'fx',
         'subcategory': '2x_yen_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'BITU': {'category': 'leveraged',
          'subcategory': '2x_bitcoin_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'SBIT': {'category': 'leveraged',
          'subcategory': '2x_bitcoin_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'ETHT': {'category': 'leveraged',
          'subcategory': '2x_ethereum_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'MSTX': {'category': 'leveraged',
          'subcategory': '2x_mstr_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'TSLR': {'category': 'leveraged',
          'subcategory': '2x_tsla_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'TSLS': {'category': 'leveraged',
          'subcategory': '2x_tsla_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'NVDX': {'category': 'leveraged',
          'subcategory': '2x_nvda_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'NVDU': {'category': 'leveraged',
          'subcategory': '2x_nvda_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'GGLS': {'category': 'leveraged',
          'subcategory': '1x_googl_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'METD': {'category': 'leveraged',
          'subcategory': '1x_meta_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'AMZD': {'category': 'leveraged',
          'subcategory': '1x_amzn_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'MSFD': {'category': 'leveraged',
          'subcategory': '1x_msft_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'CONI': {'category': 'leveraged',
          'subcategory': '1x_coin_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'MUU': {'category': 'leveraged',
         'subcategory': '2x_mu_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'MUD': {'category': 'leveraged',
         'subcategory': '2x_mu_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'NFXL': {'category': 'leveraged',
          'subcategory': '2x_nflx_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'NFXS': {'category': 'leveraged',
          'subcategory': '2x_nflx_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'BABX': {'category': 'leveraged',
          'subcategory': '2x_baba_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'TSMX': {'category': 'leveraged',
          'subcategory': '2x_tsm_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'BRKU': {'category': 'leveraged',
          'subcategory': '2x_brk_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'CRWL': {'category': 'leveraged',
          'subcategory': '2x_crwd_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'HOOX': {'category': 'leveraged',
          'subcategory': '2x_hood_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'AVL': {'category': 'leveraged',
         'subcategory': '2x_avgo_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'AAPB': {'category': 'leveraged',
          'subcategory': '2x_aapl_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'NVDD': {'category': 'leveraged',
          'subcategory': '2x_nvda_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'SMCX': {'category': 'leveraged',
          'subcategory': '2x_smci_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'PLTD': {'category': 'leveraged',
          'subcategory': '2x_pltr_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'COII': {'category': 'leveraged',
          'subcategory': '2x_coin_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'AMUU': {'category': 'leveraged',
          'subcategory': '2x_amzn_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'TSLZ': {'category': 'leveraged',
          'subcategory': '2x_tsla_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'URTY': {'category': 'leveraged',
          'subcategory': '3x_r2000_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'SRTY': {'category': 'leveraged',
          'subcategory': '3x_r2000_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'UMDD': {'category': 'leveraged',
          'subcategory': '3x_midcap_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'SMDD': {'category': 'leveraged',
          'subcategory': '3x_midcap_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'QQQU': {'category': 'leveraged',
          'subcategory': '2x_qqq_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'TTT': {'category': 'leveraged',
         'subcategory': '3x_20y_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'XLG': {'category': 'broad',
         'subcategory': 'us_megacap',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'IJH': {'category': 'broad',
         'subcategory': 'us_mid_cap',
         'smart_money': True,
         'region': 'US',
         'ref_sector': None},
 'FTEC': {'category': 'sector',
          'subcategory': 'technology',
          'smart_money': True,
          'region': 'US',
          'ref_sector': 'Technology'},
 'RXD': {'category': 'leveraged',
         'subcategory': '2x_health_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'SDP': {'category': 'leveraged',
         'subcategory': '2x_utilities_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'SIJ': {'category': 'leveraged',
         'subcategory': '2x_industrials_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'UGE': {'category': 'leveraged',
         'subcategory': '2x_staples_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'SZK': {'category': 'leveraged',
         'subcategory': '2x_staples_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'SCC': {'category': 'leveraged',
         'subcategory': '2x_discretionary_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'XSD': {'category': 'sector',
         'subcategory': 'semiconductors',
         'smart_money': True,
         'region': 'US',
         'ref_sector': 'Technology'},
 'TBT': {'category': 'leveraged',
         'subcategory': '2x_20y_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'UBT': {'category': 'leveraged',
         'subcategory': '2x_20y_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'TBF': {'category': 'leveraged',
         'subcategory': '1x_20y_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'PST': {'category': 'leveraged',
         'subcategory': '2x_7-10y_bear',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'UST': {'category': 'leveraged',
         'subcategory': '2x_7-10y_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'GDXU': {'category': 'leveraged',
          'subcategory': '2x_goldminers_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'GDXD': {'category': 'leveraged',
          'subcategory': '2x_goldminers_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'BTCL': {'category': 'leveraged',
          'subcategory': '2x_btc_bull',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'ETU': {'category': 'leveraged',
         'subcategory': '2x_eth_bull',
         'smart_money': False,
         'region': 'US',
         'ref_sector': None},
 'ETHD': {'category': 'leveraged',
          'subcategory': '2x_eth_bear',
          'smart_money': False,
          'region': 'US',
          'ref_sector': None},
 'CHAU': {'category': 'leveraged',
          'subcategory': '2x_china_bull',
          'smart_money': False,
          'region': 'CN',
          'ref_sector': None},
 'XPP': {'category': 'leveraged',
         'subcategory': '2x_china_bull',
         'smart_money': False,
         'region': 'CN',
         'ref_sector': None},
 'FXP': {'category': 'leveraged',
         'subcategory': '2x_china_bear',
         'smart_money': False,
         'region': 'CN',
         'ref_sector': None},
 'BUG': {'category': 'sector',
         'subcategory': 'cybersecurity',
         'smart_money': True,
         'region': 'US',
         'ref_sector': 'Technology'},
 'QTUM': {'category': 'sector',
          'subcategory': 'quantum',
          'smart_money': True,
          'region': 'US',
          'ref_sector': 'Technology'},
 'ROBO': {'category': 'sector',
          'subcategory': 'robotics',
          'smart_money': True,
          'region': 'US',
          'ref_sector': 'Technology'},
 'MSOS': {'category': 'sector',
          'subcategory': 'cannabis',
          'smart_money': True,
          'region': 'US',
          'ref_sector': 'Healthcare'},
 'NLR': {'category': 'sector',
         'subcategory': 'nuclear',
         'smart_money': True,
         'region': 'US',
         'ref_sector': 'Utilities'},
 'PPA': {'category': 'sector',
         'subcategory': 'defense',
         'smart_money': True,
         'region': 'US',
         'ref_sector': 'Industrials'},
 'ARKX': {'category': 'sector',
          'subcategory': 'space',
          'smart_money': True,
          'region': 'US',
          'ref_sector': 'Industrials'},
 'PHO': {'category': 'sector',
         'subcategory': 'water',
         'smart_money': True,
         'region': 'US',
         'ref_sector': 'Utilities'}}

COMPLEXES = {'Semiconductors': {'core': ['SMH', 'SOXX', 'XSD'],
                    'bull': ['SOXL', 'USD'],
                    'bear': ['SOXS', 'SSG'],
                    'primary': 'SMH',
                    'stocks': ['NVDA',
                               'AMD',
                               'AVGO',
                               'MU',
                               'TSM',
                               'LRCX',
                               'AMAT',
                               'KLAC',
                               'MRVL',
                               'ON',
                               'ARM',
                               'SMCI']},
 'Technology': {'core': ['XLK', 'QQQ', 'VGT', 'FTEC'],
                'bull': ['TQQQ', 'TECL', 'ROM', 'QQQU'],
                'bear': ['SQQQ', 'TECS', 'REW'],
                'primary': 'XLK',
                'stocks': ['AAPL', 'MSFT', 'NVDA', 'AVGO', 'ORCL', 'CRM', 'ADBE', 'AMD']},
 'Software': {'core': ['IGV', 'WCLD', 'SKYY'],
              'bull': [],
              'bear': [],
              'primary': 'IGV',
              'stocks': ['MSFT', 'CRM', 'NOW', 'ADBE', 'SNOW', 'PLTR', 'DDOG', 'NET']},
 'Biotech': {'core': ['XBI', 'IBB'],
             'bull': ['LABU', 'BIB'],
             'bear': ['LABD', 'BIS'],
             'primary': 'XBI',
             'stocks': ['VRTX', 'REGN', 'GILD', 'AMGN', 'MRNA', 'BIIB', 'ALNY']},
 'Energy': {'core': ['XLE', 'XOP', 'OIH'],
            'bull': ['ERX', 'GUSH', 'DIG'],
            'bear': ['ERY', 'DRIP', 'DUG'],
            'primary': 'XLE',
            'stocks': ['XOM', 'CVX', 'COP', 'SLB', 'EOG', 'OXY', 'FANG', 'PSX']},
 'Oil': {'core': ['USO'], 'bull': ['UCO'], 'bear': ['SCO'], 'primary': 'USO', 'stocks': []},
 'Natural Gas': {'core': ['UNG'], 'bull': ['BOIL'], 'bear': ['KOLD'], 'primary': 'UNG', 'stocks': []},
 'Financials': {'core': ['XLF', 'KRE', 'KBE'],
                'bull': ['FAS', 'DPST', 'UYG'],
                'bear': ['FAZ', 'SKF'],
                'primary': 'XLF',
                'stocks': ['JPM', 'BAC', 'WFC', 'GS', 'MS', 'C', 'SCHW']},
 'Clean Energy': {'core': ['ICLN', 'TAN'],
                  'bull': [],
                  'bear': [],
                  'primary': 'TAN',
                  'stocks': ['FSLR', 'ENPH', 'SEDG', 'RUN', 'NEE', 'STEM']},
 'China': {'core': ['KWEB', 'FXI', 'MCHI'],
           'bull': ['YINN', 'CWEB', 'CHAU', 'XPP'],
           'bear': ['YANG', 'FXP'],
           'primary': 'KWEB',
           'stocks': ['BABA', 'PDD', 'JD', 'BIDU', 'NIO', 'LI', 'XPEV']},
 'Innovation/ARK': {'core': ['ARKK', 'ARKW', 'ARKG'],
                    'bull': [],
                    'bear': [],
                    'primary': 'ARKK',
                    'stocks': ['TSLA', 'COIN', 'ROKU', 'HOOD', 'PLTR', 'RBLX']},
 'Crypto': {'core': ['IBIT', 'FBTC', 'BITO', 'ETHA', 'ARKB'],
            'bull': ['BITX', 'ETHU', 'BITU', 'ETHT', 'BTCL', 'ETU'],
            'bear': ['BITI', 'SBIT', 'ETHD'],
            'primary': 'IBIT',
            'stocks': ['COIN', 'MSTR', 'MARA', 'RIOT', 'CLSK', 'HUT']},
 'Gold': {'core': ['GLD', 'IAU'],
          'bull': ['UGL'],
          'bear': ['GLL'],
          'primary': 'GLD',
          'stocks': ['NEM', 'GOLD', 'AEM', 'WPM', 'FNV']},
 'Gold Miners': {'core': ['GDX', 'GDXJ'],
                 'bull': ['NUGT', 'JNUG', 'GDXU'],
                 'bear': ['DUST', 'JDST', 'GDXD'],
                 'primary': 'GDX',
                 'stocks': ['NEM', 'GOLD', 'AEM', 'WPM', 'AU']},
 'Silver': {'core': ['SLV'],
            'bull': ['AGQ'],
            'bear': ['ZSL'],
            'primary': 'SLV',
            'stocks': ['PAAS', 'AG', 'HL']},
 'Copper/Mining': {'core': ['COPX', 'XME', 'CPER'],
                   'bull': [],
                   'bear': [],
                   'primary': 'XME',
                   'stocks': ['FCX', 'SCCO', 'TECK', 'VALE', 'RIO']},
 'Uranium': {'core': ['URA', 'URNM', 'NLR'],
             'bull': [],
             'bear': [],
             'primary': 'URA',
             'stocks': ['CCJ', 'UEC', 'DNN', 'NXE', 'UUUU']},
 'Homebuilders': {'core': ['ITB', 'XHB'],
                  'bull': ['NAIL'],
                  'bear': [],
                  'primary': 'ITB',
                  'stocks': ['DHI', 'LEN', 'PHM', 'NVR', 'TOL', 'KBH']},
 'Retail': {'core': ['XRT'],
            'bull': ['RETL'],
            'bear': [],
            'primary': 'XRT',
            'stocks': ['AMZN', 'WMT', 'COST', 'TGT', 'HD', 'LOW']},
 'Small Caps': {'core': ['IWM'],
                'bull': ['TNA', 'UWM', 'SAA', 'URTY'],
                'bear': ['TZA', 'TWM', 'RWM', 'SRTY'],
                'primary': 'IWM',
                'stocks': []},
 'S&P 500 Broad': {'core': ['SPY', 'VOO', 'IVV'],
                   'bull': ['SPXL', 'UPRO', 'SSO', 'SPUU'],
                   'bear': ['SPXS', 'SPXU', 'SDS', 'SH'],
                   'primary': 'SPY',
                   'stocks': []},
 'Nasdaq Broad': {'core': ['QQQ'],
                  'bull': ['TQQQ', 'QLD'],
                  'bear': ['SQQQ', 'QID', 'PSQ'],
                  'primary': 'QQQ',
                  'stocks': []},
 'Dow': {'core': ['DIA'],
         'bull': ['UDOW', 'DDM'],
         'bear': ['SDOW', 'DXD', 'DOG'],
         'primary': 'DIA',
         'stocks': []},
 'Industrials': {'core': ['XLI', 'PAVE'],
                 'bull': ['DUSL', 'UXI'],
                 'bear': ['SIJ'],
                 'primary': 'XLI',
                 'stocks': ['CAT', 'DE', 'GE', 'HON', 'UNP', 'BA']},
 'Aerospace/Defense': {'core': ['ITA', 'PPA', 'ARKX'],
                       'bull': ['DFEN'],
                       'bear': [],
                       'primary': 'ITA',
                       'stocks': ['RTX', 'LMT', 'NOC', 'GD', 'BA', 'LHX']},
 'Transports': {'core': ['IYT'],
                'bull': ['TPOR'],
                'bear': [],
                'primary': 'IYT',
                'stocks': ['UPS', 'FDX', 'UNP', 'CSX', 'NSC', 'ODFL']},
 'Airlines': {'core': ['JETS'],
              'bull': [],
              'bear': [],
              'primary': 'JETS',
              'stocks': ['DAL', 'UAL', 'AAL', 'LUV', 'ALK']},
 'Materials': {'core': ['XLB'],
               'bull': ['UYM'],
               'bear': ['SMN'],
               'primary': 'XLB',
               'stocks': ['LIN', 'FCX', 'NEM', 'SHW', 'APD']},
 'Healthcare': {'core': ['XLV'],
                'bull': ['CURE', 'RXL'],
                'bear': ['RXD'],
                'primary': 'XLV',
                'stocks': ['UNH', 'JNJ', 'LLY', 'ABBV', 'MRK', 'PFE']},
 'Consumer Discretionary': {'core': ['XLY'],
                            'bull': ['WANT', 'UCC'],
                            'bear': ['SCC'],
                            'primary': 'XLY',
                            'stocks': ['AMZN', 'TSLA', 'HD', 'MCD', 'NKE', 'LOW']},
 'Consumer Staples': {'core': ['XLP'],
                      'bull': ['UGE'],
                      'bear': ['SZK'],
                      'primary': 'XLP',
                      'stocks': ['PG', 'KO', 'PEP', 'COST', 'WMT']},
 'Utilities': {'core': ['XLU', 'PHO'],
               'bull': ['UTSL', 'UPW'],
               'bear': ['SDP'],
               'primary': 'XLU',
               'stocks': ['NEE', 'DUK', 'SO', 'D', 'AEP']},
 'Real Estate': {'core': ['XLRE'],
                 'bull': ['DRN', 'URE'],
                 'bear': ['DRV', 'SRS'],
                 'primary': 'XLRE',
                 'stocks': ['PLD', 'AMT', 'EQIX', 'SPG', 'O']},
 'Communications/Internet': {'core': ['XLC'],
                             'bull': ['WEBL'],
                             'bear': ['WEBS'],
                             'primary': 'XLC',
                             'stocks': ['GOOGL', 'META', 'NFLX', 'DIS', 'TMUS']},
 'Mega-Cap Tech (FANG+)': {'core': ['QQQ'],
                           'bull': ['FNGU', 'BULZ'],
                           'bear': ['FNGD', 'BERZ'],
                           'primary': 'QQQ',
                           'stocks': ['AAPL',
                                      'MSFT',
                                      'NVDA',
                                      'AMZN',
                                      'META',
                                      'GOOGL',
                                      'NFLX',
                                      'AVGO',
                                      'TSLA']},
 'Europe': {'core': ['EFA', 'VEA', 'EWG', 'EWU'],
            'bull': ['EURL'],
            'bear': [],
            'primary': 'EFA',
            'stocks': []},
 'Emerging Markets': {'core': ['EEM', 'VWO'],
                      'bull': ['EDC'],
                      'bear': ['EDZ'],
                      'primary': 'EEM',
                      'stocks': []},
 'India': {'core': ['INDA'], 'bull': ['INDL'], 'bear': [], 'primary': 'INDA', 'stocks': []},
 'Brazil': {'core': ['EWZ'],
            'bull': ['BRZU'],
            'bear': [],
            'primary': 'EWZ',
            'stocks': ['VALE', 'PBR', 'ITUB', 'NU']},
 'Long Treasuries (20Y)': {'core': ['TLT'],
                           'bull': ['TMF', 'UBT'],
                           'bear': ['TMV', 'TBT', 'TTT', 'TBF'],
                           'primary': 'TLT',
                           'stocks': []},
 'Intermediate Treasuries (7-10Y)': {'core': ['IEF'],
                                     'bull': ['TYD', 'UST'],
                                     'bear': ['TYO', 'PST'],
                                     'primary': 'IEF',
                                     'stocks': []},
 'Cybersecurity': {'core': ['CIBR', 'HACK', 'BUG'],
                   'bull': [],
                   'bear': [],
                   'primary': 'CIBR',
                   'stocks': ['PANW', 'CRWD', 'ZS', 'FTNT', 'NET', 'S', 'OKTA']},
 'Mid Caps': {'core': ['IJH'],
              'bull': ['MIDU', 'MVV', 'UMDD'],
              'bear': ['MZZ', 'SMDD'],
              'primary': 'IJH',
              'stocks': []},
 'Cannabis': {'core': ['MSOS'],
              'bull': [],
              'bear': [],
              'primary': 'MSOS',
              'stocks': ['TLRY', 'CGC', 'CRON', 'GTBIF', 'CURLF']},
 'Quantum Computing': {'core': ['QTUM'],
                       'bull': [],
                       'bear': [],
                       'primary': 'QTUM',
                       'stocks': ['IONQ', 'RGTI', 'QBTS', 'QUBT', 'IBM']},
 'Robotics/AI': {'core': ['BOTZ', 'ROBO'],
                 'bull': [],
                 'bear': [],
                 'primary': 'BOTZ',
                 'stocks': ['NVDA', 'ISRG', 'ABB', 'ROK', 'TER']}}

SINGLE_STOCK_LEV = {'NVDA': {'bull': ['NVDL', 'NVDX', 'NVDU'], 'bear': ['NVDS', 'NVDD']},
 'TSLA': {'bull': ['TSLL', 'TSLR'], 'bear': ['TSLQ', 'TSLS', 'TSLZ']},
 'AAPL': {'bull': ['AAPU', 'AAPB'], 'bear': ['AAPD']},
 'META': {'bull': ['METU'], 'bear': ['METD']},
 'AMZN': {'bull': ['AMZU', 'AMUU'], 'bear': ['AMZD']},
 'MSFT': {'bull': ['MSFU'], 'bear': ['MSFD']},
 'AMD': {'bull': ['AMDL'], 'bear': ['AMDD']},
 'GOOGL': {'bull': ['GGLL'], 'bear': ['GGLS']},
 'MSTR': {'bull': ['MSTU', 'MSTX'], 'bear': ['MSTZ']},
 'COIN': {'bull': ['CONL'], 'bear': ['CONI', 'COII']},
 'PLTR': {'bull': ['PLTU'], 'bear': ['PLTD']},
 'SMCI': {'bull': ['SMCL', 'SMCX'], 'bear': []},
 'AVGO': {'bull': ['AVGX', 'AVL'], 'bear': []},
 'MU': {'bull': ['MUU'], 'bear': ['MUD']},
 'NFLX': {'bull': ['NFXL'], 'bear': ['NFXS']},
 'BABA': {'bull': ['BABX'], 'bear': []},
 'TSM': {'bull': ['TSMX'], 'bear': []},
 'BRK': {'bull': ['BRKU'], 'bear': []},
 'CRWD': {'bull': ['CRWL'], 'bear': []},
 'HOOD': {'bull': ['HOOX'], 'bear': []}}
