"""Complete predecessor requests and reviewed official definition boundaries.

Metadata comes from accepted operations 6121 and 6124, not legacy labels.
None is an unreviewed original identity, never permission to guess its unit.
"""
SPECS = {'WALCL': {'group': 'fed_balance_sheet',
           'legacy_label': 'Fed Total Assets',
           'legacy_unit': 'B USD',
           'legacy_frequency': 'w',
           'reviewed_definition': ('Millions of U.S. Dollars',
                                   'W',
                                   'Weekly, As of Wednesday',
                                   'Not Seasonally Adjusted')},
 'WTREGEN': {'group': 'tga',
             'legacy_label': 'Treasury General Account (TGA)',
             'legacy_unit': 'B USD',
             'legacy_frequency': 'w',
             'reviewed_definition': ('Millions of U.S. Dollars',
                                     'W',
                                     'Weekly, Ending Wednesday',
                                     'Not Seasonally Adjusted')},
 'RRPONTSYD': {'group': 'rrp',
               'legacy_label': 'Fed Reverse Repo (RRP)',
               'legacy_unit': 'B USD',
               'legacy_frequency': 'd',
               'reviewed_definition': ('Billions of US Dollars', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'WSHOSHO': {'group': 'soma',
             'legacy_label': 'SOMA Holdings Total',
             'legacy_unit': 'B USD',
             'legacy_frequency': 'w',
             'reviewed_definition': ('Millions of U.S. Dollars',
                                     'W',
                                     'Weekly, As of Wednesday',
                                     'Not Seasonally Adjusted')},
 'WSHOTSL': {'group': 'soma',
             'legacy_label': 'SOMA Treasury Securities',
             'legacy_unit': 'B USD',
             'legacy_frequency': 'w',
             'reviewed_definition': ('Millions of U.S. Dollars',
                                     'W',
                                     'Weekly, As of Wednesday',
                                     'Not Seasonally Adjusted')},
 'WSHOMCB': {'group': 'soma',
             'legacy_label': 'SOMA MBS Holdings',
             'legacy_unit': 'B USD',
             'legacy_frequency': 'w',
             'reviewed_definition': ('Millions of U.S. Dollars',
                                     'W',
                                     'Weekly, As of Wednesday',
                                     'Not Seasonally Adjusted')},
 'WRESBAL': {'group': 'reserves',
             'legacy_label': 'Reserve Balances at Fed',
             'legacy_unit': 'B USD',
             'legacy_frequency': 'w',
             'reviewed_definition': ('Millions of U.S. Dollars',
                                     'W',
                                     'Weekly, Ending Wednesday',
                                     'Not Seasonally Adjusted')},
 'TOTRESNS': {'group': 'reserves',
              'legacy_label': 'Total Reserves Depository Inst',
              'legacy_unit': 'B USD',
              'legacy_frequency': 'm',
              'reviewed_definition': ('Billions of Dollars', 'M', 'Monthly', 'Not Seasonally Adjusted')},
 'EXCSRESNW': {'group': 'reserves',
               'legacy_label': 'Excess Reserves (discontinued 2020)',
               'legacy_unit': 'B USD',
               'legacy_frequency': 'w',
               'reviewed_definition': None},
 'M2SL': {'group': 'money_supply',
          'legacy_label': 'M2 Money Supply',
          'legacy_unit': 'B USD',
          'legacy_frequency': 'm',
          'reviewed_definition': ('Billions of Dollars', 'M', 'Monthly', 'Seasonally Adjusted')},
 'M1SL': {'group': 'money_supply',
          'legacy_label': 'M1 Money Supply',
          'legacy_unit': 'B USD',
          'legacy_frequency': 'm',
          'reviewed_definition': ('Billions of Dollars', 'M', 'Monthly', 'Seasonally Adjusted')},
 'BOGMBASE': {'group': 'money_supply',
              'legacy_label': 'Monetary Base',
              'legacy_unit': 'B USD',
              'legacy_frequency': 'm',
              'reviewed_definition': ('Billions of Dollars', 'M', 'Monthly', 'Not Seasonally Adjusted')},
 'DTWEXBGS': {'group': 'dollar',
              'legacy_label': 'Nominal Broad US Dollar Index',
              'legacy_unit': 'Index',
              'legacy_frequency': 'd',
              'reviewed_definition': ('Index Jan 2006=100', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'DTWEXAFEGS': {'group': 'dollar',
                'legacy_label': 'Dollar vs Advanced Economies',
                'legacy_unit': 'Index',
                'legacy_frequency': 'd',
                'reviewed_definition': ('Index Jan 2006=100', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'DTWEXEMEGS': {'group': 'dollar',
                'legacy_label': 'Dollar vs Emerging Markets',
                'legacy_unit': 'Index',
                'legacy_frequency': 'd',
                'reviewed_definition': ('Index Jan 2006=100', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'DGS2': {'group': 'yields',
          'legacy_label': '2-Year Treasury Yield',
          'legacy_unit': '%',
          'legacy_frequency': 'd',
          'reviewed_definition': ('Percent', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'DGS10': {'group': 'yields',
           'legacy_label': '10-Year Treasury Yield',
           'legacy_unit': '%',
           'legacy_frequency': 'd',
           'reviewed_definition': ('Percent', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'DGS30': {'group': 'yields',
           'legacy_label': '30-Year Treasury Yield',
           'legacy_unit': '%',
           'legacy_frequency': 'd',
           'reviewed_definition': ('Percent', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'T10Y2Y': {'group': 'yields',
            'legacy_label': '10Y-2Y Yield Spread',
            'legacy_unit': '%',
            'legacy_frequency': 'd',
            'reviewed_definition': ('Percent', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'T10Y3M': {'group': 'yields',
            'legacy_label': '10Y-3M Yield Spread',
            'legacy_unit': '%',
            'legacy_frequency': 'd',
            'reviewed_definition': ('Percent', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'DFII10': {'group': 'yields',
            'legacy_label': '10Y TIPS (Real Yield)',
            'legacy_unit': '%',
            'legacy_frequency': 'd',
            'reviewed_definition': ('Percent', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'SOFR': {'group': 'funding',
          'legacy_label': 'SOFR Rate',
          'legacy_unit': '%',
          'legacy_frequency': 'd',
          'reviewed_definition': ('Percent', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'DFF': {'group': 'funding',
         'legacy_label': 'Fed Funds Effective Rate',
         'legacy_unit': '%',
         'legacy_frequency': 'd',
         'reviewed_definition': ('Percent', 'D', 'Daily, 7-Day', 'Not Seasonally Adjusted')},
 'DPCREDIT': {'group': 'funding',
              'legacy_label': 'Discount Window Primary Credit',
              'legacy_unit': '%',
              'legacy_frequency': 'd',
              'reviewed_definition': ('Percent', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'WORAL': {'group': 'fed_repo_assets',
           'legacy_label': 'Fed Overnight RRP Awards',
           'legacy_unit': 'B USD',
           'legacy_frequency': 'd',
           'reviewed_definition': ('Millions of U.S. Dollars',
                                   'W',
                                   'Weekly, As of Wednesday',
                                   'Not Seasonally Adjusted')},
 'TREAST': {'group': 'soma',
            'legacy_label': 'US Treasury Securities Held (total)',
            'legacy_unit': 'B USD',
            'legacy_frequency': 'w',
            'reviewed_definition': ('Millions of U.S. Dollars',
                                    'W',
                                    'Weekly, As of Wednesday',
                                    'Not Seasonally Adjusted')},
 'WSHONBIILB': {'group': 'soma',
                'legacy_label': 'SOMA TIPS Holdings',
                'legacy_unit': 'B USD',
                'legacy_frequency': 'w',
                'reviewed_definition': None},
 'WSHOBL': {'group': 'soma',
            'legacy_label': 'SOMA Treasury Bills',
            'legacy_unit': 'B USD',
            'legacy_frequency': 'w',
            'reviewed_definition': None},
 'WSHOFADSL': {'group': 'soma',
               'legacy_label': 'SOMA Federal Agency Debt',
               'legacy_unit': 'B USD',
               'legacy_frequency': 'w',
               'reviewed_definition': ('Millions of U.S. Dollars',
                                       'W',
                                       'Weekly, As of Wednesday',
                                       'Not Seasonally Adjusted')},
 'WSHOMBLS': {'group': 'soma',
              'legacy_label': 'SOMA MBS Holdings (total)',
              'legacy_unit': 'B USD',
              'legacy_frequency': 'w',
              'reviewed_definition': None},
 'H41RESPPALDKNWA': {'group': 'fed_balance_sheet',
                     'legacy_label': 'Fed Repo Agreements (H.4.1)',
                     'legacy_unit': 'B USD',
                     'legacy_frequency': 'w',
                     'reviewed_definition': None},
 'WCBSL': {'group': 'fed_balance_sheet',
           'legacy_label': 'Central Bank Swap Lines',
           'legacy_unit': 'B USD',
           'legacy_frequency': 'w',
           'reviewed_definition': None},
 'TRESEGUSM052N': {'group': 'reserves',
                   'legacy_label': 'US International Reserves Excluding Gold',
                   'legacy_unit': 'B USD',
                   'legacy_frequency': 'm',
                   'reviewed_definition': None},
 'IORB': {'group': 'funding',
          'legacy_label': 'Interest on Reserve Balances',
          'legacy_unit': '%',
          'legacy_frequency': 'd',
          'reviewed_definition': ('Percent', 'D', 'Daily, 7-Day', 'Not Seasonally Adjusted')},
 'EFFR': {'group': 'funding',
          'legacy_label': 'Effective Fed Funds Rate',
          'legacy_unit': '%',
          'legacy_frequency': 'd',
          'reviewed_definition': ('Percent', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'OBFR': {'group': 'funding',
          'legacy_label': 'Overnight Bank Funding Rate',
          'legacy_unit': '%',
          'legacy_frequency': 'd',
          'reviewed_definition': ('Percent', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'M2V': {'group': 'money_supply',
         'legacy_label': 'Velocity of M2',
         'legacy_unit': 'ratio',
         'legacy_frequency': 'q',
         'reviewed_definition': ('Ratio', 'Q', 'Quarterly', 'Seasonally Adjusted')},
 'WCURCIR': {'group': 'money_supply',
             'legacy_label': 'Currency in Circulation (weekly average)',
             'legacy_unit': 'B USD',
             'legacy_frequency': 'w',
             'reviewed_definition': ('Millions of U.S. Dollars',
                                     'W',
                                     'Weekly, Ending Wednesday',
                                     'Not Seasonally Adjusted')},
 'DEXUSEU': {'group': 'dollar',
             'legacy_label': 'USD/EUR',
             'legacy_unit': 'rate',
             'legacy_frequency': 'd',
             'reviewed_definition': ('U.S. Dollars to One Euro', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'DEXJPUS': {'group': 'dollar',
             'legacy_label': 'JPY/USD',
             'legacy_unit': 'rate',
             'legacy_frequency': 'd',
             'reviewed_definition': ('Japanese Yen to One U.S. Dollar', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'DEXCHUS': {'group': 'dollar',
             'legacy_label': 'CNY/USD',
             'legacy_unit': 'rate',
             'legacy_frequency': 'd',
             'reviewed_definition': ('Chinese Yuan Renminbi to One U.S. Dollar',
                                     'D',
                                     'Daily',
                                     'Not Seasonally Adjusted')},
 'DEXKOUS': {'group': 'dollar',
             'legacy_label': 'KRW/USD',
             'legacy_unit': 'rate',
             'legacy_frequency': 'd',
             'reviewed_definition': ('South Korean Won to One U.S. Dollar',
                                     'D',
                                     'Daily',
                                     'Not Seasonally Adjusted')},
 'DEXBZUS': {'group': 'dollar',
             'legacy_label': 'BRL/USD',
             'legacy_unit': 'rate',
             'legacy_frequency': 'd',
             'reviewed_definition': ('Brazilian Reals to One U.S. Dollar',
                                     'D',
                                     'Daily',
                                     'Not Seasonally Adjusted')},
 'DFII5': {'group': 'yields',
           'legacy_label': '5Y TIPS Real Yield',
           'legacy_unit': '%',
           'legacy_frequency': 'd',
           'reviewed_definition': ('Percent', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'DFII30': {'group': 'yields',
            'legacy_label': '30Y TIPS Real Yield',
            'legacy_unit': '%',
            'legacy_frequency': 'd',
            'reviewed_definition': ('Percent', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'T10YIE': {'group': 'yields',
            'legacy_label': '10Y Breakeven Inflation',
            'legacy_unit': '%',
            'legacy_frequency': 'd',
            'reviewed_definition': ('Percent', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'T5YIE': {'group': 'yields',
           'legacy_label': '5Y Breakeven Inflation',
           'legacy_unit': '%',
           'legacy_frequency': 'd',
           'reviewed_definition': ('Percent', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'T5YIFR': {'group': 'yields',
            'legacy_label': '5y5y Forward Breakeven',
            'legacy_unit': '%',
            'legacy_frequency': 'd',
            'reviewed_definition': ('Percent', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'THREEFYTP10': {'group': 'yields',
                 'legacy_label': 'ACM 10Y Term Premium',
                 'legacy_unit': '%',
                 'legacy_frequency': 'm',
                 'reviewed_definition': ('Percent', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'DGS3MO': {'group': 'yields',
            'legacy_label': '3-Month Treasury Yield',
            'legacy_unit': '%',
            'legacy_frequency': 'd',
            'reviewed_definition': ('Percent', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'BAMLC0A0CM': {'group': 'credit',
                'legacy_label': 'IG Corporate Master OAS',
                'legacy_unit': '%',
                'legacy_frequency': 'd',
                'reviewed_definition': ('Percent', 'D', 'Daily, Close', 'Not Seasonally Adjusted')},
 'BAMLC0A1CAAA': {'group': 'credit',
                  'legacy_label': 'IG AAA OAS',
                  'legacy_unit': '%',
                  'legacy_frequency': 'd',
                  'reviewed_definition': ('Percent', 'D', 'Daily, Close', 'Not Seasonally Adjusted')},
 'BAMLC0A2CAA': {'group': 'credit',
                 'legacy_label': 'IG AA OAS',
                 'legacy_unit': '%',
                 'legacy_frequency': 'd',
                 'reviewed_definition': ('Percent', 'D', 'Daily, Close', 'Not Seasonally Adjusted')},
 'BAMLC0A3CA': {'group': 'credit',
                'legacy_label': 'IG A OAS',
                'legacy_unit': '%',
                'legacy_frequency': 'd',
                'reviewed_definition': ('Percent', 'D', 'Daily, Close', 'Not Seasonally Adjusted')},
 'BAMLC0A4CBBB': {'group': 'credit',
                  'legacy_label': 'IG BBB OAS',
                  'legacy_unit': '%',
                  'legacy_frequency': 'd',
                  'reviewed_definition': ('Percent', 'D', 'Daily, Close', 'Not Seasonally Adjusted')},
 'BAMLC0A0CMFOAS': {'group': 'credit',
                    'legacy_label': 'IG Financial OAS',
                    'legacy_unit': '%',
                    'legacy_frequency': 'd',
                    'reviewed_definition': None},
 'BAMLC0A0CMIOAS': {'group': 'credit',
                    'legacy_label': 'IG Industrial OAS',
                    'legacy_unit': '%',
                    'legacy_frequency': 'd',
                    'reviewed_definition': None},
 'BAMLC0A0CMUOAS': {'group': 'credit',
                    'legacy_label': 'IG Utility OAS',
                    'legacy_unit': '%',
                    'legacy_frequency': 'd',
                    'reviewed_definition': None},
 'BAMLH0A0HYM2': {'group': 'credit',
                  'legacy_label': 'HY Master II OAS',
                  'legacy_unit': '%',
                  'legacy_frequency': 'd',
                  'reviewed_definition': ('Percent', 'D', 'Daily, Close', 'Not Seasonally Adjusted')},
 'BAMLH0A1HYBB': {'group': 'credit',
                  'legacy_label': 'HY BB OAS',
                  'legacy_unit': '%',
                  'legacy_frequency': 'd',
                  'reviewed_definition': ('Percent', 'D', 'Daily, Close', 'Not Seasonally Adjusted')},
 'BAMLH0A2HYB': {'group': 'credit',
                 'legacy_label': 'HY Single-B OAS',
                 'legacy_unit': '%',
                 'legacy_frequency': 'd',
                 'reviewed_definition': ('Percent', 'D', 'Daily, Close', 'Not Seasonally Adjusted')},
 'BAMLH0A3HYC': {'group': 'credit',
                 'legacy_label': 'HY CCC & Lower OAS',
                 'legacy_unit': '%',
                 'legacy_frequency': 'd',
                 'reviewed_definition': ('Percent', 'D', 'Daily, Close', 'Not Seasonally Adjusted')},
 'BAMLEMCBPIOAS': {'group': 'credit',
                   'legacy_label': 'EM Corporate Plus OAS',
                   'legacy_unit': '%',
                   'legacy_frequency': 'd',
                   'reviewed_definition': ('Percent', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'BAMLEMHBHYCRPIOAS': {'group': 'credit',
                       'legacy_label': 'EM HY Corporate OAS',
                       'legacy_unit': '%',
                       'legacy_frequency': 'd',
                       'reviewed_definition': ('Percent', 'D', 'Daily', 'Not Seasonally Adjusted')},
 'BAMLHE00EHYIOAS': {'group': 'credit',
                     'legacy_label': 'Euro HY OAS',
                     'legacy_unit': '%',
                     'legacy_frequency': 'd',
                     'reviewed_definition': ('Percent', 'D', 'Daily, Close', 'Not Seasonally Adjusted')},
 'DRTSCILM': {'group': 'stress',
              'legacy_label': 'SLOOS: C&I Standards Tightening',
              'legacy_unit': '%',
              'legacy_frequency': 'q',
              'reviewed_definition': ('Percent', 'Q', 'Quarterly', 'Not Seasonally Adjusted')},
 'DRTSCLCC': {'group': 'stress',
              'legacy_label': 'SLOOS: Credit Card Tightening',
              'legacy_unit': '%',
              'legacy_frequency': 'q',
              'reviewed_definition': ('Percent', 'Q', 'Quarterly', 'Not Seasonally Adjusted')},
 'DRTSCLM': {'group': 'stress',
             'legacy_label': 'SLOOS: Mortgage Tightening',
             'legacy_unit': '%',
             'legacy_frequency': 'q',
             'reviewed_definition': None},
 'NFCI': {'group': 'stress',
          'legacy_label': 'Chicago Fed NFCI',
          'legacy_unit': 'index',
          'legacy_frequency': 'w',
          'reviewed_definition': ('Index', 'W', 'Weekly, Ending Friday', 'Not Seasonally Adjusted')},
 'ANFCI': {'group': 'stress',
           'legacy_label': 'Adjusted NFCI',
           'legacy_unit': 'index',
           'legacy_frequency': 'w',
           'reviewed_definition': ('Index', 'W', 'Weekly, Ending Friday', 'Not Seasonally Adjusted')},
 'STLFSI4': {'group': 'stress',
             'legacy_label': 'St. Louis Fed Financial Stress',
             'legacy_unit': 'index',
             'legacy_frequency': 'w',
             'reviewed_definition': ('Index', 'W', 'Weekly, Ending Friday', 'Not Seasonally Adjusted')},
 'OFRFSI': {'group': 'stress',
            'legacy_label': 'OFR Financial Stress Index',
            'legacy_unit': 'index',
            'legacy_frequency': 'd',
            'reviewed_definition': None},
 'SP500': {'group': 'equities',
           'legacy_label': 'S&P 500 price index',
           'legacy_unit': 'Index',
           'legacy_frequency': 'd',
           'reviewed_definition': ('Index', 'D', 'Daily, Close', 'Not Seasonally Adjusted')}}

SERIES = tuple(SPECS)
CONTEXT_KEYS = ('data/global-liquidity.json', 'data/china-liquidity.json', 'data/fred-cache.json')
DEFINITION_NOTES = {
    'WORAL': 'Federal Reserve repo assets: weekly Wednesday level, not overnight reverse-repo awards.',
    'DPCREDIT': 'Primary-credit interest rate in percent, not a discount-window borrowing balance.',
    'THREEFYTP10': 'Kim-Wright model term premium, daily observations; not the ACM estimate.',
    'DTWEXBGS': 'Federal Reserve broad trade-weighted dollar index; not ICE DXY.',
    'SP500': 'Daily closing price index, excluding dividends. Calendar return and distance from a window high are separate measures.',
    'WTREGEN': 'Weekly average ending Wednesday, distinct from the Wednesday WALCL stock.',
}
METHOD_SOURCES = {sid: 'https://fred.stlouisfed.org/series/'+sid for sid in DEFINITION_NOTES}
