"""Preserved configured universe; categories are coverage groups, not complete markets."""
ETFS = {'BROAD_EQUITY_US': ['SPY', 'VOO', 'IVV', 'QQQ', 'VTI', 'IWM', 'DIA', 'RSP'],
 'SECTOR_EQUITY': ['XLK',
                   'XLF',
                   'XLE',
                   'XLV',
                   'XLI',
                   'XLY',
                   'XLP',
                   'XLU',
                   'XLB',
                   'XLRE',
                   'XLC',
                   'SMH',
                   'XBI',
                   'KRE',
                   'ITB',
                   'XOP'],
 'THEMATIC': ['ARKK',
              'ICLN',
              'TAN',
              'BOTZ',
              'ROBO',
              'LIT',
              'URA',
              'NLR',
              'IGV',
              'HACK',
              'CIBR',
              'FINX',
              'DRIV'],
 'INTERNATIONAL': ['EFA', 'VEA', 'EEM', 'VWO', 'FXI', 'EWZ', 'EWJ', 'INDA', 'ASHR'],
 'COUNTRY': ['MCHI',
             'EWG',
             'EWY',
             'EWT',
             'EWU',
             'EWC',
             'EWA',
             'EWW',
             'EZA',
             'TUR',
             'EPOL',
             'ARGT',
             'EIDO',
             'VNM',
             'THD',
             'EWQ',
             'EWL',
             'EWI',
             'EWP',
             'EWS'],
 'RATES_TREASURIES': ['TLT',
                      'IEF',
                      'SHY',
                      'GOVT',
                      'BIL',
                      'SGOV',
                      'SHV',
                      'VGSH',
                      'IEI',
                      'VGIT',
                      'VGLT',
                      'EDV'],
 'CREDIT': ['LQD',
            'HYG',
            'JNK',
            'AGG',
            'BND',
            'VCIT',
            'VCSH',
            'USHY',
            'SJNK',
            'BKLN',
            'SRLN',
            'EMB',
            'MUB'],
 'TIPS_INFLATION': ['TIP', 'SCHP', 'VTIP', 'STIP'],
 'CRYPTO_ETF': ['IBIT', 'FBTC', 'ETHA', 'BITO'],
 'COMMODITIES': ['GLD', 'SLV', 'USO', 'DBC', 'DBA', 'UNG', 'GDX'],
 'CRYPTO': ['IBIT', 'FBTC', 'ETHA', 'BITO', 'GBTC'],
 'VOLATILITY': ['VXX', 'UVXY', 'SVXY'],
 'DIVIDEND_VALUE': ['SCHD', 'VYM', 'VTV', 'DVY', 'VIG'],
 'GROWTH': ['VUG', 'IWF', 'MGK', 'SCHG'],
 'LEVERED_INVERSE': ['TQQQ', 'SQQQ', 'SSO', 'SDS', 'UPRO', 'SPXU', 'QLD', 'QID', 'TBT']}

PROSHARES = ('BITO', 'QID', 'QLD', 'SDS', 'SPXU', 'SQQQ', 'SSO', 'SVXY', 'TBT', 'TQQQ', 'UPRO', 'UVXY')

WRAPPER_COMPLEX = {'SP500': ['SPY', 'IVV', 'VOO', 'SPLG'],
 'NASDAQ100': ['QQQ', 'QQQM'],
 'TOTAL_US': ['VTI', 'ITOT', 'SCHB'],
 'RUSSELL2000': ['IWM', 'VTWO'],
 'EMERGING': ['EEM', 'IEMG', 'VWO'],
 'DEV_INTL': ['EFA', 'IEFA', 'VEA'],
 'GOLD': ['GLD', 'IAU', 'GLDM', 'SGOL'],
 'BITCOIN': ['IBIT', 'FBTC', 'GBTC', 'ARKB', 'BITB'],
 'US_AGG_BOND': ['AGG', 'BND'],
 'HIGH_YIELD': ['HYG', 'JNK'],
 'LONG_TREASURY': ['TLT', 'VGLT']}

