import json, boto3, base64
lam=boto3.client("lambda",region_name="us-east-1"); s3=boto3.client("s3",region_name="us-east-1")
r=lam.invoke(FunctionName="justhodl-retail-sentiment", InvocationType="RequestResponse", LogType="Tail")
print("invoke:", r.get("StatusCode"), "err:", r.get("FunctionError"))
log=base64.b64decode(r.get("LogResult","")).decode("utf-8","ignore")
for ln in log.splitlines():
    if any(k in ln for k in ("Traceback","Error","[retail-","alerts:","corroboration:","attention-history:")) and "tg err" not in ln: print("  LOG:",ln[:150])
d=json.loads(s3.get_object(Bucket="justhodl-dashboard-live",Key="data/retail-sentiment.json")["Body"].read())
rk=d.get("ranked",{})
print("\n=== ALL 11 FEATURES — payload presence ===")
print("#1 track_record:", bool(d.get("track_record")), "| signals_logged:", d.get("signals_logged"))
print("#2 crowded_exhaustion/capitulation:", len(rk.get("crowded_exhaustion",[])), "/", len(rk.get("capitulation",[])))
print("#3 squeeze_radar:", len(rk.get("squeeze_radar",[])))
print("#4 attention history fields on top names:", sum(1 for e in d.get("top_30_by_mentions",[]) if e.get("days_tracked")))
print("#6 multi_venue_confirmed:", len(rk.get("multi_venue_confirmed",[])))
print("#7 flow_leaders:", len(rk.get("flow_leaders",[])))
print("#8 theme_rollup:", len(d.get("theme_rollup",[])), "themes")
print("#9 suspicious + data_quality:", len(rk.get("suspicious",[])), "|", bool(d.get("data_quality")))
print("#10 igniting/peaking/fading + persistence:", len(rk.get("igniting",[])),"/",len(rk.get("peaking",[])),"/",len(rk.get("fading",[])), "| persist:", bool(d.get("signal_persistence")))
print("#11 recent_alerts:", len(d.get("recent_alerts",[])), "| alert state written")
print("\nelapsed_seconds:", d.get("elapsed_seconds"), "| n_with_price:", d.get("n_with_price"))
