#!/usr/bin/env python3
"""Bake source-bound output references plus separately verified public payload health.
Only HTTP 404 proves absence; permission, transport, validation and unresolved-family
failures remain explicit unknown states. A page reference never certifies runtime rendering.
"""
import glob, json, re, sys, time
from pathlib import Path
from page_sources import scan_pages
from concurrent.futures import ThreadPoolExecutor
from email.utils import parsedate_to_datetime

BUCKET = "https://justhodl.ai"


def get(url, to=12):
    import urllib.request, urllib.error
    try:
        r = urllib.request.urlopen(urllib.request.Request(
            url, headers={"User-Agent": "Mozilla/5.0 jh"}), timeout=to)
        return r.getcode(), r.read(4 * 1024 * 1024 + 1), dict(r.headers)
    except urllib.error.HTTPError as exc:
        return exc.code,b"",dict(exc.headers or {})
    except Exception:
        return None, b"", {}


def load_entries(build_dir="."):
    """Union of two sources so the directory can never go stale on its own:
      * engine-manifest.json -- regenerated by gen_engine_manifest.py on EVERY deploy from aws/lambdas (authoritative
        list of engines and the keys they write). QA audit 2026-09-07: engines.html was baked from
        data/engine-registry.json alone, which has had no writer since 2026-07-07 (667 engines vs 860 in the fleet).
      * data/engine-registry.json (S3, optional) -- adds description/schedule/consumers for the engines it knows.
    """
    entries = {}
    for mpath in (f"{build_dir}/engine-manifest.json", "engine-manifest.json"):
        try:
            m = json.load(open(mpath, encoding="utf-8"))
            for e in m.get("engines") or []:
                if e.get("engine"):
                    entries[e["engine"]] = {"name": e["engine"], "outs": list(e.get("keys") or []), "description": e.get("description") or "", "source": "manifest", "key_patterns": list(e.get("key_patterns") or []), "unresolved_writes": e.get("unresolved_writes") or []}
            break
        except Exception:
            continue
    c, rb, _ = get(f"{BUCKET}/data/engine-registry.json?t={int(time.time())}")
    try:
        reg = json.loads(rb) if c == 200 else {}
    except Exception:
        reg = {}
    raw = reg.get("engines", reg) if isinstance(reg, dict) else reg
    records = ({k: {**(v if isinstance(v, dict) else {}), "name": k} for k, v in raw.items()}
               if isinstance(raw, dict) else {e.get("name", str(i)): e for i, e in enumerate(raw or [])})
    for name, r in records.items():
        prior = entries.get(name) or {"name": name, "outs": [], "description": "", "source": "registry"}
        outs = list(prior.get("outs") or [])  # registry hints never confer producer ownership
        merged = {**r, **prior, "outs": outs, "description": prior.get("description") or r.get("description") or r.get("doc") or ""}
        merged["unverified_registry_outs"] = [k for k in (r.get("outs") or r.get("outputs") or []) if k not in outs]
        merged["source"] = "manifest+registry" if prior.get("source") == "manifest" else "registry"
        entries[name] = merged
    return entries, (reg.get("generated_at") if isinstance(reg, dict) else None)


def main(build_dir="."):
    entries, registry_asof = load_entries(build_dir)

    page_graphs = scan_pages(Path(build_dir))
    page_keys = {page:set(rec["keys"]) for page,rec in page_graphs.items() if page != "engines.html"}
    unique_feeds = set()
    for e in entries.values():
        unique_feeds.update(e.get("outs") or [])

    cadence={}
    try:
        settings=json.load(open(Path(build_dir)/"config/feed-sla.json"))
        for key,value in settings.items():
            if isinstance(value,(int,float)) and value>0:cadence[key]=value
            elif isinstance(value,dict):
                hours=value.get("max_age_hours",value.get("max_age_h"))
                if isinstance(hours,(int,float)) and hours>0:cadence[key]=hours
    except (OSError,ValueError):pass
    def inspect_feed(key):
        if "*" in key:
            return {"state":"pattern_requires_index","present":None,"valid":False,"age_h":None,"fresh":False}
        code, body, headers = get(f"{BUCKET}/{key}?t={int(time.time())}")
        result={"http_status":code,"present":True if code==200 else False if code==404 else None,"valid":False,"fresh":False,"age_h":None}
        if code != 200:
            result["state"]="missing" if code==404 else "inaccessible" if code in (401,403) else "fetch_failed"
            return result
        if len(body)>4*1024*1024:
            result["state"]="body_exceeds_validation_limit";return result
        try:
            obj=json.loads(body)
            if obj is None or obj == {} or obj == []:raise ValueError("empty")
            result["valid"]=True
        except (ValueError,TypeError):
            result["state"]="invalid_or_empty";return result
        source_ts=next((obj.get(k) for k in ("generated_at","as_of","asof","updated_at","timestamp","date") if isinstance(obj,dict) and obj.get(k)),None)
        if source_ts:
            try:
                from datetime import datetime,timezone
                dt=datetime.fromisoformat(str(source_ts).replace("Z","+00:00"))
                if not dt.tzinfo:dt=dt.replace(tzinfo=timezone.utc)
                age=(time.time()-dt.timestamp())/3600
                max_age=cadence.get(key,24)
                result.update(age_h=round(age,1),fresh=0<=age<max_age,state="fresh" if 0<=age<max_age else "future_timestamp" if age<0 else "stale",freshness_basis="payload",max_age_h=max_age,cadence_basis="feed_sla" if key in cadence else "default_24h")
                return result
            except (ValueError,TypeError):pass
        result["state"]="source_time_unknown"
        return result

    observations={}
    with ThreadPoolExecutor(max_workers=16) as ex:
        observations=dict(zip(sorted(unique_feeds),ex.map(inspect_feed,sorted(unique_feeds))))

    rows = []
    for name, e in sorted(entries.items()):
        outs = e.get("outs") or []
        # per-output state: declared -> present on S3 -> referenced by a page -> fresh (audit C-3/C-5)
        outputs = []
        for o in outs:
            observation=observations[o]
            refs=sorted(pg for pg,keys in page_keys.items() if o in keys)
            outputs.append({"key":o,**observation,"pages":refs,"ref_kind":["exact_path"] if refs else [],"rendered":None,"field_coverage":None})
        for pattern in e.get("key_patterns") or []:
            outputs.append({"key":pattern,"state":"pattern_requires_index","present":None,"valid":False,"age_h":None,"fresh":False,"pages":[],"ref_kind":[],"rendered":None,"field_coverage":None})
        pages=sorted({p for o in outputs for p in o["pages"]})
        referenced=[o for o in outputs if o["pages"]];present=[o for o in outputs if o["present"]]
        ready=[o for o in outputs if o["valid"] and o["fresh"] and o["pages"]]
        if not outputs:status="no-outs"
        elif ready and len(ready)==len(outputs):status="wired"
        elif ready:status="partial"
        elif any(o['present'] is None or o['state'] in ('source_time_unknown','future_timestamp','body_exceeds_validation_limit') for o in outputs):status='wired-unverified-feed' if referenced else 'declared-unverified'
        elif referenced and any(o["state"]=='invalid_or_empty' for o in referenced):status='wired-invalid-feed'
        elif referenced and any(o["valid"] for o in referenced):status="wired-stale-feed"
        elif referenced:status="wired-missing-feed"
        elif not present:status="declared-absent"
        elif any(o["fresh"] for o in present):status="orphan-fresh"
        else:status="orphan-stale"
        rows.append({"name":name,"outs":[o["key"] for o in outputs],"pages":pages,
                     "age_h":max((o["age_h"] for o in outputs if o["age_h"] is not None),default=None),
                     "status":status,"n_outputs":len(outputs),"n_present":len(present),"n_referenced":len(referenced),
                     "outputs":outputs,"unresolved_writes":e.get("unresolved_writes") or [],
                     "unverified_registry_outs":e.get("unverified_registry_outs") or [],
                     "coverage_status":"runtime_not_verified","missing_scripts":{p:page_graphs[p]["missing_scripts"] for p in pages if page_graphs[p]["missing_scripts"]}})

    counts = {}
    for r in rows:
        counts[r["status"]] = counts.get(r["status"], 0) + 1

    data = {"generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "total": len(rows), "counts": counts, "rows": rows,
            "sources": {"engine_manifest": sum(1 for e in entries.values() if "manifest" in (e.get("source") or "")),
                        "registry_only": sum(1 for e in entries.values() if e.get("source") == "registry"), "registry_generated_at": registry_asof}}
    try:  # fresh registry for consumers that read the July doc: same shape, every deploy
        import os
        os.makedirs(f"{build_dir}/config", exist_ok=True)
        with open(f"{build_dir}/config/engine-registry.json", "w", encoding="utf-8") as f:
            json.dump({"generated_at": data["generated_at"], "n_engines": len(entries), "source": "engine-manifest.json + data/engine-registry.json (deploy-time union)",
                       "engines": {k: {"description": v.get("description", ""), "outs": v.get("outs") or [], "source": v.get("source")} for k, v in sorted(entries.items())}},
                      f, separators=(",", ":"))
    except Exception as exc:  # noqa: BLE001
        print(f"engine registry copy skipped: {exc}")

    path = f"{build_dir}/engines.html"
    s = open(path, encoding="utf-8").read()
    marker = "__JH_ENGINE_DATA__"
    if marker not in s:
        print("engines.html: bake marker not found, skipping")
        return
    s = s.replace(marker, json.dumps(data, separators=(",", ":")))
    open(path, "w", encoding="utf-8").write(s)
    print(f"engine directory baked: {len(rows)} engines, counts={counts}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else ".")
