#!/usr/bin/env python3
"""scripts/bake_engine_directory.py — computes the REAL, live status of all
661 registered engines and bakes it into engines.html at deploy time (same
mechanism as bake_right_rail.py: public HTTPS only, no AWS creds needed in
this workflow — Last-Modified header from data/*.json IS the freshness
source, exactly like the rail's own feed-freshness checks).

For each engine: is ANY of its declared outs[] referenced by ANY live page's
actual source (exact string containment, not name-fuzzy-matching)? If yes,
which page(s). If no, is the underlying feed still fresh (engine running,
just invisible) or stale/dead? This directly answers 'is my engine wired to
a page' for the whole fleet in one place, replacing guesswork.
"""
import glob, json, re, sys, time
from concurrent.futures import ThreadPoolExecutor
from email.utils import parsedate_to_datetime

BUCKET = "https://justhodl.ai"


def get(url, to=12):
    import urllib.request
    try:
        r = urllib.request.urlopen(urllib.request.Request(
            url, headers={"User-Agent": "Mozilla/5.0 jh"}), timeout=to)
        return r.getcode(), r.read(), dict(r.headers)
    except Exception:
        return None, b"", {}


def load_entries(build_dir="."):
    """Union of two sources so the directory can never go stale on its own:
      * engine-manifest.json -- regenerated by gen_engine_manifest.py on EVERY deploy from aws/lambdas (authoritative
        list of engines and the keys they write). QA audit 2026-09-07: engines.html was baked from
        data/engine-registry.json alone, which has had no writer since 2026-07-07 (667 engines vs 860 in the fleet).
      * data/engine-registry.json (S3, optional) -- adds description/schedule/consumers for the engines it knows.
    """
    entries = {}
    for mpath in (f"{build_dir}/engine-manifest.json", "engine-manifest.json"):
        try:
            m = json.load(open(mpath, encoding="utf-8"))
            for e in m.get("engines") or []:
                if e.get("engine"):
                    entries[e["engine"]] = {"name": e["engine"], "outs": list(e.get("keys") or []), "description": e.get("description") or "", "source": "manifest"}
            break
        except Exception:
            continue
    c, rb, _ = get(f"{BUCKET}/data/engine-registry.json?t={int(time.time())}")
    try:
        reg = json.loads(rb) if c == 200 else {}
    except Exception:
        reg = {}
    raw = reg.get("engines", reg) if isinstance(reg, dict) else reg
    records = ({k: {**(v if isinstance(v, dict) else {}), "name": k} for k, v in raw.items()}
               if isinstance(raw, dict) else {e.get("name", str(i)): e for i, e in enumerate(raw or [])})
    for name, r in records.items():
        prior = entries.get(name) or {"name": name, "outs": [], "description": "", "source": "registry"}
        outs = list(dict.fromkeys(list(prior.get("outs") or []) + list(r.get("outs") or r.get("outputs") or [])))
        merged = {**r, **prior, "outs": outs, "description": prior.get("description") or r.get("description") or r.get("doc") or ""}
        merged["source"] = "manifest+registry" if prior.get("source") == "manifest" else "registry"
        entries[name] = merged
    return entries, (reg.get("generated_at") if isinstance(reg, dict) else None)


def main(build_dir="."):
    entries, registry_asof = load_entries(build_dir)

    # read every page's ALREADY-ASSEMBLED source in _site (no network needed for this part)
    page_src = {}
    for f in glob.glob(f"{build_dir}/*.html"):
        name = f.split("/")[-1]
        if name in ("engines.html",):
            continue
        page_src[name] = open(f, encoding="utf-8", errors="replace").read()

    unique_feeds = set()
    for e in entries.values():
        unique_feeds.update(e.get("outs") or [])

    def age_of(key):
        c2, _, hdrs = get(f"{BUCKET}/{key}?t={int(time.time())}")
        lm = hdrs.get("Last-Modified") if c2 == 200 else None
        if not lm:
            return None
        try:
            return round((time.time() - parsedate_to_datetime(lm).timestamp()) / 3600, 1)
        except Exception:
            return None

    ages = {}
    with ThreadPoolExecutor(max_workers=16) as ex:
        for k, a in zip(unique_feeds, ex.map(age_of, unique_feeds)):
            ages[k] = a

    def referenced(out, src):
        # Pages fetch feeds three ways: full path literal, constructed base+"name.json",
        # or a quoted stem inside a JS key list. Any of them means the page displays it.
        if out in src:
            return True
        bare = out.split("/")[-1]
        if bare in src:
            return True
        stem = bare.rsplit(".", 1)[0]
        return re.search(r'["\']' + re.escape(stem) + r'["\']', src) is not None

    rows = []
    for name, e in sorted(entries.items()):
        outs = e.get("outs") or []
        pages = sorted({p for p, src in page_src.items()
                        if any(referenced(o, src) for o in outs)}) if outs else []
        best_age = min((ages[o] for o in outs if ages.get(o) is not None), default=None)
        if not outs:
            status = "no-outs"
        elif pages:
            status = "wired"
        elif best_age is not None and best_age < 24:
            status = "orphan-fresh"
        elif best_age is not None:
            status = "orphan-stale"
        else:
            status = "orphan-dead"
        rows.append({"name": name, "outs": outs[:3], "pages": pages[:3],
                      "age_h": best_age, "status": status})

    counts = {}
    for r in rows:
        counts[r["status"]] = counts.get(r["status"], 0) + 1

    data = {"generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "total": len(rows), "counts": counts, "rows": rows,
            "sources": {"engine_manifest": sum(1 for e in entries.values() if "manifest" in (e.get("source") or "")),
                        "registry_only": sum(1 for e in entries.values() if e.get("source") == "registry"), "registry_generated_at": registry_asof}}
    try:  # fresh registry for consumers that read the July doc: same shape, every deploy
        import os
        os.makedirs(f"{build_dir}/config", exist_ok=True)
        with open(f"{build_dir}/config/engine-registry.json", "w", encoding="utf-8") as f:
            json.dump({"generated_at": data["generated_at"], "n_engines": len(entries), "source": "engine-manifest.json + data/engine-registry.json (deploy-time union)",
                       "engines": {k: {"description": v.get("description", ""), "outs": v.get("outs") or [], "source": v.get("source")} for k, v in sorted(entries.items())}},
                      f, separators=(",", ":"))
    except Exception as exc:  # noqa: BLE001
        print(f"engine registry copy skipped: {exc}")

    path = f"{build_dir}/engines.html"
    s = open(path, encoding="utf-8").read()
    marker = "__JH_ENGINE_DATA__"
    if marker not in s:
        print("engines.html: bake marker not found, skipping")
        return
    s = s.replace(marker, json.dumps(data, separators=(",", ":")))
    open(path, "w", encoding="utf-8").write(s)
    print(f"engine directory baked: {len(rows)} engines, counts={counts}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else ".")
