"""Reject repository-only directories in a built public site. Metadata only."""
from pathlib import Path
import json,sys
from page_sources import DENY

# Config is intentionally generated by the offline bakers for public consumers.
# Its body-level policies are separate. Infrastructure/test trees never belong
# at the public root, even if a source fixture happens to contain HTML.
FORBIDDEN_ROOTS=frozenset(DENY)-{'config'}

def check(root):
 root=Path(root)
 if not root.is_dir() or root.is_symlink():raise ValueError('Built site directory required')
 bad=sorted(p.name for p in root.iterdir() if p.name in FORBIDDEN_ROOTS)
 if bad:raise ValueError('Repository-only roots in public artifact: '+', '.join(bad))
 return {'status':'public_artifact_boundary_checked','forbidden_roots':0,'content_bodies_read':0}

if __name__=='__main__':
 try:
  if len(sys.argv)!=2:raise ValueError('One built site path required')
  print(json.dumps(check(sys.argv[1]),sort_keys=True))
 except (ValueError,OSError) as exc:
  print(str(exc),file=sys.stderr);sys.exit(1)
