#!/usr/bin/env python3
"""Regenerate STATE.md -- the one-file session-start snapshot.

Run by run-ops.yml after every ops execution (continue-on-error) and
committed back with the reports, so every fresh session gets the live
state of the ops pipeline from a single `cat STATE.md` instead of a
multi-call recon (pending scan + ran scan + report reads + log tails).
Pure stdlib, no AWS, safe everywhere.
"""
import json
import re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OPS = ROOT / "aws" / "ops"


def ops_num(name):
    m = re.match(r"ops_(\d+)_", name)
    return int(m.group(1)) if m else None


def main():
    pending = sorted(p.name for p in (OPS / "pending").glob("ops_*.py"))
    ran_nums = [n for n in (ops_num(p.name)
                            for p in (OPS / "ran").glob("ops_*.py"))
                if n is not None]
    pend_nums = [n for n in (ops_num(p) for p in pending) if n is not None]
    next_free = max(ran_nums + pend_nums, default=0) + 1

    reports = []
    for rp in (OPS / "reports").glob("[0-9]*.json"):
        try:
            num = int(rp.stem)
            d = json.loads(rp.read_text())
            reports.append((num, d))
        except Exception:
            continue
    reports.sort(key=lambda x: -x[0])

    lines = [
        "# STATE.md -- ops pipeline snapshot (auto-generated by "
        "aws/ops/_gen_state.py via run-ops.yml; do not hand-edit)",
        "",
        "- generated_at: %s" % datetime.now(timezone.utc).isoformat(),
        "- next_free_ops_number: **%d**" % next_free,
        "- pending_count: %d" % len(pending),
        "",
        "## Pending ops (will run on next matching push)",
        "",
    ]
    lines += (["- `%s`" % p for p in pending] or ["- (none)"])
    lines += ["", "## Last ops verdicts (newest first)", ""]
    for num, d in reports[:8]:
        v = d.get("verdict", "?")
        fails = d.get("fails") or []
        warns = d.get("warns") or []
        extra = ""
        if fails:
            extra = " -- first fail: %s" % str(fails[0])[:140]
        elif warns:
            extra = " -- %d warn(s): %s" % (len(warns), str(warns[0])[:100])
        lines.append("- **%d** %s (%s)%s" % (num, v, d.get("ts", "")[:16],
                                             extra))
    if not reports:
        lines.append("- (no reports)")
    lines += [
        "",
        "## Session-start shortcut",
        "",
        "`cat STATE.md` replaces: pending/ scan + ran/ scan + last-report",
        "reads + next-ops-number computation. Full protocol: AUTONOMY.md +",
        "the protected MASTER BOOTSTRAP memory card. Before pushing any ops",
        "script: `python aws/ops/_preflight.py <files...>`.",
        "",
    ]
    (ROOT / "STATE.md").write_text("\n".join(lines))
    print("STATE.md regenerated: next_free=%d pending=%d reports=%d"
          % (next_free, len(pending), len(reports)))


if __name__ == "__main__":
    main()
